# Glutamate response analysis run

Use this notebook to load one session, run activation/tuning/sequence analyses, and save standardized output tables.

In [1]:
import os
import glob
import zipfile
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from vip_slap2_analysis.glutamate.analysis import (
    GlutamateAnalysisConfig,
    resolve_glutamate_analysis_paths,
    run_glutamate_analysis,
)

from vip_slap2_analysis.io.session_registry import VIPSessionRegistry

import seaborn as sns
sns.set_style('white')
params = {'legend.fontsize': 'x-large',
         'axes.labelsize': 'xx-large',
         'axes.titlesize':'xx-large',
         'xtick.labelsize':'xx-large',
         'ytick.labelsize':'xx-large'}
plt.rcParams.update(params)

from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
%load_ext autoreload
%autoreload 2

In [10]:
target_mice = [826033]

In [ ]:
registry = VIPSessionRegistry.from_basepath(
    r'\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics'
)

process_df = registry.sessions(
    subject_ids=target_mice,
    exclude_session_types=["expression_check"],
    paradigms=["change_detection_passive"],
)

assets = [registry.resolve_assets(row) for _, row in process_df.iterrows()]

In [9]:
assets[0]

SessionAssets(session_id='826033_2026-02-17_13-13-55', subject_id=826033, session_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f+RCaMP3/826033/826033_2026-02-17_13-13-55'), summary_mat=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f+RCaMP3/826033/826033_2026-02-17_13-13-55/826033_2026-02-17_13-13-55_slap2_2026-02-17_13-13-55/source_extraction/ExperimentSummary/SummaryLoCo-260218-072719.mat'), bonsai_event_log_csv=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f+RCaMP3/826033/826033_2026-02-17_13-13-55/826033_2026-02-17_13-13-55/behavior/VCO1_Behavior.harp/bonsai_event_log.csv'), harp_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f+RCaMP3/826033/826033_2026-02-17_13-13-55/826033_2026-02-17_13-13-55/behavior/VCO1_Behavior.harp'), photodiode_pkl=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f+RCaMP3/826033/826033_2026-02-17_13-13-55/826033_2026-02-17_13-13-55/behavior/VCO1_Behavior.harp/extracted_files/photodiode.pkl'), harp_df_csv=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f+RCaMP3/826033/826033_2026-02-17_13-13-55/826033_2026-02-17_13-13-55/behavior/VCO1_Behavior.harp/extracted_files/HARP_df.csv'), qc_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f+RCaMP3/826033/826033_2026-02-17_13-13-55/analysis/qc'), derived_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f+RCaMP3/826033/826033_2026-02-17_13-13-55/analysis/derived'), metadata={'session_id': '826033_2026-02-17_13-13-55', 'subject_id': 826033, 'session_#': 2, 'session_date': Timestamp('2026-02-17 00:00:00'), 'indicator1': 'iGluSnFR4', 'indicator2': 'RCaMP3', 'dmd1_depth': 50, 'dmd2_depth': 200, 'paradigm': 'change_detection_passive', 'session_type': 'familiar', 'stimulus': 'images_A', 'experimentor': 'Andrew Shelton', 'instrument_name': 'slap2_albert', 'instrument_id': 'SLAP2_1', 'camera_type': 'spinnaker', 'has raster ROI?': 'yes', 'has integration roi?': 'no', 'behavior_rig': 'VCO.1', 'quality': 'good', 'flags': 'stimlus ID not recorded properly', 'session_dir': WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f+RCaMP3/826033/826033_2026-02-17_13-13-55'), 'purpose': nan, 'notes': nan})

In [6]:
for asset in assets[1:]:
    session_root = asset.session_dir
    paths = resolve_glutamate_analysis_paths(session_root)
    print(paths)
    
    config = GlutamateAnalysisConfig(
    alpha=0.05,
    min_events_activation=8,
    min_events_tuning_per_image=5,
    min_images_for_tuning=4,
    min_images_for_sequence=4,
    min_positions_for_sequence=3,
    n_shuffles_tuning=1000,
    random_seed=0,
    )
    config
    
    results = run_glutamate_analysis(session_root, config=config)
    {k: v.shape for k, v in results.items() if hasattr(v, 'shape')}
    
    activation_summary = results['activation_summary_table']
    tuning_summary = results['tuning_summary_table']
    sequence_summary = results['sequence_summary_table']

    display(activation_summary.head())
    display(tuning_summary.head())
    display(sequence_summary.head())
    
    output_dir = resolve_glutamate_analysis_paths(session_root).output_dir
    print(output_dir)
    print(sorted(p.name for p in output_dir.iterdir()))

GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0000,image,2277,-20.015213,-23.085767,none,3.356907e-02,no_change,1.007072e-01
1,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0001,image,2277,11.062568,10.113008,none,1.885622e-01,no_change,3.431282e-01
2,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,image,2277,62.247024,75.345806,up,1.833899e-10,activated,5.501698e-10
3,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0003,image,2277,51.070708,94.594795,up,5.779422e-15,activated,1.733827e-14
4,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0004,image,2277,-94.736861,-159.029189,down,1.601894e-34,deactivated,4.805682e-34

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,2277,7,0.016428,0.000999,6.161776e-06,imk01643,209.877494,194.113103,148.201225,79.053404,False,0.001556,1.247760e-05
1,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0003,2277,7,0.029130,0.000999,2.518969e-11,imk01378,186.991674,110.479186,69.505918,6.580640,False,0.001556,7.847557e-11
2,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0005,2277,7,0.090994,0.000999,1.177659e-48,imk01643,622.228322,622.815466,348.406914,133.607561,True,0.001556,1.907808e-47
3,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0006,2277,7,0.007872,0.009990,5.606826e-03,imk01220,128.009940,143.542635,117.889387,40.459149,False,0.013051,7.569215e-03
4,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0007,2277,7,0.017145,0.000999,1.310140e-05,imk00895,117.075662,97.514651,58.983192,8.945764,False,0.001556,2.526698e-05

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,7,-8.076821,1.000000,92.015880,-276.286065,102.560630,305.798560,360.275090,0.21875,stable,0.454327
1,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0003,7,-0.722605,0.858060,44.223449,-122.997100,70.886819,97.337593,311.847098,0.68750,stable,0.807065
2,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0005,7,-7.898842,1.000000,349.948409,-172.897076,448.438109,690.713444,217.207262,0.03125,stable,0.158203
3,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0006,7,-1.355001,0.898264,75.070938,-176.820424,22.233419,199.150761,120.485039,0.68750,stable,0.807065
4,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0007,7,-5.214190,1.000000,64.219228,-54.981275,47.567511,173.151400,105.636095,0.21875,stable,0.454327

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-25_803496\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-28_803496/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-28_803496/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-28_803496/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-28_803496/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,809436_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0000,image,2279,-7.322039,-7.027186,none,0.058468,no_change,0.175403
1,809436_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0001,image,2279,0.372955,-2.741992,none,0.960449,no_change,0.960449
2,809436_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0002,image,2279,-2.073546,-2.230991,none,0.596116,no_change,0.596116
3,809436_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0003,image,2279,2.022670,5.343727,none,0.206030,no_change,0.309045
4,809436_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0004,image,2279,-2.952058,1.917886,none,0.838605,no_change,0.988757

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,809436_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0041,2279,7,0.002612,0.448551,0.338585,imk01057,27.886124,26.540467,20.937123,4.677125,False,0.448551,0.38367
1,809436_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0053,2279,7,0.003144,0.296703,0.383670,imk01220,29.504172,22.208108,15.598786,7.173881,False,0.395604,0.38367
2,809436_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0093,2279,7,0.003648,0.192807,0.128477,imk01643,33.750144,24.776745,11.670331,6.556310,False,0.385614,0.38367
3,809436_2025-07-28_08-04-39,803496,DMD2,DMD2_syn0013,2279,7,0.003843,0.188811,0.355794,imk01643,23.717630,15.665176,7.588627,4.755249,False,0.385614,0.38367

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,809436_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0041,7,-1.976708,0.424786,10.153110,16.869437,11.745588,19.978627,32.773169,0.468750,stable,0.6250
1,809436_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0053,7,-0.716319,1.000000,17.410460,-25.678129,0.189372,53.471605,-40.614676,0.375000,stable,0.6250
2,809436_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0093,7,-2.309091,-0.496850,45.656524,136.860349,50.821270,-102.020290,8.017768,0.296875,stable,0.6250
3,809436_2025-07-28_08-04-39,803496,DMD2,DMD2_syn0013,7,1.239029,1.000000,23.813044,-53.880254,15.105638,58.317342,-36.632756,0.687500,stable,0.6875

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-28_803496\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-29_803496/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-29_803496/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-29_803496/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-29_803496/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,image,2279,21.644501,42.219638,up,3.327419e-05,activated,9.982258e-05
1,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0001,image,2279,-31.003103,-38.643089,down,2.155098e-12,deactivated,6.465293e-12
2,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0002,image,2279,-15.272386,-33.967593,down,1.450552e-07,deactivated,4.351656e-07
3,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0003,image,2279,8.018818,5.397400,none,7.747566e-02,no_change,2.324270e-01
4,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0004,image,2279,16.073048,24.712531,up,6.276711e-05,activated,1.883013e-04

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,2279,7,0.011122,0.001998,3.004001e-03,imk01057,107.098150,53.809699,36.443897,34.705245,False,0.002506,3.528509e-03
1,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0004,2279,7,0.008375,0.004995,1.967942e-03,imk01097,54.952463,53.356200,41.735212,2.455001,False,0.006060,2.510822e-03
2,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0010,2279,7,0.250095,0.000999,1.459657e-121,imk01057,484.644726,453.464113,319.470543,39.177590,True,0.001297,5.400731e-120
3,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0011,2279,7,0.015585,0.000999,1.506017e-09,imk01097,105.325181,79.103289,73.662309,31.542690,False,0.001297,3.184151e-09
4,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0013,2279,7,0.006938,0.010989,2.851575e-02,imk01057,78.596756,67.495887,41.400131,43.287376,False,0.012706,3.103185e-02

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,7,-5.336103,0.981937,72.001657,0.653214,123.426447,77.502113,-5.381142,0.015625,stable,0.165179
1,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0004,7,-0.975812,-0.443855,32.065475,83.247913,32.972522,-15.784800,-56.832736,0.218750,stable,0.476103
2,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0010,7,-5.869332,0.023698,207.674063,162.834655,244.382419,22.660666,179.737484,0.046875,stable,0.321181
3,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0011,7,-9.060994,-0.161923,5.151347,-8.897875,52.522036,79.245158,78.021646,0.078125,stable,0.321181
4,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0013,7,1.461472,-0.054164,44.268477,91.342480,49.687171,-32.556083,-14.901660,0.812500,stable,0.897388

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-29_803496\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-30_803496/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-30_803496/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-30_803496/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-30_803496/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,image,2276,127.509519,144.769685,up,6.169076e-141,activated,1.850723e-140
1,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0001,image,2276,24.638196,6.322372,up,1.506774e-04,activated,4.520322e-04
2,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0002,image,2276,213.511197,238.515185,up,2.086079e-225,activated,6.258236e-225
3,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0003,image,2276,90.678339,95.101973,up,1.419521e-77,activated,4.258564e-77
4,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0004,image,2276,0.677146,-7.834420,none,6.098101e-01,no_change,6.098101e-01

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,2276,7,0.008780,0.003996,3.377251e-03,imk01333,173.423656,171.315554,50.311779,3.791163,False,0.008637,8.380587e-03
1,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0001,2276,7,0.011314,0.001998,3.791226e-03,imk01333,48.958751,51.435489,28.834645,9.358197,False,0.004868,8.912707e-03
2,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0002,2276,7,0.030109,0.000999,1.091178e-13,216066,328.210373,311.755688,110.888600,37.332404,False,0.002732,1.827723e-12
3,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0003,2276,7,0.011194,0.001998,1.811481e-04,216066,135.284276,132.635049,46.798185,12.740008,False,0.004868,8.091284e-04
4,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0006,2276,7,0.006405,0.026973,5.632466e-02,100075,29.064320,32.935081,26.701986,10.410738,False,0.042028,8.480342e-02

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,7,-0.690317,0.576670,192.313094,42.859174,203.326094,170.518740,81.486986,0.578125,stable,0.938578
1,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0001,7,-0.588725,0.094140,36.431198,31.126937,33.515092,10.417041,10.799150,0.296875,stable,0.765024
2,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0002,7,0.183249,-0.002984,204.726462,293.577044,253.792858,-39.784186,-59.049059,0.687500,stable,0.938578
3,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0003,7,-1.781960,0.179030,128.189111,77.513209,127.252728,53.714579,32.813302,0.218750,stable,0.697917
4,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0006,7,-2.002600,1.000000,9.572383,-78.366667,7.516847,85.883513,12.687416,0.078125,stable,0.697917

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-30_803496\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-31_803496/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-31_803496/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-31_803496/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-31_803496/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,image,2277,23.565567,32.576312,up,1.141687e-04,activated,3.425061e-04
1,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0001,image,2277,26.149843,34.717327,up,1.165898e-08,activated,3.497693e-08
2,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0002,image,2277,23.338449,26.390752,up,5.337258e-09,activated,1.601177e-08
3,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0003,image,2277,20.060566,28.285237,up,2.755198e-04,activated,4.132797e-04
4,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0004,image,2277,-0.367144,9.138489,none,7.001959e-01,no_change,1.000000e+00

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,2277,7,0.054361,0.000999,5.874587e-22,41006,220.203901,165.156175,162.598441,174.415416,True,0.001558,7.720886e-21
1,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0001,2277,7,0.016044,0.000999,3.196809e-07,216066,97.051511,88.543064,71.082471,47.450986,False,0.001558,7.541190e-07
2,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0002,2277,7,0.012518,0.000999,2.551070e-06,69022,66.606783,43.261825,21.765094,16.925087,False,0.001558,5.334055e-06
3,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0003,2277,7,0.003681,0.216783,2.066899e-01,216066,60.616723,47.414162,30.479462,14.431443,False,0.240290,2.237114e-01
4,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0005,2277,7,0.021524,0.000999,5.143283e-05,41006,278.348697,149.511881,91.396165,129.436598,False,0.001558,9.434442e-05

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,7,0.815785,-0.802123,8.899201,45.335585,60.613152,15.277568,-3.654153,0.9375,stable,1.000000
1,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0001,7,-0.159549,1.000000,55.534426,-58.153971,49.400097,53.430007,-81.968885,1.0000,stable,1.000000
2,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0002,7,-1.597147,0.338498,38.490661,-36.179051,29.470044,36.041174,46.480933,0.6875,stable,0.970779
3,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0003,7,0.584967,1.000000,46.051883,-34.142970,55.628374,60.783535,-59.560320,0.6875,stable,0.970779
4,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0005,7,-1.173257,-0.284174,140.177662,166.027505,224.925664,101.212222,-46.738343,0.9375,stable,1.000000

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-31_803496\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-08-01_803496/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-08-01_803496/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-08-01_803496/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-08-01_803496/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0000,image,2278,-38.241781,-54.493009,down,7.440372e-24,deactivated,2.232111e-23
1,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0001,image,2278,0.000000,0.434148,none,7.620824e-01,no_change,9.607628e-01
2,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0002,image,2278,0.000000,16.056385,none,4.831379e-02,no_change,1.449414e-01
3,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,image,2278,12.389700,27.979953,up,4.440151e-05,activated,1.332045e-04
4,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0004,image,2278,3.697176,30.047383,up,1.650438e-03,activated,4.951313e-03

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,2278,7,0.047062,0.000999,6.662141e-15,41006,219.858661,168.478659,168.478659,142.814581,False,0.001418,3.497624e-14
1,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0004,2278,7,0.014134,0.000999,7.647300e-04,216066,112.214604,59.377323,59.377323,56.483031,False,0.001418,1.163720e-03
2,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0005,2278,7,0.011643,0.000999,1.089091e-04,268048,55.330114,20.887655,15.346442,0.360037,False,0.001418,1.844429e-04
3,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0007,2278,7,0.162084,0.000999,6.197109e-66,100075,1477.383162,1144.001780,711.100471,334.630609,True,0.001418,2.168988e-64
4,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0008,2278,7,0.007799,0.001998,1.247833e-03,69022,72.682034,84.307432,62.622866,1.481721,False,0.002656,1.819757e-03

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,7,1.885122,0.146627,22.437601,90.387102,49.273978,-41.113125,-38.730493,0.468750,stable,0.734608
1,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0004,7,1.790692,0.498015,19.850325,-72.739579,60.748453,111.663668,-35.435900,0.937500,stable,0.955704
2,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0005,7,-1.381422,-0.492095,70.797605,44.287616,54.479868,-2.451615,52.043178,0.296875,stable,0.692708
3,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0007,7,-13.883889,-0.032062,735.202444,646.803394,925.975651,301.854073,286.456397,0.031250,stable,0.218750
4,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0008,7,-9.369963,0.996680,2.884955,-240.491638,5.048317,273.408514,188.544832,0.046875,stable,0.259046

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-08-01_803496\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-25_804730/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-25_804730/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-25_804730/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-25_804730/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0000,image,2278,0.000000,-7.901627,none,2.629127e-01,no_change,3.943690e-01
1,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0001,image,2278,0.000000,17.124573,none,3.812596e-01,no_change,6.134399e-01
2,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0002,image,2278,0.000000,-6.275322,none,2.296219e-01,no_change,2.314110e-01
3,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,image,2278,8.818317,39.478649,up,6.531216e-16,activated,1.959365e-15
4,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0004,image,2278,0.000000,-32.027310,none,3.010028e-03,no_change,9.030085e-03

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,2278,7,0.014201,0.000999,6.196481e-06,imk01057,73.104221,51.530046,49.554176,0.667871,False,0.001042,7.405550e-06
1,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0006,2278,7,0.029585,0.000999,2.953435e-08,imk01220,292.387655,126.575350,41.122997,36.795783,False,0.001042,3.710727e-08
2,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0008,2278,7,0.079282,0.000999,1.148891e-24,imk01378,339.691030,166.810474,166.810474,77.956470,True,0.001042,2.962930e-24
3,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0016,2278,7,0.009508,0.001998,2.247994e-04,imk01643,75.374273,39.279992,39.279992,21.797683,False,0.002040,2.343654e-04
4,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0017,2278,7,0.019013,0.000999,1.501762e-05,imk01220,162.662278,96.210850,78.079843,96.073920,False,0.001042,1.711310e-05

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,7,-2.243297,0.360982,84.155116,80.100201,75.081276,54.837244,-7.198989,0.015625,stable,0.076563
1,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0006,7,-11.230488,-0.042128,323.776169,325.265270,374.861621,-0.071609,172.359302,0.015625,stable,0.076563
2,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0008,7,1.025633,0.594350,40.966406,-62.995135,68.189383,112.246934,-95.279430,0.937500,stable,0.937500
3,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0016,7,-0.164023,0.717395,67.644218,13.721003,45.102968,27.387382,-0.913812,0.468750,stable,0.560213
4,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0017,7,-6.472795,0.047720,65.971801,42.403605,90.821800,-21.565923,126.065437,0.015625,stable,0.076563

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-25_804730\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-28_804730/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-28_804730/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-28_804730/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-28_804730/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0000,image,2278,0.000000,7.244737,none,1.759174e-05,no_change,5.277523e-05
1,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0001,image,2278,0.000000,6.355112,none,5.300946e-05,no_change,1.590284e-04
2,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0002,image,2278,0.000000,32.569209,none,5.009746e-14,no_change,1.502924e-13
3,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,image,2278,20.331811,88.113399,up,2.344941e-44,activated,7.034824e-44
4,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0004,image,2278,-33.126127,-142.333274,down,1.607856e-73,deactivated,4.823568e-73

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,2278,7,0.023865,0.000999,2.914694e-09,imk01097,134.965340,34.946954,17.172780,1.399822,False,0.001358,8.130462e-09
1,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0011,2278,7,0.012280,0.000999,1.923850e-05,imk01057,193.411175,88.196707,61.013653,4.262363,False,0.001358,3.289162e-05
2,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0013,2278,7,0.018702,0.000999,5.622348e-09,imk01643,126.560670,102.299349,82.199716,27.659776,False,0.001358,1.470172e-08
3,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0014,2278,7,0.191955,0.000999,7.218833e-56,imk01220,400.085908,340.140815,340.140815,291.605637,True,0.001358,3.825982e-54
4,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0021,2278,7,0.013191,0.000999,4.424289e-05,imk00459,77.873004,53.740558,48.623936,12.473484,False,0.001358,6.896686e-05

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,7,8.799201,-0.616665,48.373828,204.010226,58.042392,-145.967833,-71.023463,0.218750,stable,0.724609
1,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0011,7,-15.875127,1.000000,198.052471,-79.617988,220.045483,165.936166,257.070739,0.078125,stable,0.460069
2,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0013,7,-3.278542,0.543062,134.874710,39.939699,120.427517,38.695868,-31.643427,0.015625,stable,0.276042
3,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0014,7,-3.819342,1.000000,166.374099,-122.937325,166.539841,285.595794,47.719881,0.015625,stable,0.276042
4,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0021,7,-0.973030,0.251981,59.963907,28.970262,57.129518,38.339042,-12.221703,0.296875,stable,0.786719

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-28_804730\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-29_804730/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-29_804730/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-29_804730/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-29_804730/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0000,image,2277,0.0,57.240422,none,4.559096e-21,no_change,1.367729e-20
1,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0001,image,2277,0.0,29.540391,none,4.466963e-08,no_change,1.340089e-07
2,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0002,image,2277,0.0,159.978883,none,6.316040e-60,no_change,1.894812e-59
3,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0003,image,2277,0.0,40.803744,none,8.269002e-11,no_change,2.480701e-10
4,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0004,image,2277,0.0,5.404548,none,7.177088e-01,no_change,7.177088e-01

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0063,2277,7,0.065477,0.000999,1.051408e-30,imk01057,342.146211,291.064911,243.147378,30.803867,True,0.000999,2.102816e-30
1,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0000,2277,7,0.196880,0.000999,1.926526e-47,imk00895,212.675570,154.250560,154.250560,174.603494,True,0.000999,9.632631e-47
2,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0007,2277,7,0.050108,0.000999,1.601014e-14,imk01643,103.929928,36.400115,36.400115,50.473289,True,0.000999,2.287163e-14
3,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0012,2277,7,0.148403,0.000999,4.388983e-28,imk01097,196.951674,107.102500,107.102500,152.470760,True,0.000999,7.314972e-28
4,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0026,2277,7,0.020176,0.000999,4.353558e-07,imk01097,130.725919,57.660543,56.647026,42.328303,False,0.000999,4.837287e-07

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0063,7,0.043262,0.012545,476.217884,451.125548,470.564581,-65.622355,66.965468,0.687500,stable,0.859375
1,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0000,7,-1.817082,0.200633,48.029549,33.982578,81.529881,34.674182,24.493665,0.078125,stable,0.156250
2,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0007,7,-4.674878,1.000000,75.610254,-30.902067,77.854663,125.759695,41.340846,0.046875,stable,0.156250
3,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0012,7,-3.933829,0.016160,51.195902,105.554820,103.635978,-1.918842,-1.693995,0.109375,stable,0.156250
4,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0026,7,0.134057,-0.056869,101.062321,205.037374,119.082757,-82.571079,48.400284,0.937500,stable,0.937500

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-29_804730\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-30_804730/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-30_804730/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-30_804730/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-30_804730/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0000,image,2277,0.000000,6.422066,none,1.827399e-02,no_change,5.482198e-02
1,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,image,2277,10.273371,33.730969,up,6.038482e-30,activated,1.811545e-29
2,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0002,image,2277,0.000000,30.721095,none,2.220139e-11,no_change,6.660416e-11
3,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0003,image,2277,0.000000,-2.537169,none,3.998996e-01,no_change,5.998494e-01
4,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0004,image,2277,0.000000,20.373152,none,1.999523e-07,no_change,5.998570e-07

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,2277,7,0.019198,0.000999,7.103690e-11,100075,68.412930,55.471153,51.794096,19.897820,False,0.001467,2.384810e-10
1,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0005,2277,7,0.004513,0.103896,1.166349e-01,69022,95.841478,53.571439,33.408188,0.162988,False,0.110980,1.274847e-01
2,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0006,2277,7,0.005634,0.050949,4.823038e-02,69022,65.477700,42.537872,42.537872,6.701702,False,0.059865,5.812380e-02
3,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0007,2277,7,0.009333,0.001998,6.356761e-06,216066,197.968681,83.462623,35.721801,13.691606,False,0.002846,1.195071e-05
4,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0008,2277,7,0.014280,0.000999,1.039001e-04,216066,53.111818,20.159162,18.629885,0.586532,False,0.001467,1.627769e-04

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,7,-0.521734,-0.177768,61.196245,87.657741,39.953655,-70.030378,-4.740216,0.937500,stable,0.957880
1,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0005,7,-5.183297,-0.684646,83.421461,49.920784,88.343562,-26.401034,-39.868687,0.578125,stable,0.754774
2,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0006,7,-6.049668,-0.500469,85.750034,167.841565,118.706782,-104.911898,-3.410049,0.078125,stable,0.407986
3,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0007,7,2.045211,0.558146,118.347044,-99.421910,123.567462,207.225321,57.083014,0.109375,stable,0.428385
4,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0008,7,0.987364,0.601306,39.204789,-62.609775,27.614282,61.760697,33.174046,0.937500,stable,0.957880

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-30_804730\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-31_804730/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-31_804730/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-31_804730/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-31_804730/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,image,2277,32.281927,39.019688,up,2.391364e-16,activated,7.174091e-16
1,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0001,image,2277,14.068165,21.601726,up,8.413502e-06,activated,2.524051e-05
2,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0002,image,2277,35.612595,37.934304,up,1.766482e-22,activated,5.299445e-22
3,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0003,image,2277,31.344018,38.842228,up,1.274875e-15,activated,3.824624e-15
4,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0004,image,2277,28.887461,44.298491,up,5.643126e-12,activated,1.692938e-11

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,2277,7,0.023194,0.000999,2.128861e-08,216066,100.766014,84.637358,60.273653,41.576917,False,0.002145,1.032892e-07
1,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0001,2277,7,0.006062,0.024975,1.042674e-01,McGill_stairs,40.069525,25.330383,12.536893,4.834744,False,0.035562,1.264725e-01
2,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0002,2277,7,0.003362,0.267732,1.083408e-01,100075,55.529261,58.930823,28.017682,9.242150,False,0.299769,1.278617e-01
3,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0003,2277,7,0.003875,0.186813,2.287302e-01,41006,70.564876,52.192133,22.501934,28.360453,False,0.218505,2.517955e-01
4,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0004,2277,7,0.011310,0.000999,1.248002e-03,41006,79.782708,52.452598,28.286582,4.430219,False,0.002145,2.440123e-03

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,7,0.285409,0.090178,52.713597,-46.012189,25.140640,71.152829,-23.350843,0.6875,stable,0.950335
1,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0001,7,-1.106610,0.562578,15.777477,5.317550,14.939659,40.226392,-6.403741,0.9375,stable,0.990423
2,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0002,7,0.255915,-0.189406,34.948128,102.582363,29.514815,-89.300513,-12.850424,0.8125,stable,0.950335
3,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0003,7,0.675670,-0.278647,61.208940,120.025620,70.415303,-64.273934,-52.344618,0.6875,stable,0.950335
4,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0004,7,-3.998333,-0.554319,81.673802,39.412122,60.249282,34.496762,11.504015,0.3750,stable,0.767578

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-31_804730\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-08-01_804730/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-08-01_804730/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-08-01_804730/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-08-01_804730/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,image,2279,127.991999,143.141810,up,7.460263e-221,activated,2.238079e-220
1,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0001,image,2279,107.748085,131.300790,up,2.431556e-54,activated,7.294669e-54
2,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0002,image,2279,11.719513,27.881171,up,2.065679e-06,activated,6.197037e-06
3,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0003,image,2279,54.659018,65.242747,up,6.374178e-121,activated,1.912253e-120
4,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0004,image,2279,45.847445,54.102866,up,3.788065e-36,activated,1.136419e-35

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,2279,7,0.068782,0.000999,5.088048e-28,268048,205.317241,192.913605,73.759058,11.691388,True,0.001499,3.154590e-27
1,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0001,2279,7,0.040872,0.000999,3.024855e-20,268048,264.283320,252.709013,171.026438,96.234049,False,0.001499,1.339579e-19
2,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0002,2279,7,0.004148,0.144855,8.705683e-01,41006,59.257184,17.779415,6.514440,14.796726,False,0.151365,8.705683e-01
3,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0003,2279,7,0.011886,0.000999,6.596432e-04,69022,85.827669,74.334209,21.003105,7.911990,False,0.001499,9.294972e-04
4,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0004,2279,7,0.051636,0.000999,4.566871e-20,268048,143.455117,139.034569,106.345152,46.087307,True,0.001499,1.930541e-19

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,7,0.382230,0.401391,129.530195,91.542389,157.731210,51.947398,60.122922,0.578125,stable,0.875856
1,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0001,7,1.227777,0.084382,166.421278,134.530541,127.919180,-6.611361,-49.309027,0.687500,stable,0.875856
2,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0002,7,-0.152408,0.084030,38.024087,-6.678418,42.265878,48.944296,82.492605,0.687500,stable,0.875856
3,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0003,7,-1.193346,0.902737,82.210087,5.032261,81.069843,104.115607,41.177314,0.375000,stable,0.875856
4,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0004,7,-2.955819,-0.145320,52.794645,71.270373,76.725986,4.504643,25.866996,0.578125,stable,0.875856

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-08-01_804730\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-25_804733/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-25_804733/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-25_804733/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-25_804733/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0000,image,2277,20.546762,22.869892,none,1.697016e-02,no_change,5.091047e-02
1,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,image,2277,47.429487,43.108061,up,4.431872e-06,activated,1.329562e-05
2,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0002,image,2277,16.822427,14.971332,up,2.404219e-03,activated,7.212656e-03
3,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0003,image,2277,-135.314813,-165.028672,down,1.847468e-57,deactivated,5.542405e-57
4,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0004,image,2277,-33.990210,-42.270624,down,1.525773e-09,deactivated,4.577319e-09

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,2277,7,0.008735,0.001998,1.406698e-03,imk01220,124.640785,140.110263,99.101810,40.174272,False,0.002331,1.641147e-03
1,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0002,2277,7,0.005007,0.065934,2.668325e-02,imk01220,74.701246,45.406973,31.085389,59.073394,False,0.069767,2.890685e-02
2,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0008,2277,7,0.020572,0.000999,2.606174e-07,imk01220,102.029569,72.623628,49.384459,69.980103,False,0.001181,3.705653e-07
3,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0009,2277,7,0.036894,0.000999,1.173693e-10,imk00459,144.025604,71.738968,41.797240,34.446205,False,0.001181,2.053962e-10
4,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0010,2277,7,0.053342,0.000999,2.826609e-25,imk01057,282.865802,271.063797,98.710972,17.363944,True,0.001181,1.169188e-24

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,7,-8.610677,-0.534128,37.531135,-36.046621,100.518816,208.425285,29.917550,0.156250,stable,0.546875
1,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0002,7,0.680843,-0.546075,33.263395,106.423531,34.258525,-190.134256,-39.969481,0.687500,stable,0.906703
2,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0008,7,-3.246741,-0.126931,37.236907,83.554443,43.885541,-18.571127,25.432598,0.078125,stable,0.338542
3,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0009,7,-2.089631,-0.284399,42.266917,126.215032,76.721922,-107.035610,4.971774,0.109375,stable,0.398125
4,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0010,7,-7.573878,0.219777,271.981464,120.849478,227.178027,87.153228,76.516797,0.031250,stable,0.304688

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-25_804733\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-28_804733/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-28_804733/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-28_804733/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-28_804733/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0000,image,2277,0.000000,4.039210,none,8.541730e-01,no_change,8.541730e-01
1,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0001,image,2277,0.000000,6.760873,none,8.805787e-01,no_change,9.948598e-01
2,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0002,image,2277,-58.420841,-75.900247,down,5.840377e-91,deactivated,1.752113e-90
3,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,image,2277,4.476792,20.404038,up,8.404823e-07,activated,2.521447e-06
4,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0004,image,2277,-9.911611,-40.012227,down,3.590991e-08,deactivated,1.077297e-07

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,2277,7,0.007234,0.011988,3.228628e-03,imk01057,51.787917,44.193077,44.110498,23.776854,False,0.012787,3.443870e-03
1,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0007,2277,7,0.039020,0.000999,2.605757e-13,imk00895,152.898893,96.517796,96.517796,116.910988,False,0.001102,7.580384e-13
2,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0008,2277,7,0.107040,0.000999,8.407704e-44,imk01057,268.440722,238.246199,194.589518,123.844718,True,0.001102,5.380931e-43
3,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0009,2277,7,0.071963,0.000999,1.967710e-28,imk01057,191.469760,174.078936,129.512029,53.452074,True,0.001102,8.995244e-28
4,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0010,2277,7,0.112574,0.000999,2.428729e-53,imk01220,267.308382,242.001813,117.455596,32.470967,True,0.001102,3.885966e-52

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,7,-0.058043,0.584399,35.343815,-23.101104,25.680234,32.010192,-16.250860,0.937500,stable,0.967742
1,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0007,7,-2.946542,0.978430,30.972733,-11.738101,2.655011,76.089774,12.231602,0.812500,stable,0.962963
2,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0008,7,-5.309834,1.000000,90.095838,-84.379917,129.647153,217.039496,83.137482,0.015625,stable,0.500000
3,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0009,7,-2.817635,0.922130,115.849260,3.523720,117.633996,118.988709,26.319289,0.078125,stable,0.500000
4,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0010,7,-2.158549,-0.150109,176.146736,254.618035,225.581972,-29.036063,29.725779,0.031250,stable,0.500000

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-28_804733\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-29_804733/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-29_804733/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-29_804733/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-29_804733/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0000,image,2278,0.000000,2.249527,none,7.604218e-03,no_change,2.281265e-02
1,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,image,2278,13.124292,18.090690,up,9.906999e-08,activated,2.972100e-07
2,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0002,image,2278,36.516792,58.672103,up,2.148264e-30,activated,6.444791e-30
3,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0003,image,2278,0.000000,-0.113329,none,3.543158e-01,no_change,5.314737e-01
4,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0004,image,2278,0.000000,23.472453,none,6.004972e-04,no_change,1.801492e-03

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,2278,7,0.009349,0.001998,5.577653e-07,imk01057,62.285253,46.429870,38.427462,7.015856,False,0.002449,9.634128e-07
1,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0002,2278,7,0.088628,0.000999,6.447721e-37,imk00459,194.474650,183.895027,166.221539,72.788243,True,0.001245,6.125335e-36
2,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0010,2278,7,0.037343,0.000999,2.936210e-17,imk00459,366.935420,286.261814,251.624426,207.628715,False,0.001245,1.174484e-16
3,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0012,2278,7,0.039244,0.000999,2.918693e-15,imk01097,225.774756,164.492750,124.015017,74.233856,False,0.001245,1.008276e-14
4,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0013,2278,7,0.169071,0.000999,1.140380e-59,imk00895,680.318918,593.988847,593.988847,536.953403,True,0.001245,2.888963e-58

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,7,3.141759,-0.229095,23.876944,81.543783,17.788507,-78.186476,-58.954739,0.078125,stable,0.494792
1,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0002,7,-1.385266,0.453218,40.719949,-29.442686,66.447097,95.889783,24.123766,0.578125,stable,0.896684
2,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0010,7,-6.569276,0.070244,234.391656,164.537773,179.423476,-26.253077,-199.833377,0.468750,stable,0.896684
3,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0012,7,-6.266271,1.000000,181.658991,-107.726362,183.210537,288.133583,142.408728,0.218750,stable,0.593750
4,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0013,7,-5.112298,0.838893,29.221528,-33.237934,200.791539,375.189349,17.315518,0.109375,stable,0.554167

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-29_804733\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-30_804733/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-30_804733/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-30_804733/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-30_804733/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0000,image,2278,-12.894695,-19.108900,down,1.286560e-03,deactivated,1.929840e-03
1,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0001,image,2278,8.697711,14.686569,none,5.755059e-02,no_change,1.726518e-01
2,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0002,image,2278,5.281195,-5.088143,none,7.220957e-01,no_change,7.220957e-01
3,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0003,image,2278,-0.491887,-0.919548,none,7.008794e-01,no_change,7.008794e-01
4,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,image,2278,46.782947,53.701373,up,3.747473e-18,activated,1.124242e-17

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,2278,7,0.004703,0.106893,1.770781e-03,McGill_stairs,97.656534,110.422753,70.919136,36.444193,False,0.126079,3.194350e-03
1,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0005,2278,7,0.010699,0.001998,4.596665e-06,69022,155.106081,149.469038,59.801988,12.492552,False,0.003468,1.174703e-05
2,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0006,2278,7,0.034675,0.000999,4.833375e-14,69022,152.883138,145.620190,76.674044,15.249740,False,0.001838,2.021229e-13
3,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0007,2278,7,0.144748,0.000999,5.934659e-68,216066,313.437696,287.188669,154.005607,56.841481,True,0.001838,1.364972e-66
4,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0008,2278,7,0.012178,0.000999,1.544404e-05,216066,84.478302,71.381797,30.361011,0.173147,False,0.001838,3.552129e-05

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,7,-3.188160,1.000000,54.416100,-41.976935,51.270392,72.805702,-21.176582,0.578125,stable,0.857863
1,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0005,7,-7.718226,-0.167403,121.976415,199.589967,128.787225,-159.061323,88.337268,0.218750,stable,0.559028
2,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0006,7,-0.613840,-0.249363,126.834603,221.717614,97.060832,-79.549807,112.502702,0.468750,stable,0.770089
3,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0007,7,3.803966,-0.422177,164.790852,410.047941,174.549706,-264.215217,-127.925544,0.687500,stable,0.866438
4,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0008,7,-1.759931,-0.653200,10.909070,195.482765,68.995500,-94.456611,-27.265384,0.937500,stable,0.947802

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-30_804733\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-31_804733/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-31_804733/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-31_804733/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-31_804733/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,image,2278,23.088219,29.579810,up,2.007564e-07,activated,6.022692e-07
1,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0001,image,2278,512.777884,611.080875,up,2.350093e-238,activated,7.050279e-238
2,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0002,image,2278,6.232298,11.036412,up,1.044723e-03,activated,3.134168e-03
3,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0003,image,2278,18.511344,24.390533,up,1.712411e-06,activated,5.137232e-06
4,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0004,image,2278,-15.537744,-22.219449,down,1.929338e-04,deactivated,5.788015e-04

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,2278,7,0.003697,0.191808,5.444174e-01,268048,49.343737,24.163983,2.157102,3.466333,False,0.258621,5.988591e-01
1,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0001,2278,7,0.141826,0.000999,3.136267e-64,imk01306,1040.905917,1003.667801,551.244237,191.197918,True,0.002564,2.414925e-62
2,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0002,2278,7,0.003748,0.201798,1.794883e-01,imk01333,24.178418,12.633852,7.077495,1.454741,False,0.263364,2.265672e-01
3,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0003,2278,7,0.003382,0.235764,1.688901e-01,69022,41.776228,25.706400,8.787132,4.006856,False,0.297604,2.167423e-01
4,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0008,2278,7,0.001677,0.742258,3.297996e-01,268048,51.519840,23.006245,18.902272,10.932661,False,0.793803,3.906857e-01

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,7,1.960854,1.000000,17.028593,-7.042075,32.389528,12.190895,61.969184,0.15625,stable,0.701823
1,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0001,7,-23.202807,0.906924,679.068478,33.145043,687.254318,594.606140,535.417413,0.03125,stable,0.501302
2,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0002,7,-0.138978,-0.615604,2.053010,9.389144,5.832778,12.646559,-53.860581,0.81250,stable,0.962500
3,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0003,7,-0.475819,-0.759763,34.023056,34.295752,38.437386,-38.681928,-130.071862,0.93750,stable,1.000000
4,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0008,7,-0.289072,-0.322136,52.276483,83.692146,49.470003,-50.029589,-30.954733,0.93750,stable,1.000000

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-31_804733\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-08-01_804733/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-08-01_804733/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-08-01_804733/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-08-01_804733/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0000,image,2277,0.000000,34.039712,none,1.971864e-13,no_change,5.915591e-13
1,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,image,2277,54.673802,128.329756,up,3.344848e-53,activated,1.003454e-52
2,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0002,image,2277,0.000000,-11.360168,none,1.242669e-03,no_change,3.728007e-03
3,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0003,image,2277,1.696254,36.680358,up,2.143996e-26,activated,6.431988e-26
4,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0004,image,2277,0.000000,33.547074,none,2.249812e-14,no_change,6.749436e-14

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,2277,7,0.006854,0.017982,1.152593e-03,McGill_stairs,198.165901,176.838921,146.797360,55.767047,False,0.028257,1.811218e-03
1,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0003,2277,7,0.002699,0.409590,1.789059e-01,41006,50.981728,16.056483,16.056483,8.767429,False,0.409590,2.459956e-01
2,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0008,2277,7,0.054725,0.000999,3.852692e-23,41006,277.107736,262.287098,129.857425,31.984371,True,0.002198,1.059490e-22
3,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0009,2277,7,0.097609,0.000999,1.099475e-39,imk01306,672.788818,619.246242,313.337124,79.523230,True,0.002198,1.209422e-38
4,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0020,2277,7,0.010962,0.001998,2.599321e-04,imk01306,140.772802,88.692952,42.806793,10.733340,False,0.003663,4.765421e-04

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,7,-6.207003,0.042187,227.158575,194.613180,207.409396,59.748113,104.774350,0.218750,stable,0.481250
1,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0003,7,-1.276499,0.435958,66.558024,14.599000,43.004691,12.879450,-13.690076,0.812500,stable,0.893750
2,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0008,7,-5.259910,-0.040227,242.016984,275.707052,280.785384,-19.962248,-5.184296,0.015625,stable,0.085938
3,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0009,7,-6.906388,0.344027,573.358172,275.395055,588.179007,312.783952,169.082037,0.015625,stable,0.085938
4,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0020,7,-2.205339,-0.037857,140.589850,202.074591,109.727339,5.003235,60.432539,0.375000,stable,0.687500

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-08-01_804733\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-25_810196/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-25_810196/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-25_810196/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-25_810196/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0000,image,2278,42.215522,82.923058,up,9.092869e-38,activated,2.727861e-37
1,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0001,image,2278,-143.323561,-175.130531,down,9.381453e-105,deactivated,2.814436e-104
2,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0002,image,2278,618.013797,579.396046,up,0.000000e+00,activated,0.000000e+00
3,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0003,image,2278,159.173721,185.524252,up,2.887975e-120,activated,8.663924e-120
4,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0004,image,2278,257.719550,287.101434,up,6.007969e-169,activated,1.802391e-168

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0000,2278,7,0.062049,0.000999,1.490331e-21,imk00895,217.545330,151.077273,119.828255,95.476964,True,0.001068,2.750015e-21
1,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0002,2278,7,0.301884,0.000999,6.774998e-124,imk01057,761.945014,803.844153,216.057262,4.969604,True,0.001068,9.546588e-123
2,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0003,2278,7,0.077230,0.000999,3.754771e-31,imk01220,349.256402,304.660638,161.318053,43.225518,True,0.001068,8.818023e-31
3,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0004,2278,7,0.033672,0.000999,4.445631e-14,imk01220,413.273219,377.785833,138.190572,81.081655,False,0.001068,6.690027e-14
4,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0005,2278,7,0.047138,0.000999,3.715514e-18,imk00895,283.633832,274.706231,102.331628,38.535531,False,0.001068,6.259834e-18

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0000,7,-3.212203,1.000000,79.340039,-53.046068,82.240759,118.029988,-23.686966,0.109375,stable,0.199449
1,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0002,7,-7.108321,-0.014453,687.591576,566.533374,613.648141,47.114767,-109.796088,0.109375,stable,0.199449
2,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0003,7,-4.327295,0.178150,209.411190,222.369074,204.053903,18.590025,37.193293,0.375000,stable,0.501078
3,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0004,7,-9.566838,0.697357,395.447883,97.138856,401.223812,317.715579,139.395463,0.031250,stable,0.105299
4,810196_2025-07-25_16-24-20,810196,DMD1,DMD1_syn0005,7,-9.136992,0.668089,281.025689,43.542265,256.407169,190.008442,292.208675,0.015625,stable,0.069196

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-25_810196\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-28_810196/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-28_810196/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-28_810196/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-28_810196/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0000,image,2278,2488.674000,2772.646919,up,6.575104e-145,activated,1.972531e-144
1,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0001,image,2278,2523.566019,2169.402407,up,6.791938e-17,activated,2.037581e-16
2,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0002,image,2278,282.523846,-238.331453,none,4.725074e-01,no_change,4.725074e-01
3,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0003,image,2278,1308.481839,1600.802588,up,2.096203e-31,activated,6.288608e-31
4,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0004,image,2278,555.045252,1977.783364,up,6.745117e-10,activated,2.023535e-09

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0000,2278,7,0.062031,0.000999,1.160161e-47,imk01643,5247.555595,4714.985885,2566.59426,989.047575,True,0.001104,4.592306e-47
1,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0001,2278,7,0.131271,0.000999,2.015802e-50,imk00895,14740.065806,13096.386200,11870.86592,10847.564826,True,0.001104,8.326139e-50
2,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0003,2278,7,0.085131,0.000999,6.047080e-29,imk01643,5606.842296,4720.952958,3894.46996,4056.437784,True,0.001104,1.335983e-28
3,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0004,2278,7,0.084070,0.000999,3.042792e-21,imk01057,7488.597991,1611.194096,1198.68353,1920.384253,True,0.001104,5.667947e-21
4,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0005,2278,7,0.061073,0.000999,1.077926e-22,imk00895,5134.653394,3403.880381,2852.67378,2133.781736,True,0.001104,2.133394e-22

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0000,7,-143.787215,0.952179,3866.683767,38.526398,3613.901450,3719.924535,2190.824967,0.031250,stable,0.185547
1,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0001,7,-104.949799,1.000000,2363.125566,-178.938048,4329.998173,5946.571031,2562.663132,0.468750,stable,0.618490
2,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0003,7,-82.079058,-0.019996,2939.804676,3131.950642,3220.114762,288.844152,-318.996038,0.109375,stable,0.346354
3,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0004,7,-48.002957,1.000000,986.375999,-1667.974355,2639.585761,5627.224793,2839.398010,0.156250,stable,0.362043
4,810196_2025-07-28_19-59-05,810196,DMD1,DMD1_syn0005,7,-68.337780,-0.037733,879.281607,3511.380791,2438.718327,-1653.556439,-1953.267537,0.375000,stable,0.574597

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-28_810196\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-29_810196/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-29_810196/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-29_810196/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-29_810196/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0000,image,2277,0.000000,-0.783501,none,7.420389e-01,no_change,0.758312
1,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0001,image,2277,0.000000,-0.284702,none,6.356651e-01,no_change,0.635665
2,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0002,image,2277,0.000000,3.100269,none,9.212732e-01,no_change,0.921273
3,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0003,image,2277,0.000000,0.344902,none,7.771235e-01,no_change,0.777124
4,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0004,image,2277,41.736898,46.381139,up,7.213545e-07,activated,0.000002

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0004,2277,7,0.004448,0.114885,2.753428e-03,imk01378,101.137621,123.401227,95.747296,16.471148,False,0.129246,3.304113e-03
1,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0006,2277,7,0.002868,0.342657,4.191989e-01,imk01057,38.278158,15.576466,15.576466,21.163219,False,0.362814,4.438576e-01
2,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0013,2277,7,0.009286,0.003996,1.914269e-04,imk01220,56.510086,33.473679,32.829026,21.082603,False,0.005138,2.650526e-04
3,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0014,2277,7,0.033739,0.000999,2.279073e-12,imk01057,91.708061,41.214385,41.214385,47.832802,False,0.001383,5.860473e-12
4,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0026,2277,7,0.001647,0.732268,7.183481e-01,imk01220,16.192378,0.000000,-3.162441,8.700251,False,0.732268,7.183481e-01

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0004,7,1.598429,0.943002,12.517564,-222.952519,12.580211,306.855501,117.827973,1.000000,stable,1.000000
1,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0006,7,0.950343,1.000000,14.881198,-31.069327,20.924560,75.740237,23.280752,1.000000,stable,1.000000
2,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0013,7,0.249613,-0.149702,39.566312,58.386887,25.554629,-20.283895,-55.245082,0.578125,stable,0.800481
3,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0014,7,-4.589146,0.887332,29.715580,-32.898275,40.033725,80.159115,79.314163,0.109375,stable,0.312500
4,810196_2025-07-29_17-02-41,810196,DMD1,DMD1_syn0026,7,-1.506932,1.000000,10.433658,-49.436187,10.311453,68.110381,38.928358,0.015625,stable,0.070312

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-29_810196\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-30_810196/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-30_810196/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-30_810196/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-30_810196/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0000,image,2277,220.095692,325.879621,up,4.372474e-215,activated,1.311742e-214
1,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0001,image,2277,419.065861,447.597804,up,1.441346e-195,activated,4.324039e-195
2,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0002,image,2277,144.145018,162.998273,up,3.253605e-256,activated,9.760816e-256
3,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0003,image,2277,176.405210,196.362254,up,1.615025e-165,activated,4.845074e-165
4,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0004,image,2277,248.948800,268.220027,up,1.203711e-296,activated,3.611132e-296

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0000,2277,7,0.159382,0.000999,6.624842e-55,McGill_stairs,734.376423,539.712424,343.246807,202.188088,True,0.00126,1.358093e-53
1,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0001,2277,7,0.040229,0.000999,9.385053e-17,McGill_stairs,614.696108,590.064357,194.971926,16.056209,False,0.00126,2.332044e-16
2,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0002,2277,7,0.057693,0.000999,1.183978e-30,268048,252.711525,233.722393,103.856321,75.148077,True,0.00126,6.472414e-30
3,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0003,2277,7,0.032275,0.000999,1.091740e-14,268048,298.400912,252.266887,87.453135,78.824291,False,0.00126,2.633020e-14
4,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0004,2277,7,0.087451,0.000999,9.668379e-40,100075,382.824148,369.527012,140.924317,21.606893,True,0.00126,8.808967e-39

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0000,7,-10.353972,0.450115,356.897055,135.335787,446.799128,243.507083,-11.612734,0.015625,stable,0.075368
1,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0001,7,-24.424595,0.357332,735.818281,306.447618,593.488555,341.477955,198.637872,0.015625,stable,0.075368
2,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0002,7,-5.582067,0.544757,242.299166,75.747330,224.999200,201.503533,60.053447,0.031250,stable,0.075368
3,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0003,7,-4.504755,0.438985,270.667595,79.252399,280.226900,217.572659,74.212004,0.031250,stable,0.075368
4,810196_2025-07-31_08-28-08,810196,DMD1,DMD1_syn0004,7,-10.622870,0.015442,296.833121,296.577511,329.131235,37.229712,87.712807,0.015625,stable,0.075368

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-30_810196\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-31_810196/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-31_810196/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-31_810196/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-31_810196/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0000,image,2278,62.177436,91.408043,up,7.028026e-57,activated,2.108408e-56
1,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0001,image,2278,81.107154,83.005556,up,4.330653e-24,activated,1.299196e-23
2,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0002,image,2278,46.700537,62.402887,up,2.424308e-27,activated,7.272924e-27
3,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0003,image,2278,14.188843,23.275866,up,2.502424e-03,activated,7.507271e-03
4,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0004,image,2278,53.786590,43.465536,up,3.149346e-12,activated,9.448038e-12

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0000,2278,7,0.024987,0.000999,3.808549e-08,69022,156.694120,119.846731,64.995640,13.076295,False,0.001155,5.376776e-08
1,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0001,2278,7,0.022689,0.000999,1.407602e-12,imk01306,191.739402,196.941329,131.795409,48.537194,False,0.001155,2.329823e-12
2,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0002,2278,7,0.032183,0.000999,4.747538e-13,imk01306,165.386682,111.188876,73.956644,66.371102,False,0.001155,8.286612e-13
3,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0003,2278,7,0.019655,0.000999,1.939447e-05,100075,123.540659,84.556629,77.845146,68.666204,False,0.001155,2.418012e-05
4,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0004,2278,7,0.083831,0.000999,1.729151e-33,imk01306,264.675194,122.722220,84.230884,12.348670,True,0.001155,5.928516e-33

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0000,7,0.814416,0.180770,79.763674,112.500392,93.786765,-18.713627,-91.785219,0.375000,stable,0.500000
1,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0001,7,-0.870447,0.648460,88.827970,40.888842,131.352332,125.619693,310.613274,0.468750,stable,0.569620
2,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0002,7,-4.126464,0.870458,117.915787,22.536838,162.318898,156.089509,33.153232,0.078125,stable,0.178571
3,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0003,7,-7.800350,1.000000,87.642569,-230.625834,102.402557,382.222375,192.758107,0.015625,stable,0.107143
4,810196_2025-07-31_14-19-46,810196,DMD1,DMD1_syn0004,7,-4.247915,0.093290,-31.297983,-75.299272,139.703198,255.771200,136.260200,0.015625,stable,0.107143

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-31_810196\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-08-01_810196/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-08-01_810196/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-08-01_810196/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-08-01_810196/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0000,image,2277,60.938570,72.498211,up,1.634859e-15,activated,4.904576e-15
1,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0001,image,2277,24.606149,30.416522,up,9.216990e-09,activated,2.765097e-08
2,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0002,image,2277,85.493193,128.688004,up,5.430599e-75,activated,1.629180e-74
3,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0003,image,2277,20.488038,28.150694,up,9.956887e-07,activated,2.987066e-06
4,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0004,image,2277,-59.442278,-108.502484,down,3.292836e-17,deactivated,9.878508e-17

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0000,2277,7,0.074749,0.000999,9.809144e-36,100075,254.599856,231.258633,191.226492,50.044358,True,0.001474,7.234244e-35
1,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0001,2277,7,0.013308,0.000999,3.001287e-03,41006,93.432151,56.781630,36.696687,53.205466,False,0.001474,4.118046e-03
2,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0002,2277,7,0.337198,0.000999,1.016588e-98,268048,573.737211,533.442474,481.598392,487.188766,True,0.001474,5.997872e-97
3,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0003,2277,7,0.205789,0.000999,2.726149e-77,268048,298.607032,266.158263,275.625869,253.830964,True,0.001474,8.042139e-76
4,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0006,2277,7,0.001211,0.843157,4.745676e-01,100075,16.550370,15.090727,3.253091,2.326979,False,0.843157,4.745676e-01

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0000,7,0.555877,0.344661,38.844096,48.977360,90.980184,153.466839,117.377920,0.687500,stable,0.921875
1,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0001,7,1.216832,0.254710,69.738121,-33.059490,30.472337,78.337959,138.319868,0.812500,stable,0.921875
2,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0002,7,0.462964,1.000000,62.618326,-6.320315,98.535337,204.896702,55.526847,1.000000,stable,1.000000
3,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0003,7,-2.049837,0.069501,4.885800,-27.317094,47.833859,47.081061,9.942451,0.109375,stable,0.460938
4,810196_2025-08-01_16-37-27,810196,DMD1,DMD1_syn0006,7,-0.248616,-0.530817,16.272770,84.427679,22.576649,-60.543937,-11.319829,0.578125,stable,0.921875

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-08-01_810196\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-10-29_809047/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-10-29_809047/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-10-29_809047/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-10-29_809047/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0000,image,2285,87.324767,175.807221,none,1.994229e-02,no_change,5.982687e-02
1,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0001,image,2285,-12.178469,169.506503,none,6.902559e-01,no_change,6.902559e-01
2,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0002,image,2285,564.149517,617.815765,up,1.762159e-16,activated,5.286477e-16
3,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0003,image,2285,-160.467595,-216.918594,none,1.472846e-01,no_change,2.209269e-01
4,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0004,image,2285,191.209406,218.912965,up,5.292017e-04,activated,1.587605e-03

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0002,2285,7,0.049502,0.000999,3.558067e-20,imk01097,1862.334681,1511.176888,1230.536604,317.891327,False,0.001343,1.387646e-19
1,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0004,2285,7,0.002785,0.391608,1.928493e-01,imk01097,495.653998,594.652307,481.476138,159.073531,False,0.412776,2.089201e-01
2,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0006,2285,7,0.007420,0.004995,2.134380e-02,imk00895,879.009459,459.380692,109.907946,106.025472,False,0.006284,2.601276e-02
3,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0008,2285,7,0.150046,0.000999,2.604845e-54,imk01378,13339.312883,12127.582129,11379.620017,6660.020362,True,0.001343,2.031779e-53
4,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0009,2285,7,0.006314,0.019980,3.508499e-02,imk01097,307.757472,400.673168,325.363152,64.788078,False,0.022918,4.024455e-02

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0002,7,-29.448823,1.000000,799.993233,-898.123846,857.524615,1755.648462,2199.419887,0.109375,stable,0.533203
1,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0004,7,-14.288562,-0.396985,441.985988,1023.934014,296.853276,-911.474002,-14.877242,0.218750,stable,0.533203
2,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0006,7,8.513124,1.000000,599.473927,-35.302484,685.811103,669.626528,-165.045968,0.812500,stable,0.937500
3,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0008,7,-6.308210,0.252325,1602.875712,956.964994,5318.717034,4958.722249,3290.870646,0.812500,stable,0.937500
4,809047_2025-10-29_10-16-32,809047,DMD1,DMD1_syn0009,7,-7.270404,1.000000,132.438902,-374.344296,180.972875,555.317171,98.585124,0.218750,stable,0.533203

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-29_809047\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-10-30_809047/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-10-30_809047/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-10-30_809047/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-10-30_809047/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0000,image,2279,24.117967,-166.861765,none,5.440051e-01,no_change,5.440051e-01
1,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0001,image,2279,100.490490,-28.775081,none,9.785934e-01,no_change,1.000000e+00
2,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0002,image,2279,-27.664003,60.372018,none,6.183004e-01,no_change,9.274505e-01
3,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0003,image,2279,1086.637889,989.975736,up,2.942360e-11,activated,8.827079e-11
4,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0004,image,2279,71.075472,88.677519,none,6.004525e-02,no_change,9.006788e-02

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0003,2279,7,0.010184,0.001998,3.403187e-03,imk00895,2374.135058,2236.184065,1288.104952,1080.480806,False,0.002725,4.640709e-03
1,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0014,2279,7,0.004099,0.164835,1.802267e-01,imk01643,1272.382835,1112.104254,633.205055,143.031579,False,0.190194,2.252834e-01
2,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0017,2279,7,0.053099,0.000999,2.012741e-25,imk00942,3686.895672,3748.982269,3015.927990,91.258279,True,0.001499,6.038222e-25
3,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0020,2279,7,0.079191,0.000999,1.921003e-29,imk00942,3525.499984,3018.820161,3060.877040,2989.652149,True,0.001499,7.203762e-29
4,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0028,2279,7,0.087398,0.000999,2.615780e-23,imk00942,13178.462649,5372.142217,4534.969466,6983.770734,True,0.001499,5.075972e-23

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0003,7,33.769483,1.000000,1168.598219,-552.629505,1236.004534,189.413317,246.877247,0.015625,stable,0.234375
1,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0014,7,-7.834477,-0.637357,535.723716,3322.507158,98.426241,-3442.635373,-180.482152,0.578125,stable,0.722656
2,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0017,7,3.344949,0.660803,355.657423,-2784.652992,1092.975834,1386.125493,-692.147049,0.218750,stable,0.546875
3,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0020,7,12.233345,1.000000,445.748614,-1461.337803,762.589598,1994.106099,211.602822,0.937500,stable,0.937500
4,809047_2025-10-30_10-06-43,809047,DMD1,DMD1_syn0028,7,-81.618751,-0.385170,2808.116998,8914.518791,5352.540721,-4910.107116,-2925.161773,0.156250,stable,0.546875

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-30_809047\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-10-31_809047/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-10-31_809047/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-10-31_809047/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-10-31_809047/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0000,image,2278,275.958487,196.651203,none,7.717666e-02,no_change,1.157650e-01
1,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0001,image,2278,-370.638650,-196.557318,none,1.354843e-01,no_change,2.032265e-01
2,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0002,image,2278,707.782364,490.350439,up,2.649293e-08,activated,7.947879e-08
3,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0003,image,2278,-116.466270,-305.836933,none,1.933294e-01,no_change,2.899941e-01
4,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0004,image,2278,-1104.401066,-1199.886988,down,3.920658e-10,deactivated,1.176197e-09

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0002,2278,7,0.014035,0.000999,6.504785e-05,imk01057,2100.638447,1689.906928,1104.550700,867.779856,False,0.001118,7.868691e-05
1,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0008,2278,7,0.030947,0.000999,6.627916e-13,imk01097,2660.173450,2575.063293,2152.024870,40.266294,False,0.001118,1.242734e-12
2,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0010,2278,7,0.030040,0.000999,3.573131e-13,imk01378,10322.497837,9878.911053,2599.558297,218.606811,False,0.001118,6.936171e-13
3,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0012,2278,7,0.079776,0.000999,2.384190e-26,imk00895,8469.866505,6942.130838,5046.416548,4186.259563,True,0.001118,7.774534e-26
4,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0013,2278,7,0.048764,0.000999,5.614493e-20,imk01643,9326.007783,9327.176487,7935.636323,284.760201,False,0.001118,1.452024e-19

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0002,7,63.373075,0.280062,1513.379400,94.794905,734.750546,3361.382596,1416.129465,0.296875,stable,0.742188
1,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0008,7,18.739312,-0.025995,943.085453,539.783373,1881.652421,185.593422,-4287.333860,0.578125,stable,0.937500
2,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0010,7,-16.679906,0.277736,12396.402266,9256.326421,10159.754056,6940.881308,12837.903342,0.468750,stable,0.837054
3,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0012,7,18.506166,-0.525380,2599.451631,5816.014648,2697.599504,-3912.912456,-1616.478426,0.375000,stable,0.803571
4,809047_2025-10-31_12-00-50,809047,DMD1,DMD1_syn0013,7,-57.936544,0.660378,8066.611758,3075.176548,7240.656207,3830.272615,-5507.118448,0.687500,stable,0.937500

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-31_809047\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-11-01_809047/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-11-01_809047/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-11-01_809047/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-11-01_809047/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,809047_2025-11-01_17-51-59,809047,DMD1,DMD1_syn0000,image,2278,0.0,2638.289371,none,2.703698e-49,no_change,8.111095e-49
1,809047_2025-11-01_17-51-59,809047,DMD1,DMD1_syn0001,image,2278,0.0,2136.732126,none,6.437882e-77,no_change,1.931365e-76
2,809047_2025-11-01_17-51-59,809047,DMD1,DMD1_syn0002,image,2278,0.0,977.426421,none,5.686600e-19,no_change,1.705980e-18
3,809047_2025-11-01_17-51-59,809047,DMD1,DMD1_syn0003,image,2278,0.0,432.121293,none,9.845330e-07,no_change,2.953599e-06
4,809047_2025-11-01_17-51-59,809047,DMD1,DMD1_syn0004,image,2278,0.0,1092.768755,none,7.796025e-32,no_change,2.338807e-31

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,809047_2025-11-01_17-51-59,809047,DMD2,DMD2_syn0001,2278,7,0.069748,0.000999,1.956345e-29,268048,3363.434804,2642.295015,1586.276772,100.147574,True,0.000999,4.890862e-29
1,809047_2025-11-01_17-51-59,809047,DMD2,DMD2_syn0009,2278,7,0.102954,0.000999,2.678532e-38,imk01306,3862.561296,2799.112336,2088.201698,945.023358,True,0.000999,1.004450e-37
2,809047_2025-11-01_17-51-59,809047,DMD2,DMD2_syn0010,2278,7,0.065976,0.000999,1.981137e-18,69022,4227.801849,2498.050067,2073.659861,1226.118038,True,0.000999,3.301895e-18
3,809047_2025-11-01_17-51-59,809047,DMD2,DMD2_syn0011,2278,7,0.047192,0.000999,9.084065e-14,216066,3418.122341,2594.669346,2064.895389,1746.189932,False,0.000999,9.732926e-14
4,809047_2025-11-01_17-51-59,809047,DMD2,DMD2_syn0018,2278,7,0.080085,0.000999,1.140262e-25,41006,7026.070987,3647.531174,3647.531174,2963.196003,True,0.000999,2.443418e-25

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,809047_2025-11-01_17-51-59,809047,DMD2,DMD2_syn0001,7,-130.708347,0.257253,3443.171096,1978.871149,3824.710284,2560.893153,1431.211466,0.078125,stable,0.234375
1,809047_2025-11-01_17-51-59,809047,DMD2,DMD2_syn0009,7,20.278975,-0.006180,3088.714480,759.709756,2597.112685,2120.281082,-319.476588,0.812500,stable,0.812500
2,809047_2025-11-01_17-51-59,809047,DMD2,DMD2_syn0010,7,-51.449406,0.262520,3499.308419,2540.416545,3139.699588,599.283043,1529.898023,0.218750,stable,0.445312
3,809047_2025-11-01_17-51-59,809047,DMD2,DMD2_syn0011,7,-19.901445,0.348291,2476.557149,701.643655,2794.584808,2092.941153,234.528729,0.296875,stable,0.445312
4,809047_2025-11-01_17-51-59,809047,DMD2,DMD2_syn0018,7,-289.476992,0.196538,3663.795025,2460.198457,4731.218032,4982.150632,3812.192402,0.046875,stable,0.234375

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-01_809047\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-11-05_809047/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-11-05_809047/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-11-05_809047/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-11-05_809047/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0000,image,2282,893.198492,2174.354446,up,2.847119e-58,activated,8.541356e-58
1,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0001,image,2282,7005.438671,8571.915979,up,1.735285e-200,activated,5.205855e-200
2,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0002,image,2282,0.000000,1247.702704,none,3.653162e-08,no_change,1.095949e-07
3,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0003,image,2282,211.220557,3264.434875,up,2.051772e-32,activated,6.155315e-32
4,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0004,image,2282,0.000000,1486.518651,none,2.526542e-08,no_change,7.579626e-08

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0000,2282,7,0.015771,0.000999,5.917594e-08,McGill_stairs,3148.239920,1024.127241,158.170503,476.431007,False,0.001181,9.050438e-08
1,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0001,2282,7,0.145577,0.000999,3.657354e-73,69022,13330.198638,12008.932621,9485.140033,5847.328066,True,0.001181,7.131841e-72
2,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0003,2282,7,0.034849,0.000999,3.696604e-14,268048,6716.738079,0.000000,-254.418469,1958.147932,False,0.001181,8.238147e-14
3,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0008,2282,7,0.182348,0.000999,4.840172e-49,imk01333,13037.654602,9590.726942,9590.726942,11282.010937,True,0.001181,5.393335e-48
4,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0009,2282,7,0.040102,0.000999,3.635138e-18,imk01333,4519.690184,2421.904841,2421.904841,1227.907646,False,0.001181,9.777267e-18

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0000,7,-1.034147,1.000000,4221.904726,-1115.656903,3662.864176,5024.545177,-1163.802725,0.812500,stable,0.990234
1,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0001,7,60.314118,-0.186369,6707.436644,9780.224050,11897.619547,1956.634749,438.306012,0.578125,stable,0.990234
2,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0003,7,-35.415087,1.000000,5353.231546,-2872.936349,5274.865866,7067.396221,3253.823531,0.468750,stable,0.990234
3,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0008,7,11.634039,-0.147084,1577.472982,2127.955601,1479.488478,-168.179082,91.881209,0.468750,stable,0.990234
4,809047_2025-11-05_10-13-00,809047,DMD1,DMD1_syn0009,7,6.315869,1.000000,5174.027751,-2225.781279,3694.704386,5920.485665,2595.245694,1.000000,stable,1.000000

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-05_809047\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-11-06_809047/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-11-06_809047/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-11-06_809047/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/809047/2025-11-06_809047/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,809047_2025-11-06_11-05-31,809047,DMD1,DMD1_syn0000,image,2278,0.0,8.772611,none,1.090741e-04,no_change,3.272223e-04
1,809047_2025-11-06_11-05-31,809047,DMD1,DMD1_syn0001,image,2278,0.0,5.823612,none,2.431166e-01,no_change,3.646749e-01
2,809047_2025-11-06_11-05-31,809047,DMD1,DMD1_syn0002,image,2278,0.0,40.591404,none,3.213489e-14,no_change,9.640466e-14
3,809047_2025-11-06_11-05-31,809047,DMD1,DMD1_syn0003,image,2278,0.0,37.046889,none,1.746480e-29,no_change,5.239440e-29
4,809047_2025-11-06_11-05-31,809047,DMD1,DMD1_syn0004,image,2278,0.0,-10.528942,none,1.435233e-06,no_change,4.305699e-06

Empty DataFrame
Columns: [q_shuffle_fve, q_kw]
Index: []

Empty DataFrame
Columns: [seq_q]
Index: []

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-06_809047\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-10-29_803121/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-10-29_803121/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-10-29_803121/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-10-29_803121/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0000,image,2283,449.739706,891.833893,up,1.328928e-12,activated,3.986783e-12
1,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0001,image,2283,0.000000,156.691488,none,3.339191e-02,no_change,1.001757e-01
2,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0002,image,2283,0.000000,-131.314151,none,5.059576e-01,no_change,7.589363e-01
3,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0003,image,2283,-383.733057,-648.918485,down,1.613320e-08,deactivated,4.839960e-08
4,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0004,image,2283,0.216055,74.808284,none,4.274293e-02,no_change,1.282288e-01

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0000,2283,7,0.049693,0.000999,9.973308e-19,imk00942,2205.252556,1003.272880,619.729535,314.926404,False,0.001137,2.056995e-18
1,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0006,2283,7,0.014271,0.000999,3.942706e-07,imk01643,713.755475,542.828248,542.828248,266.386811,False,0.001137,5.204372e-07
2,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0007,2283,7,0.095978,0.000999,2.541919e-33,imk00895,7168.691488,6332.833790,4275.830591,3328.975837,True,0.001137,9.320369e-33
3,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0010,2283,7,0.027644,0.000999,3.135165e-11,imk01057,467.328296,284.118666,277.629687,4.969917,False,0.001137,5.173022e-11
4,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0011,2283,7,0.039346,0.000999,7.030856e-19,imk00459,2569.974754,2602.757543,1901.623598,599.497280,False,0.001137,1.546788e-18

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0000,7,-98.146728,0.920240,496.723614,-2110.033579,1242.708645,2842.111008,3778.912796,0.078125,stable,0.286458
1,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0006,7,-10.008299,-0.902904,259.826880,2143.159672,169.097964,-1349.022730,-732.457966,0.687500,stable,0.907500
2,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0007,7,-169.715461,0.207409,3238.121716,2543.774425,4914.933271,2371.158847,4280.265299,0.078125,stable,0.286458
3,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0010,7,-1.998517,-0.525365,320.825710,794.990059,225.536620,-748.895334,-174.017559,0.937500,stable,1.000000
4,803121_2025-10-29_11-19-29,803121,DMD1,DMD1_syn0011,7,-23.462582,-0.339906,1060.430547,859.823594,1025.711175,1030.733192,-601.202327,0.578125,stable,0.829484

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-29_803121\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-10-30_803121/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-10-30_803121/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-10-30_803121/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-10-30_803121/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0000,image,2279,713.781187,968.765148,up,2.096452e-18,activated,6.289355e-18
1,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0001,image,2279,42.738759,773.323643,up,2.951859e-04,activated,8.855576e-04
2,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0002,image,2279,183.394521,273.053127,up,1.286172e-07,activated,3.858516e-07
3,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0003,image,2279,409.129227,437.713228,up,6.420687e-18,activated,1.926206e-17
4,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0004,image,2279,0.000000,-303.251798,none,1.130934e-02,no_change,3.392802e-02

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0000,2279,7,0.019887,0.000999,1.700803e-08,imk01643,1679.001432,1279.741507,645.580386,77.115863,False,0.001199,2.653253e-08
1,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0001,2279,7,0.081364,0.000999,3.500259e-24,imk00942,5894.874509,3682.662546,3682.662546,4366.808650,True,0.001199,1.137584e-23
2,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0002,2279,7,0.006727,0.025974,1.841000e-02,imk01057,530.110824,395.128685,248.850076,29.928028,False,0.028535,1.994416e-02
3,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0003,2279,7,0.025620,0.000999,4.316410e-11,imk00942,1063.159032,1113.810883,773.224403,326.339215,False,0.001199,8.016190e-11
4,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0005,2279,7,0.078551,0.000999,4.734582e-27,imk00895,2688.654387,1902.106618,1902.106618,1105.907555,True,0.001199,1.758559e-26

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0000,7,53.104945,-0.583634,1224.538088,3889.876819,1295.348893,-3032.793655,-3414.540933,0.218750,stable,0.710938
1,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0001,7,13.036892,0.421042,-909.248458,201.691233,294.174297,2363.847287,3278.967717,0.375000,stable,0.750000
2,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0002,7,-19.966655,-0.471720,378.704425,1177.815096,438.293488,-1005.687296,900.653330,0.109375,stable,0.710938
3,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0003,7,-31.204744,1.000000,915.965917,-2177.556174,708.347828,2728.822945,1553.012864,0.046875,stable,0.609375
4,803121_2025-10-30_11-13-32,803121,DMD1,DMD1_syn0005,7,35.657561,0.739739,170.245447,-1949.128818,1204.037206,3336.150629,1016.099793,0.812500,stable,0.905357

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-30_803121\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-10-31_803121/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-10-31_803121/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-10-31_803121/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-10-31_803121/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0000,image,2278,-961.228387,-1724.586555,down,2.382503e-18,deactivated,7.147510e-18
1,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0001,image,2278,-2383.371591,-2916.346178,down,4.763545e-45,deactivated,1.429064e-44
2,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0002,image,2278,-37.760489,-453.860467,down,8.024911e-03,deactivated,1.203737e-02
3,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0003,image,2278,590.680434,1292.865952,up,2.294703e-10,activated,6.884109e-10
4,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0004,image,2278,1003.254139,1614.813938,up,2.349023e-23,activated,7.047069e-23

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0003,2278,7,0.047689,0.000999,8.596374e-17,imk01220,5650.723460,4340.215597,4316.971611,4174.032616,False,0.001078,1.408027e-16
1,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0004,2278,7,0.046132,0.000999,1.592132e-15,imk01220,5489.350627,4448.520542,3842.173913,3601.785772,False,0.001078,2.520875e-15
2,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0005,2278,7,0.018304,0.000999,5.504612e-08,imk01220,3851.826687,2617.131321,2087.808547,1987.605860,False,0.001078,6.536727e-08
3,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0006,2278,7,0.027441,0.000999,1.038292e-11,imk00459,3941.703570,3545.505793,2900.156159,1395.071861,False,0.001078,1.409110e-11
4,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0008,2278,7,0.009067,0.004995,1.410040e-03,imk00459,3916.504566,2071.315284,1424.399508,423.378507,False,0.005273,1.505099e-03

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0003,7,-78.570815,1.000000,2952.582291,-764.525668,3153.299587,5541.612712,2364.797465,0.046875,stable,0.556641
1,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0004,7,-201.994114,0.298979,2788.398509,1010.601658,3540.039494,2529.437835,-43.691315,0.031250,stable,0.424107
2,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0005,7,-113.054985,0.434151,1935.959405,1500.941838,3107.332523,2143.817234,2493.121644,0.468750,stable,0.840212
3,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0006,7,-83.239382,-0.358993,2835.244052,6275.358502,2361.800970,-3607.520094,-1199.898993,0.078125,stable,0.570913
4,803121_2025-10-31_13-05-26,803121,DMD1,DMD1_syn0008,7,-46.210320,-0.033187,2778.080997,4634.742089,1292.927898,-3011.532007,2972.721218,0.937500,stable,1.000000

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-31_803121\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-11-01_803121/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-11-01_803121/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-11-01_803121/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-11-01_803121/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0000,image,2278,292.593660,1053.786069,up,8.501298e-38,activated,2.550389e-37
1,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0001,image,2278,1529.175172,3242.314524,up,2.108836e-67,activated,6.326507e-67
2,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0002,image,2278,78.925141,1194.217533,up,6.078443e-22,activated,1.823533e-21
3,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0003,image,2278,0.000000,1428.692425,none,3.643999e-07,no_change,1.093200e-06
4,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0004,image,2278,362.580977,1078.533232,up,3.676313e-46,activated,1.102894e-45

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0000,2278,7,0.052026,0.000999,3.701839e-18,41006,2667.127644,1955.356629,1906.299972,1357.967191,True,0.001081,6.269243e-18
1,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0001,2278,7,0.052913,0.000999,5.015209e-15,41006,6664.675214,4599.489615,3569.896346,2249.561427,True,0.001081,7.416859e-15
2,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0002,2278,7,0.020308,0.000999,2.168522e-08,41006,2473.767301,1089.184948,1089.184948,611.495185,False,0.001081,2.558368e-08
3,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0004,2278,7,0.013043,0.000999,6.933668e-07,41006,1810.365418,692.380561,407.816208,278.958645,False,0.001081,7.745055e-07
4,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0006,2278,7,0.104402,0.000999,1.953415e-47,McGill_stairs,5245.545565,4172.548584,4172.548584,2811.656672,True,0.001081,1.025543e-46

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0000,7,-37.380773,-0.054981,1429.336716,2235.669611,1636.768138,-722.098456,601.386686,0.21875,stable,0.450368
1,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0001,7,-86.422404,-0.059954,3167.008117,2167.417780,5413.746134,4027.862129,2331.244226,0.21875,stable,0.450368
2,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0002,7,-37.077513,0.434892,2010.150386,2166.858883,2643.288324,-1690.664027,517.157446,0.21875,stable,0.450368
3,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0004,7,-27.033329,1.000000,1557.865565,-1327.141147,1720.544844,2610.453164,1304.688751,0.21875,stable,0.450368
4,803121_2025-11-01_19-00-21,803121,DMD1,DMD1_syn0006,7,-21.772863,0.241804,1157.781524,548.413953,1761.799974,1213.386021,380.016334,0.68750,stable,0.925481

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-01_803121\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-11-05_803121/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-11-05_803121/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-11-05_803121/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-11-05_803121/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0000,image,2278,9.138544,11.487562,up,4.348932e-03,activated,1.304680e-02
1,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0001,image,2278,24.934479,23.655807,up,7.491446e-07,activated,2.247434e-06
2,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0002,image,2278,0.629642,2.723951,none,6.015263e-01,no_change,6.015263e-01
3,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0003,image,2278,22.386377,19.263691,up,2.107125e-04,activated,6.321376e-04
4,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0004,image,2278,29.422618,30.761389,up,5.952165e-09,activated,1.785649e-08

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0000,2278,7,0.008979,0.002997,8.709859e-03,216066,44.261353,27.056560,21.109802,14.408004,False,0.003643,1.048565e-02
1,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0001,2278,7,0.021463,0.000999,5.829341e-08,100075,79.079641,79.837818,63.024139,6.686516,False,0.001290,9.035478e-08
2,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0003,2278,7,0.036659,0.000999,5.978087e-16,216066,112.239478,78.002847,66.773339,18.609643,False,0.001290,1.482566e-15
3,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0004,2278,7,0.004309,0.128871,5.284641e-02,imk01333,61.696561,24.995802,-4.919467,5.675937,False,0.141416,6.067550e-02
4,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0005,2278,7,0.074827,0.000999,7.996956e-29,41006,292.847669,238.494445,188.854058,111.768158,True,0.001290,3.672676e-28

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0000,7,0.405345,1.000000,16.911964,-77.415876,10.704159,110.887051,56.427000,0.687500,stable,0.968750
1,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0001,7,-7.661223,1.000000,102.285300,-87.612226,98.700053,185.668447,260.313445,0.031250,stable,0.430556
2,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0003,7,0.737346,-0.665774,1.501737,1.161136,43.816024,37.917285,-33.685178,0.078125,stable,0.484375
3,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0004,7,1.043129,-0.358940,25.920253,70.135430,2.388611,-91.552877,4.066713,0.156250,stable,0.523649
4,803121_2025-11-05_11-16-57,803121,DMD1,DMD1_syn0005,7,-9.251106,-0.143415,107.821240,177.296463,131.210124,-94.747587,77.150501,0.015625,stable,0.430556

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-05_803121\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-11-06_803121/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-11-06_803121/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-11-06_803121/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803121/2025-11-06_803121/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0000,image,2280,-11.570199,-31.118654,down,5.504283e-13,deactivated,1.651285e-12
1,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0001,image,2280,-4.074806,-35.771417,down,8.290271e-14,deactivated,2.487081e-13
2,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0002,image,2280,0.000000,-9.559323,none,7.910649e-02,no_change,2.373195e-01
3,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0003,image,2280,0.000000,1.325095,none,3.121878e-01,no_change,3.121878e-01
4,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0004,image,2280,51.802938,137.968067,up,2.687476e-73,activated,8.062429e-73

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,q_shuffle_fve,q_kw
0,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0004,2280,7,0.409365,0.000999,3.632036e-97,216066,673.759422,647.187659,616.259942,571.640344,True,0.001213,3.087231e-96
1,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0006,2280,7,0.004701,0.091908,5.476208e-02,216066,43.265211,0.598394,-13.363881,11.132018,False,0.097652,5.818471e-02
2,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0008,2280,7,0.046888,0.000999,9.752102e-12,imk01306,144.434773,77.334082,77.334082,81.535337,False,0.001213,1.507143e-11
3,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0010,2280,7,0.170702,0.000999,6.425625e-74,41006,527.999481,564.862955,326.772614,101.893456,True,0.001213,3.641188e-73
4,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0012,2280,7,0.129902,0.000999,2.787110e-37,imk01333,346.897380,230.709164,204.401276,197.530177,True,0.001213,9.476175e-37

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0004,7,-3.614721,-0.173060,68.433730,97.076995,156.356137,56.802020,-62.179567,0.15625,stable,0.664062
1,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0006,7,-0.010323,1.000000,25.345669,-171.626236,30.831925,88.631962,-36.792032,1.00000,stable,1.000000
2,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0008,7,0.383531,-0.619604,62.329301,292.975370,45.701775,-192.205607,-133.069137,0.81250,stable,1.000000
3,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0010,7,-5.862908,0.006598,284.467885,363.335288,381.951057,33.039563,-18.039001,0.03125,stable,0.265625
4,803121_2025-11-06_12-12-23,803121,DMD1,DMD1_syn0012,7,-0.608527,0.337900,72.100396,78.941290,120.769246,60.352170,-18.425578,0.93750,stable,1.000000

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-06_803121\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f+RCaMP3/826033/826033_2026-02-17_13-13-55/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f+RCaMP3/826033/826033_2026-02-17_13-13-55/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f+RCaMP3/826033/826033_2026-02-17_13-13-55/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f+RCaMP3/826033/826033_2026-02-17_13-13-55/analysis/derived/glutamate/glutamate_analysis'))

FileNotFoundError: NPZ not found: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-17_13-13-55\analysis\derived\glutamate\glutamate_single_trial_df.npz