# Glutamate response analysis run

Use this notebook to load one session, run activation/tuning/sequence analyses, and save standardized output tables.

In [1]:
import os
import glob
import zipfile
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from vip_slap2_analysis.glutamate.analysis import (
    GlutamateAnalysisConfig,
    resolve_glutamate_analysis_paths,
    run_glutamate_analysis,
)

from vip_slap2_analysis.io.session_registry import VIPSessionRegistry

import seaborn as sns
sns.set_style('white')
params = {'legend.fontsize': 'x-large',
         'axes.labelsize': 'xx-large',
         'axes.titlesize':'xx-large',
         'xtick.labelsize':'xx-large',
         'ytick.labelsize':'xx-large'}
plt.rcParams.update(params)

from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
target_mice = [
    803496,804730,804733,810196,
    809047,803121,
    826033,838410,834788
]

In [4]:
registry = VIPSessionRegistry.from_basepath(
    r'\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics'
)

process_df = registry.sessions(
    subject_ids=target_mice,
    exclude_session_types=["expression_check"],
    paradigms=["change_detection_passive"],
)

assets = [registry.resolve_assets(row) for _, row in process_df.iterrows()]

In [5]:
assets[0]

SessionAssets(session_id='803496_2025-07-25_13-02-10', subject_id=803496, session_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496'), summary_mat=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/803496_2025-07-25_13-02-10_slap2_2026-01-18_05-53-08/source_extraction/ExperimentSummary/SummaryLoCo-260117-185357.mat'), bonsai_event_log_csv=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/803496_2025-07-25_13-02-10/behavior/VCO1_Behavior.harp/bonsai_event_log.csv'), harp_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/803496_2025-07-25_13-02-10/behavior/VCO1_Behavior.harp'), photodiode_pkl=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/803496_2025-07-25_13-02-10/behavior/VCO1_Behavior.harp/extracted_files/photodiode.pkl'), harp_df_csv=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/803496_2025-07-25_13-02-10/behavior/VCO1_Behavior.harp/extracted_files/HARP_df.csv'), qc_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/analysis/qc'), derived_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/analysis/derived'), metadata={'session_id': '803496_2025-07-25_13-02-10', 'subject_id': 803496, 'session_#': 2, 'session_date': Timestamp('2025-07-25 00:00:00'), 'indicator1': 'iGluSnFR4', 'indicator2': nan, 'dmd1_depth': 25, 'dmd2_depth': 100, 'paradigm': 'change_detection_passive', 'session_type': 'familiar', 'stimulus': 'images_A', 'experimentor': 'Andrew Shelton', 'instrument_name': 'slap2_albert', 'instrument_id': 'SLAP2_1', 'camera_type': 'vimba', 'has raster ROI?': 'yes', 'has integration roi?': 'no', 'behavior_rig': 'VCO.1', 'quality': 'good', 'flags': nan, 'session_dir': WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496'), 'purpose': nan, 'notes': nan})

In [ ]:
for asset in assets[:]:
    session_root = asset.session_dir
    paths = resolve_glutamate_analysis_paths(session_root)
    print(paths)

    config = GlutamateAnalysisConfig(
        tuning_method="fve",                 # or "manova" or "hybrid"
        manova_stat="Wilks' lambda",
        manova_max_timepoints=10,
        manova_use_post_only=True,
        random_seed=0,

        # --- new sequence-analysis settings ---
        sequence_peak_window_samples=10,     # rolling peak window inside post-image epoch
        sequence_n_quantile_bins=3,          # early / mid / late
        sequence_min_count_per_position=1,   # keep sparse late positions, but bin them
        sequence_label_slope_frac=0.15,      # relative threshold for calling non-stable motifs
        sequence_label_min_abs_slope=5,   # absolute slope floor for labels
    )

    results = run_glutamate_analysis(session_root, config=config)

    {k: v.shape for k, v in results.items() if hasattr(v, "shape")}

    activation_summary = results["activation_summary_table"]
    tuning_per_image = results["tuning_per_image_table"]
    tuning_summary = results["tuning_summary_table"]
    sequence_position = results["sequence_position_table"]
    sequence_per_image = results["sequence_per_image_table"]
    sequence_summary = results["sequence_summary_table"]

    display(activation_summary.head())
    display(tuning_summary.head())
    display(sequence_per_image.head())
    display(sequence_position.head())
    display(sequence_summary.head())

    output_dir = resolve_glutamate_analysis_paths(session_root).output_dir
    print(output_dir)
    print(sorted(p.name for p in output_dir.iterdir()))

GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-25_803496/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0000,image,2277,-20.015213,-23.085767,none,3.356907e-02,no_change,1.007072e-01
1,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0001,image,2277,11.062568,10.113008,none,1.885622e-01,no_change,3.431282e-01
2,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,image,2277,62.247024,75.345806,up,1.833899e-10,activated,5.501698e-10
3,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0003,image,2277,51.070708,94.594795,up,5.779422e-15,activated,1.733827e-14
4,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0004,image,2277,-94.736861,-159.029189,down,1.601894e-34,deactivated,4.805682e-34

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,2277,7,0.016428,0.000500,6.161776e-06,1.607803e-06,...,imk01643,209.877494,194.113103,148.201225,79.053404,False,fve,0.000778,1.247760e-05,4.069752e-06
1,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0003,2277,7,0.029130,0.000500,2.518969e-11,1.489699e-14,...,imk01378,186.991674,110.479186,69.505918,6.580640,False,fve,0.000778,7.847557e-11,7.541602e-14
2,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0005,2277,7,0.090994,0.000500,1.177659e-48,3.806244e-44,...,imk01643,622.228322,622.815466,348.406914,133.607561,True,fve,0.000778,1.907808e-47,3.853822e-43
3,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0006,2277,7,0.007872,0.006997,5.606826e-03,3.841969e-01,...,imk01220,128.009940,143.542635,117.889387,40.459149,False,fve,0.009290,7.569215e-03,3.939234e-01
4,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0007,2277,7,0.017145,0.000500,1.310140e-05,1.864352e-03,...,imk00895,117.075662,97.514651,58.983192,8.945764,False,fve,0.000778,2.526698e-05,2.849293e-03

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,stimuli\images_A\imk01378.tiff,imk01378,21,40,4.135909,-3.317766,...,0.176119,0.042583,-0.015838,0.653529,stable,-34.922383,45.880193,5,response_amplitude,False
1,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,stimuli\images_A\imk01220.tiff,imk01220,17,40,4.002009,3.400045,...,0.314888,0.078682,0.139810,1.405141,stable,64.178829,130.824089,2,response_amplitude,False
2,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,stimuli\images_A\imk00459.tiff,imk00459,16,40,2.642996,11.732948,...,0.526522,0.199214,0.181800,1.475654,stable,-14.799073,63.128745,4,response_amplitude,False
3,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,stimuli\images_A\imk01643.tiff,imk01643,13,39,3.792312,5.586604,...,0.053110,0.014005,0.095214,-0.118465,stable,156.407801,209.877494,1,response_amplitude,True
4,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,stimuli\images_A\imk00942.tiff,imk00942,14,39,9.852383,9.400597,...,-0.567097,-0.057559,-0.757631,0.229945,stable,-96.587349,-6.975492,7,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,stimuli\images_A\imk01378.tiff,imk01378,repeated,0,40.0,40,...,early,2.888889,4.678374,1.13116,270.0,-34.922383,45.880193,5,response_amplitude,False
1,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,stimuli\images_A\imk01378.tiff,imk01378,repeated,1,40.0,40,...,early,2.888889,4.678374,1.13116,270.0,-34.922383,45.880193,5,response_amplitude,False
2,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,stimuli\images_A\imk01378.tiff,imk01378,repeated,2,40.0,40,...,early,2.888889,4.678374,1.13116,270.0,-34.922383,45.880193,5,response_amplitude,False
3,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,stimuli\images_A\imk01378.tiff,imk01378,repeated,3,40.0,40,...,early,2.888889,4.678374,1.13116,270.0,-34.922383,45.880193,5,response_amplitude,False
4,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,stimuli\images_A\imk01378.tiff,imk01378,repeated,4,40.0,40,...,early,2.888889,4.678374,1.13116,270.0,-34.922383,45.880193,5,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0002,7,0.314888,0.314888,0.139810,0.739003,0.023466,4.002009,5.586604,4.665826,0.035634,-4.446395,0.218750,stable,0.256793
1,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0003,7,0.293276,0.293276,0.133638,1.405842,-0.431873,2.953085,10.091696,3.555840,-3.688215,-5.593227,0.015625,stable,0.050625
2,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0005,7,0.286486,0.286486,-0.029962,1.522233,0.170575,12.209224,9.924582,12.036393,2.757007,-7.523349,0.156250,stable,0.194712
3,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0006,7,0.519556,0.519556,0.410496,1.656695,-0.477692,3.771473,11.116352,4.375089,-7.684284,-9.139901,0.015625,stable,0.050625
4,803496_2025-07-25_13-02-10,803496,DMD1,DMD1_syn0007,7,0.086533,0.086533,0.141749,0.244003,-0.440062,2.780951,6.257007,2.848779,-1.807309,-1.981972,0.218750,stable,0.256793

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-25_803496\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-28_803496/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-28_803496/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-28_803496/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-28_803496/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0000,image,2279,-7.322039,-7.027186,none,0.058468,no_change,0.175403
1,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0001,image,2279,0.372955,-2.741992,none,0.960449,no_change,0.960449
2,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0002,image,2279,-2.073546,-2.230991,none,0.596116,no_change,0.596116
3,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0003,image,2279,2.022670,5.343727,none,0.206030,no_change,0.309045
4,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0004,image,2279,-2.952058,1.917886,none,0.838605,no_change,0.988757

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0041,2279,7,0.002612,0.440780,0.338585,0.595902,...,imk01057,27.886124,26.540467,20.937123,4.677125,False,fve,0.440780,0.38367,0.595902
1,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0053,2279,7,0.003144,0.318841,0.383670,0.040125,...,imk01220,29.504172,22.208108,15.598786,7.173881,False,fve,0.425121,0.38367,0.131351
2,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0093,2279,7,0.003648,0.223888,0.128477,0.065675,...,imk01643,33.750144,24.776745,11.670331,6.556310,False,fve,0.425121,0.38367,0.131351
3,803496_2025-07-28_08-04-39,803496,DMD2,DMD2_syn0013,2279,7,0.003843,0.189405,0.355794,0.183364,...,imk01643,23.717630,15.665176,7.588627,4.755249,False,fve,0.425121,0.38367,0.244485

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0041,stimuli\images_A\imk01643.tiff,imk01643,15,39,1.353274,7.148548,...,0.160334,0.118479,-0.081249,0.734954,stable,1.563821,13.161394,4,response_amplitude,False
1,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0041,stimuli\images_A\imk00459.tiff,imk00459,19,40,0.822842,8.777149,...,0.241664,0.293694,0.161224,0.481885,stable,-10.881455,2.494015,6,response_amplitude,False
2,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0041,stimuli\images_A\imk01057.tiff,imk01057,21,39,1.795783,8.137883,...,0.234907,0.130810,0.109378,0.576670,stable,18.742673,27.886124,1,response_amplitude,True
3,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0041,stimuli\images_A\imk01220.tiff,imk01220,16,39,1.003023,8.681523,...,0.419243,0.417980,0.176070,1.554832,stable,13.286027,23.208999,2,response_amplitude,False
4,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0041,stimuli\images_A\imk00942.tiff,imk00942,16,39,2.781649,4.417813,...,0.230903,0.083009,0.055819,0.930634,stable,-10.360423,2.940613,5,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0041,stimuli\images_A\imk01643.tiff,imk01643,repeated,0,39.0,39,...,early,2.0,1.536676,1.135524,195.0,1.563821,13.161394,4,response_amplitude,False
1,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0041,stimuli\images_A\imk01643.tiff,imk01643,repeated,1,39.0,39,...,early,2.0,1.536676,1.135524,195.0,1.563821,13.161394,4,response_amplitude,False
2,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0041,stimuli\images_A\imk01643.tiff,imk01643,repeated,2,39.0,39,...,early,2.0,1.536676,1.135524,195.0,1.563821,13.161394,4,response_amplitude,False
3,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0041,stimuli\images_A\imk01643.tiff,imk01643,repeated,3,39.0,39,...,early,2.0,1.536676,1.135524,195.0,1.563821,13.161394,4,response_amplitude,False
4,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0041,stimuli\images_A\imk01643.tiff,imk01643,repeated,4,39.0,39,...,early,2.0,1.536676,1.135524,195.0,1.563821,13.161394,4,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0041,7,0.234598,0.234598,0.109378,0.576670,-0.638445,1.003023,7.148548,1.230519,-6.123715,-4.094217,0.015625,stable,0.020833
1,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0053,7,0.200629,0.200629,0.102589,0.542050,-0.477893,2.307310,4.989984,1.998498,-2.991486,-3.197341,0.031250,stable,0.031250
2,803496_2025-07-28_08-04-39,803496,DMD1,DMD1_syn0093,7,0.370620,0.370620,0.227452,0.855189,-0.646273,1.878653,8.227758,2.082511,-5.583882,-6.607677,0.015625,stable,0.020833
3,803496_2025-07-28_08-04-39,803496,DMD2,DMD2_syn0013,7,0.227348,0.227348,0.193623,0.693129,-0.179711,1.836400,3.327475,1.622603,-1.846273,-3.817149,0.015625,stable,0.020833

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-28_803496\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-29_803496/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-29_803496/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-29_803496/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-29_803496/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,image,2279,21.644501,42.219638,up,3.327419e-05,activated,9.982258e-05
1,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0001,image,2279,-31.003103,-38.643089,down,2.155098e-12,deactivated,6.465293e-12
2,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0002,image,2279,-15.272386,-33.967593,down,1.450552e-07,deactivated,4.351656e-07
3,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0003,image,2279,8.018818,5.397400,none,7.747566e-02,no_change,2.324270e-01
4,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0004,image,2279,16.073048,24.712531,up,6.276711e-05,activated,1.883013e-04

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,2279,7,0.011122,0.001000,3.004001e-03,2.690769e-04,...,imk01057,107.098150,53.809699,36.443897,34.705245,False,fve,0.001298,3.528509e-03,4.740879e-04
1,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0004,2279,7,0.008375,0.002499,1.967942e-03,1.257109e-01,...,imk01097,54.952463,53.356200,41.735212,2.455001,False,fve,0.003082,2.510822e-03,1.431170e-01
2,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0010,2279,7,0.250095,0.000500,1.459657e-121,2.082301e-96,...,imk01057,484.644726,453.464113,319.470543,39.177590,True,fve,0.000711,5.400731e-120,5.136342e-95
3,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0011,2279,7,0.015585,0.000500,1.506017e-09,1.016995e-03,...,imk01097,105.325181,79.103289,73.662309,31.542690,False,fve,0.000711,3.184151e-09,1.636035e-03
4,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0013,2279,7,0.006938,0.015992,2.851575e-02,1.676546e-08,...,imk01057,78.596756,67.495887,41.400131,43.287376,False,fve,0.018206,3.103185e-02,3.877013e-08

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,stimuli\images_A\imk01643.tiff,imk01643,22,40,3.150628,15.472231,...,0.221379,0.070265,-0.022673,0.923753,stable,-11.033658,32.570614,5,response_amplitude,False
1,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,stimuli\images_A\imk01097.tiff,imk01097,16,39,2.481115,5.752350,...,0.118614,0.047807,-0.041701,0.723308,stable,-2.231010,40.115741,4,response_amplitude,False
2,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,stimuli\images_A\imk01057.tiff,imk01057,20,39,8.727634,7.226963,...,0.374395,0.042898,0.037282,1.129703,stable,75.915134,107.098150,1,response_amplitude,True
3,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,stimuli\images_A\imk00895.tiff,imk00895,17,39,3.166616,13.595134,...,0.253287,0.079987,0.091628,0.794988,stable,-63.416167,-12.328679,7,response_amplitude,False
4,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,stimuli\images_A\imk00459.tiff,imk00459,20,39,10.341937,6.242822,...,-0.062580,-0.006051,-0.420275,0.970404,stable,35.425682,72.392905,2,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,stimuli\images_A\imk01643.tiff,imk01643,repeated,0,40.0,40,...,early,3.149306,3.139038,0.996321,288.0,-11.033658,32.570614,5,response_amplitude,False
1,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,stimuli\images_A\imk01643.tiff,imk01643,repeated,1,40.0,40,...,early,3.149306,3.139038,0.996321,288.0,-11.033658,32.570614,5,response_amplitude,False
2,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,stimuli\images_A\imk01643.tiff,imk01643,repeated,2,40.0,40,...,early,3.149306,3.139038,0.996321,288.0,-11.033658,32.570614,5,response_amplitude,False
3,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,stimuli\images_A\imk01643.tiff,imk01643,repeated,3,40.0,40,...,early,3.149306,3.139038,0.996321,288.0,-11.033658,32.570614,5,response_amplitude,False
4,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,stimuli\images_A\imk01643.tiff,imk01643,repeated,4,40.0,40,...,early,3.149306,3.139038,0.996321,288.0,-11.033658,32.570614,5,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0000,7,0.221379,0.221379,-0.022673,0.923753,-0.427179,3.166616,7.226963,4.178840,-3.266420,-5.572246,0.031250,stable,0.037910
1,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0004,7,0.220237,0.220237,0.102498,0.440787,-0.577450,2.377035,9.577281,2.350534,-6.412672,-4.251831,0.015625,stable,0.026278
2,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0010,7,0.459728,0.459728,0.505115,0.843968,-0.530656,7.142029,19.574167,8.424949,-9.792375,-6.840520,0.015625,stable,0.026278
3,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0011,7,0.284240,0.284240,0.146009,0.523146,-0.603380,2.285015,4.078950,1.871263,-0.463153,-4.266725,0.078125,stable,0.080295
4,803496_2025-07-29_13-34-35,803496,DMD1,DMD1_syn0013,7,0.367689,0.367689,0.343771,0.436523,-0.309868,3.414104,6.539812,2.996867,-3.570467,-5.588876,0.015625,stable,0.026278

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-29_803496\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-30_803496/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-30_803496/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-30_803496/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-30_803496/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,image,2276,127.509519,144.769685,up,6.169076e-141,activated,1.850723e-140
1,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0001,image,2276,24.638196,6.322372,up,1.506774e-04,activated,4.520322e-04
2,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0002,image,2276,213.511197,238.515185,up,2.086079e-225,activated,6.258236e-225
3,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0003,image,2276,90.678339,95.101973,up,1.419521e-77,activated,4.258564e-77
4,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0004,image,2276,0.677146,-7.834420,none,6.098101e-01,no_change,6.098101e-01

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,2276,7,0.008780,0.003498,3.377251e-03,3.833456e-02,...,imk01333,173.423656,171.315554,50.311779,3.791163,False,fve,0.007685,8.380587e-03,7.338330e-02
1,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0001,2276,7,0.011314,0.001000,3.791226e-03,8.053373e-02,...,imk01333,48.958751,51.435489,28.834645,9.358197,False,fve,0.002576,8.912707e-03,1.366015e-01
2,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0002,2276,7,0.030109,0.000500,1.091178e-13,3.730160e-13,...,216066,328.210373,311.755688,110.888600,37.332404,False,fve,0.001557,1.827723e-12,4.998414e-12
3,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0003,2276,7,0.011194,0.000500,1.811481e-04,1.351337e-04,...,216066,135.284276,132.635049,46.798185,12.740008,False,fve,0.001557,8.091284e-04,6.244110e-04
4,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0006,2276,7,0.006405,0.019990,5.632466e-02,4.668351e-02,...,100075,29.064320,32.935081,26.701986,10.410738,False,fve,0.032667,8.480342e-02,8.810690e-02

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,stimuli\images_B\69022.tiff,69022,15,39,7.759012,5.988258,...,0.183859,0.023696,0.006908,0.588382,stable,29.057263,169.632493,2,response_amplitude,False
1,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,stimuli\images_B\imk01306.tiff,imk01306,13,40,6.148529,2.849519,...,-0.031138,-0.005064,-0.294250,0.594245,stable,-9.286472,136.766435,5,response_amplitude,False
2,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,stimuli\images_B\McGill_stairs.tiff,McGill_stairs,16,39,4.823471,23.883742,...,0.379533,0.078685,0.292822,0.622969,stable,-17.883628,129.397444,6,response_amplitude,False
3,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,stimuli\images_B\216066.tiff,216066,12,40,8.541943,8.616256,...,0.034383,0.004025,0.118054,-0.124453,stable,7.723696,151.346579,3,response_amplitude,False
4,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,17,40,4.043003,4.425034,...,0.564643,0.139659,0.508864,0.740956,stable,-48.290434,103.334467,7,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,stimuli\images_B\69022.tiff,69022,repeated,0,39.0,39,...,early,2.0,5.952273,0.767143,195.0,29.057263,169.632493,2,response_amplitude,False
1,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,stimuli\images_B\69022.tiff,69022,repeated,1,39.0,39,...,early,2.0,5.952273,0.767143,195.0,29.057263,169.632493,2,response_amplitude,False
2,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,stimuli\images_B\69022.tiff,69022,repeated,2,39.0,39,...,early,2.0,5.952273,0.767143,195.0,29.057263,169.632493,2,response_amplitude,False
3,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,stimuli\images_B\69022.tiff,69022,repeated,3,39.0,39,...,early,2.0,5.952273,0.767143,195.0,29.057263,169.632493,2,response_amplitude,False
4,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,stimuli\images_B\69022.tiff,69022,repeated,4,39.0,39,...,early,2.0,5.952273,0.767143,195.0,29.057263,169.632493,2,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0000,7,0.277568,0.277568,0.292822,0.588382,-0.004331,6.148529,5.988258,6.363598,0.467984,-4.361563,0.031250,stable,0.042730
1,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0001,7,0.179182,0.179182,0.168044,0.487118,-0.683314,2.007388,8.326270,2.504243,-6.941280,-2.923863,0.031250,stable,0.042730
2,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0002,7,0.318061,0.318061,0.095051,0.614981,-0.030752,11.377642,16.338159,11.621842,-5.373825,-3.681956,0.078125,stable,0.088718
3,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0003,7,0.132509,0.132509,0.022781,0.383357,-0.409051,4.554466,10.859616,4.185753,-5.175364,-1.994617,0.109375,stable,0.120133
4,803496_2025-07-30_10-05-23,803496,DMD1,DMD1_syn0006,7,0.168299,0.168299,0.073470,0.310133,-0.527628,1.176988,2.778075,1.161235,-1.697039,-2.617951,0.031250,stable,0.042730

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-30_803496\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-31_803496/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-31_803496/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-31_803496/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-07-31_803496/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,image,2277,23.565567,32.576312,up,1.141687e-04,activated,3.425061e-04
1,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0001,image,2277,26.149843,34.717327,up,1.165898e-08,activated,3.497693e-08
2,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0002,image,2277,23.338449,26.390752,up,5.337258e-09,activated,1.601177e-08
3,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0003,image,2277,20.060566,28.285237,up,2.755198e-04,activated,4.132797e-04
4,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0004,image,2277,-0.367144,9.138489,none,7.001959e-01,no_change,1.000000e+00

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,2277,7,0.054361,0.00050,5.874587e-22,3.678901e-21,...,41006,220.203901,165.156175,162.598441,174.415416,True,fve,0.000793,7.720886e-21,4.230736e-20
1,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0001,2277,7,0.016044,0.00050,3.196809e-07,2.942809e-06,...,216066,97.051511,88.543064,71.082471,47.450986,False,fve,0.000793,7.541190e-07,7.124696e-06
2,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0002,2277,7,0.012518,0.00050,2.551070e-06,1.119922e-05,...,69022,66.606783,43.261825,21.765094,16.925087,False,fve,0.000793,5.334055e-06,2.453161e-05
3,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0003,2277,7,0.003681,0.21939,2.066899e-01,1.734455e-01,...,216066,60.616723,47.414162,30.479462,14.431443,False,fve,0.243180,2.237114e-01,1.899641e-01
4,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0005,2277,7,0.021524,0.00050,5.143283e-05,1.949764e-03,...,41006,278.348697,149.511881,91.396165,129.436598,False,fve,0.000793,9.434442e-05,2.893198e-03

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,stimuli\images_B\69022.tiff,69022,15,39,2.404987,16.743623,...,0.321745,0.133782,0.236735,0.608069,stable,18.151655,18.151655,2,selectivity_score,False
1,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,27,38,1.347390,2.354495,...,0.355321,0.263711,0.300378,0.469109,stable,-80.503229,-80.503229,7,selectivity_score,False
2,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,stimuli\images_B\41006.tiff,41006,18,39,21.178661,14.153774,...,-0.465559,-0.021982,-0.905167,0.781181,stable,221.636307,221.636307,1,selectivity_score,True
3,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,stimuli\images_B\imk01333.tiff,imk01333,15,39,0.929960,6.181606,...,0.704312,0.757357,0.321927,1.845387,stable,-36.284201,-36.284201,5,selectivity_score,False
4,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,stimuli\images_B\216066.tiff,216066,22,39,1.631606,9.278615,...,0.461908,0.283100,0.516446,0.298808,stable,-28.215560,-28.215560,3,selectivity_score,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,stimuli\images_B\69022.tiff,69022,repeated,0,39.0,39,...,early,2.0,2.224403,0.924913,195.0,18.151655,18.151655,2,selectivity_score,False
1,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,stimuli\images_B\69022.tiff,69022,repeated,1,39.0,39,...,early,2.0,2.224403,0.924913,195.0,18.151655,18.151655,2,selectivity_score,False
2,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,stimuli\images_B\69022.tiff,69022,repeated,2,39.0,39,...,early,2.0,2.224403,0.924913,195.0,18.151655,18.151655,2,selectivity_score,False
3,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,stimuli\images_B\69022.tiff,69022,repeated,3,39.0,39,...,early,2.0,2.224403,0.924913,195.0,18.151655,18.151655,2,selectivity_score,False
4,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,stimuli\images_B\69022.tiff,69022,repeated,4,39.0,39,...,early,2.0,2.224403,0.924913,195.0,18.151655,18.151655,2,selectivity_score,False

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0000,7,0.321745,0.321745,0.300378,0.608069,-0.700903,1.347390,9.278615,3.025114,-6.253501,-3.767214,0.218750,stable,0.221154
1,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0001,7,0.316119,0.316119,0.192564,0.765037,0.310301,2.139159,2.255167,2.523708,-1.977045,-6.610853,0.031250,stable,0.036859
2,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0002,7,0.208070,0.208070,0.083917,0.644194,-0.488347,2.538341,8.653615,2.497733,-4.887977,-5.170733,0.046875,stable,0.050145
3,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0003,7,0.403994,0.403994,0.191138,0.545414,-0.664451,3.281883,12.119488,3.315671,-8.803817,-6.876050,0.015625,stable,0.023958
4,803496_2025-07-31_09-43-28,803496,DMD1,DMD1_syn0005,7,0.664958,0.664958,0.305698,1.140252,-0.266691,6.141007,16.475695,8.878370,-5.812984,-11.250298,0.046875,stable,0.050145

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-31_803496\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-08-01_803496/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-08-01_803496/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-08-01_803496/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/803496/2025-08-01_803496/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0000,image,2278,-38.241781,-54.493009,down,7.440372e-24,deactivated,2.232111e-23
1,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0001,image,2278,0.000000,0.434148,none,7.620824e-01,no_change,9.607628e-01
2,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0002,image,2278,0.000000,16.056385,none,4.831379e-02,no_change,1.449414e-01
3,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,image,2278,12.389700,27.979953,up,4.440151e-05,activated,1.332045e-04
4,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0004,image,2278,3.697176,30.047383,up,1.650438e-03,activated,4.951313e-03

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,2278,7,0.047062,0.000500,6.662141e-15,5.414908e-15,...,41006,219.858661,168.478659,168.478659,142.814581,False,fve,0.000719,3.497624e-14,3.158696e-14
1,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0004,2278,7,0.014134,0.000500,7.647300e-04,3.669841e-03,...,216066,112.214604,59.377323,59.377323,56.483031,False,fve,0.000719,1.163720e-03,5.584541e-03
2,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0005,2278,7,0.011643,0.000500,1.089091e-04,3.136187e-02,...,268048,55.330114,20.887655,15.346442,0.360037,False,fve,0.000719,1.844429e-04,3.874113e-02
3,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0007,2278,7,0.162084,0.000500,6.197109e-66,8.081706e-70,...,100075,1477.383162,1144.001780,711.100471,334.630609,True,fve,0.000719,2.168988e-64,2.828597e-68
4,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0008,2278,7,0.007799,0.006497,1.247833e-03,1.355361e-03,...,69022,72.682034,84.307432,62.622866,1.481721,False,fve,0.007841,1.819757e-03,2.293528e-03

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,stimuli\images_B\41006.tiff,41006,18,38,9.231354,49.026675,...,0.991969,0.107456,0.739466,1.907525,stable,225.125686,219.858661,1,response_amplitude,True
1,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,stimuli\images_B\216066.tiff,216066,20,39,3.960707,12.849152,...,0.293959,0.074219,-0.005584,1.077110,stable,-14.102443,14.805978,3,response_amplitude,False
2,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,stimuli\images_B\imk01306.tiff,imk01306,15,39,2.216472,5.462150,...,0.575404,0.259604,0.226245,1.519670,stable,-77.359653,-39.414488,7,response_amplitude,False
3,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,stimuli\images_B\69022.tiff,69022,18,38,-0.866250,12.984761,...,0.299161,0.345352,0.121420,0.605006,stable,-76.328550,-38.530685,6,response_amplitude,False
4,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,stimuli\images_B\268048.tiff,268048,13,38,0.051552,-0.977009,...,0.612014,11.871888,0.643859,0.534446,stable,-59.508700,-24.113671,5,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,stimuli\images_B\41006.tiff,41006,repeated,0,36.0,38,...,early,2.5,6.998664,0.758141,216.0,225.125686,219.858661,1,response_amplitude,True
1,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,stimuli\images_B\41006.tiff,41006,repeated,1,36.0,38,...,early,2.5,6.998664,0.758141,216.0,225.125686,219.858661,1,response_amplitude,True
2,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,stimuli\images_B\41006.tiff,41006,repeated,2,36.0,38,...,early,2.5,6.998664,0.758141,216.0,225.125686,219.858661,1,response_amplitude,True
3,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,stimuli\images_B\41006.tiff,41006,repeated,3,36.0,38,...,early,2.5,6.998664,0.758141,216.0,225.125686,219.858661,1,response_amplitude,True
4,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,stimuli\images_B\41006.tiff,41006,repeated,4,36.0,38,...,early,2.5,6.998664,0.758141,216.0,225.125686,219.858661,1,response_amplitude,True

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0003,7,0.575404,0.575404,0.226245,0.910835,-0.528764,2.216472,12.849152,3.576191,-10.419040,-4.948393,0.015625,stable,0.036458
1,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0004,7,0.430208,0.430208,0.098169,0.476617,-0.464135,2.539693,6.987774,3.548669,-2.492870,-4.587414,0.015625,stable,0.036458
2,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0005,7,0.248512,0.248512,0.109811,0.217603,-0.688612,2.584917,7.373814,2.597275,-4.776539,-1.646049,0.015625,stable,0.036458
3,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0007,7,-0.186953,-0.186953,-0.480772,1.472431,-0.213239,23.068036,35.078475,26.233931,-2.257568,-2.062751,0.578125,stable,0.601021
4,803496_2025-08-01_13-22-49,803496,DMD1,DMD1_syn0008,7,0.168786,0.168786,0.086419,0.519877,-0.325288,2.269270,4.457363,2.888808,-1.946162,-2.853738,0.015625,stable,0.036458

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-08-01_803496\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-25_804730/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-25_804730/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-25_804730/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-25_804730/analysis/derived/glutamate/glutamate_analysis'))

C:\Users\andrew.shelton\Dropbox\allen institute\Python_Code\ams\ophys\vip-slap2-analysis\src\vip_slap2_analysis\glutamate\analysis.py:193: RuntimeWarning: Mean of empty slice
  baseline = float(np.nanmean(pre_seg)) if pre_seg.size else np.nan

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0000,image,2278,0.000000,-7.901627,none,2.629127e-01,no_change,3.943690e-01
1,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0001,image,2278,0.000000,17.124573,none,3.812596e-01,no_change,6.134399e-01
2,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0002,image,2278,0.000000,-6.275322,none,2.296219e-01,no_change,2.314110e-01
3,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,image,2278,8.818317,39.478649,up,6.531216e-16,activated,1.959365e-15
4,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0004,image,2278,0.000000,-32.027310,none,3.010028e-03,no_change,9.030085e-03

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,2278,7,0.014201,0.000500,6.196481e-06,6.897921e-03,...,imk01057,73.104221,51.530046,49.554176,0.667871,False,fve,0.000532,7.405550e-06,7.191449e-03
1,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0006,2278,7,0.029585,0.000500,2.953435e-08,5.140828e-16,...,imk01220,292.387655,126.575350,41.122997,36.795783,False,fve,0.000532,3.710727e-08,8.125826e-16
2,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0008,2278,7,0.079282,0.000500,1.148891e-24,4.034294e-45,...,imk01378,339.691030,166.810474,166.810474,77.956470,True,fve,0.000532,2.962930e-24,1.235503e-44
3,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0016,2278,7,0.009508,0.002999,2.247994e-04,3.983386e-02,...,imk01643,75.374273,39.279992,39.279992,21.797683,False,fve,0.003061,2.343654e-04,4.066373e-02
4,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0017,2278,7,0.019013,0.000500,1.501762e-05,1.075566e-04,...,imk01220,162.662278,96.210850,78.079843,96.073920,False,fve,0.000532,1.711310e-05,1.197789e-04

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk00942.tiff,imk00942,20,39,3.019965,12.378972,...,0.265327,0.087858,0.211536,0.402410,stable,-28.814209,14.997088,6,response_amplitude,False
1,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk01097.tiff,imk01097,15,39,4.019817,13.691650,...,0.227123,0.056501,-0.147933,1.330048,stable,-4.303933,36.005897,4,response_amplitude,False
2,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk01057.tiff,imk01057,15,38,5.725819,6.702492,...,0.218625,0.038182,-0.140835,1.020266,stable,38.977446,73.104221,1,response_amplitude,True
3,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk01643.tiff,imk01643,15,39,4.263337,12.136250,...,-0.057306,-0.013442,-0.104761,0.050997,stable,38.198263,72.436350,2,response_amplitude,False
4,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk01220.tiff,imk01220,24,37,5.625561,15.928610,...,0.213825,0.038009,0.166160,0.340436,stable,28.436433,64.069067,3,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk00942.tiff,imk00942,repeated,0,35.0,39,...,early,2.861925,1.953157,0.646748,239.0,-28.814209,14.997088,6,response_amplitude,False
1,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk00942.tiff,imk00942,repeated,1,36.0,39,...,early,2.861925,1.953157,0.646748,239.0,-28.814209,14.997088,6,response_amplitude,False
2,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk00942.tiff,imk00942,repeated,2,36.0,39,...,early,2.861925,1.953157,0.646748,239.0,-28.814209,14.997088,6,response_amplitude,False
3,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk00942.tiff,imk00942,repeated,3,36.0,39,...,early,2.861925,1.953157,0.646748,239.0,-28.814209,14.997088,6,response_amplitude,False
4,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk00942.tiff,imk00942,repeated,4,36.0,39,...,early,2.861925,1.953157,0.646748,239.0,-28.814209,14.997088,6,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0003,7,0.218625,0.218625,0.060150,0.442358,-0.478007,4.019817,12.136250,3.607342,-6.844717,-4.095165,0.031250,stable,0.069602
1,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0006,7,0.095453,0.095453,-0.201693,1.276025,-0.171628,13.155981,22.807383,16.404452,-5.686806,-4.798836,0.218750,stable,0.274840
2,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0008,7,0.475926,0.475926,0.276824,0.529707,-0.354523,2.831023,8.158340,3.789716,-4.172397,-5.142894,0.046875,stable,0.091875
3,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0016,7,0.147325,0.147325,0.053806,0.256092,-0.136887,3.556665,4.791355,3.105938,-2.853664,-1.531256,0.031250,stable,0.069602
4,804730_2025-07-25_14-08-35,804730,DMD1,DMD1_syn0017,7,0.157394,0.157394,0.128365,0.435575,-0.323420,3.775247,9.867022,3.154751,-6.712271,-3.503502,0.156250,stable,0.206926

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-25_804730\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-28_804730/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-28_804730/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-28_804730/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-28_804730/analysis/derived/glutamate/glutamate_analysis'))

C:\Users\andrew.shelton\Dropbox\allen institute\Python_Code\ams\ophys\vip-slap2-analysis\src\vip_slap2_analysis\glutamate\analysis.py:193: RuntimeWarning: Mean of empty slice
  baseline = float(np.nanmean(pre_seg)) if pre_seg.size else np.nan

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0000,image,2278,0.000000,7.244737,none,1.759174e-05,no_change,5.277523e-05
1,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0001,image,2278,0.000000,6.355112,none,5.300946e-05,no_change,1.590284e-04
2,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0002,image,2278,0.000000,32.569209,none,5.009746e-14,no_change,1.502924e-13
3,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,image,2278,20.331811,88.113399,up,2.344941e-44,activated,7.034824e-44
4,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0004,image,2278,-33.126127,-142.333274,down,1.607856e-73,deactivated,4.823568e-73

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,2278,7,0.023865,0.0005,2.914694e-09,1.198112e-07,...,imk01097,134.965340,34.946954,17.172780,1.399822,False,fve,0.000697,8.130462e-09,2.763658e-07
1,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0011,2278,7,0.012280,0.0005,1.923850e-05,2.757338e-02,...,imk01057,193.411175,88.196707,61.013653,4.262363,False,fve,0.000697,3.289162e-05,3.176933e-02
2,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0013,2278,7,0.018702,0.0005,5.622348e-09,7.553436e-08,...,imk01643,126.560670,102.299349,82.199716,27.659776,False,fve,0.000697,1.470172e-08,1.906343e-07
3,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0014,2278,7,0.191955,0.0005,7.218833e-56,2.438675e-87,...,imk01220,400.085908,340.140815,340.140815,291.605637,True,fve,0.000697,3.825982e-54,4.308326e-86
4,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0021,2278,7,0.013191,0.0005,4.424289e-05,8.099575e-06,...,imk00459,77.873004,53.740558,48.623936,12.473484,False,fve,0.000697,6.896686e-05,1.533134e-05

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk01220.tiff,imk01220,27,40,7.009935,3.072421,...,0.111143,0.015855,0.191650,-0.031807,stable,53.236102,133.565518,2,response_amplitude,False
1,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk00459.tiff,imk00459,15,41,1.758955,7.980070,...,0.541513,0.307861,0.414192,0.904788,stable,-97.812765,4.095061,7,response_amplitude,False
2,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk00942.tiff,imk00942,18,40,4.300763,12.824788,...,0.383236,0.089109,0.291757,0.544584,stable,-45.318196,49.090405,6,response_amplitude,False
3,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk01643.tiff,imk01643,16,40,4.133145,-0.155095,...,0.500395,0.121069,0.168339,1.341312,stable,35.470681,118.338014,3,response_amplitude,False
4,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk01057.tiff,imk01057,15,40,3.053033,40.597907,...,0.250479,0.082043,-0.092739,1.434336,stable,15.864518,101.532732,4,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk01220.tiff,imk01220,repeated,0,33.0,40,...,early,3.388,6.10585,0.871028,250.0,53.236102,133.565518,2,response_amplitude,False
1,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk01220.tiff,imk01220,repeated,1,33.0,40,...,early,3.388,6.10585,0.871028,250.0,53.236102,133.565518,2,response_amplitude,False
2,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk01220.tiff,imk01220,repeated,2,33.0,40,...,early,3.388,6.10585,0.871028,250.0,53.236102,133.565518,2,response_amplitude,False
3,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk01220.tiff,imk01220,repeated,3,33.0,40,...,early,3.388,6.10585,0.871028,250.0,53.236102,133.565518,2,response_amplitude,False
4,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,stimuli\images_A\imk01220.tiff,imk01220,repeated,4,33.0,40,...,early,3.388,6.10585,0.871028,250.0,53.236102,133.565518,2,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0003,7,0.500395,0.500395,0.291757,1.341312,-0.638782,3.053033,12.824788,3.161576,-9.663212,-6.365569,0.015625,stable,0.024357
1,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0011,7,0.234537,0.234537,-0.097892,0.607704,0.100057,7.515444,6.789632,6.904384,-1.939804,-5.873690,0.031250,stable,0.038517
2,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0013,7,0.128496,0.128496,0.022160,0.393493,-0.351957,4.299388,8.058324,4.122238,-3.838304,-3.184974,0.078125,stable,0.086263
3,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0014,7,0.307425,0.307425,0.039796,0.970563,-0.053048,7.786478,9.013407,6.318181,-1.080027,-4.495305,0.046875,stable,0.055208
4,804730_2025-07-28_13-57-34,804730,DMD1,DMD1_syn0021,7,0.244680,0.244680,0.119007,0.354778,-0.474646,2.257544,8.688887,2.409072,-4.634073,-3.487970,0.015625,stable,0.024357

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-28_804730\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-29_804730/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-29_804730/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-29_804730/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-29_804730/analysis/derived/glutamate/glutamate_analysis'))

C:\Users\andrew.shelton\Dropbox\allen institute\Python_Code\ams\ophys\vip-slap2-analysis\src\vip_slap2_analysis\glutamate\analysis.py:193: RuntimeWarning: Mean of empty slice
  baseline = float(np.nanmean(pre_seg)) if pre_seg.size else np.nan

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0000,image,2277,0.0,57.240422,none,4.559096e-21,no_change,1.367729e-20
1,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0001,image,2277,0.0,29.540391,none,4.466963e-08,no_change,1.340089e-07
2,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0002,image,2277,0.0,159.978883,none,6.316040e-60,no_change,1.894812e-59
3,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0003,image,2277,0.0,40.803744,none,8.269002e-11,no_change,2.480701e-10
4,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0004,image,2277,0.0,5.404548,none,7.177088e-01,no_change,7.177088e-01

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0063,2277,7,0.065477,0.0005,1.051408e-30,5.525037e-36,...,imk01057,342.146211,291.064911,243.147378,30.803867,True,fve,0.0005,2.102816e-30,9.208395e-36
1,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0000,2277,7,0.196880,0.0005,1.926526e-47,5.723077e-109,...,imk00895,212.675570,154.250560,154.250560,174.603494,True,fve,0.0005,9.632631e-47,2.861539e-108
2,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0007,2277,7,0.050108,0.0005,1.601014e-14,4.550693e-18,...,imk01643,103.929928,36.400115,36.400115,50.473289,True,fve,0.0005,2.287163e-14,6.500990e-18
3,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0012,2277,7,0.148403,0.0005,4.388983e-28,3.365872e-70,...,imk01097,196.951674,107.102500,107.102500,152.470760,True,fve,0.0005,7.314972e-28,8.414681e-70
4,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0026,2277,7,0.020176,0.0005,4.353558e-07,1.888511e-08,...,imk01097,130.725919,57.660543,56.647026,42.328303,False,fve,0.0005,4.837287e-07,2.360639e-08

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0063,stimuli\images_A\imk01378.tiff,imk01378,13,41,13.239703,29.579546,...,0.229877,0.017363,-0.158019,1.822739,stable,7.081726,7.081726,4,selectivity_score,False
1,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0063,stimuli\images_A\imk00942.tiff,imk00942,13,41,15.145762,6.936711,...,-0.145959,-0.009637,-0.233402,0.172642,stable,-10.593314,-10.593314,5,selectivity_score,False
2,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0063,stimuli\images_A\imk00895.tiff,imk00895,14,41,6.069233,22.856390,...,1.011162,0.166605,0.968775,1.108796,stable,-227.876443,-227.876443,7,selectivity_score,False
3,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0063,stimuli\images_A\imk01097.tiff,imk01097,12,41,14.772074,21.134884,...,0.841976,0.056998,0.230689,2.318646,stable,80.321784,80.321784,2,selectivity_score,False
4,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0063,stimuli\images_A\imk01220.tiff,imk01220,11,41,15.536662,20.499026,...,-0.042306,-0.002723,-0.847527,2.770020,stable,-43.870595,-43.870595,6,selectivity_score,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0063,stimuli\images_A\imk01378.tiff,imk01378,repeated,0,27.0,41,...,early,2.0,13.027579,0.983978,135.0,7.081726,7.081726,4,selectivity_score,False
1,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0063,stimuli\images_A\imk01378.tiff,imk01378,repeated,1,27.0,41,...,early,2.0,13.027579,0.983978,135.0,7.081726,7.081726,4,selectivity_score,False
2,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0063,stimuli\images_A\imk01378.tiff,imk01378,repeated,2,27.0,41,...,early,2.0,13.027579,0.983978,135.0,7.081726,7.081726,4,selectivity_score,False
3,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0063,stimuli\images_A\imk01378.tiff,imk01378,repeated,3,27.0,41,...,early,2.0,13.027579,0.983978,135.0,7.081726,7.081726,4,selectivity_score,False
4,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0063,stimuli\images_A\imk01378.tiff,imk01378,repeated,4,27.0,41,...,early,2.0,13.027579,0.983978,135.0,7.081726,7.081726,4,selectivity_score,False

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804730_2025-07-29_14-55-04,804730,DMD1,DMD1_syn0063,7,0.479386,0.479386,0.230689,1.108796,-0.177203,14.772074,21.764491,14.879111,-6.008287,-7.677602,0.078125,stable,0.111607
1,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0000,7,0.147474,0.147474,0.063791,0.242893,-0.123261,1.634374,3.832285,2.560277,-1.216515,-2.813891,0.078125,stable,0.111607
2,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0007,7,0.148549,0.148549,0.084359,0.318796,-0.162016,2.685226,2.536691,2.749163,0.556248,-1.854462,0.296875,stable,0.371094
3,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0012,7,0.067964,0.067964,0.009595,0.496359,-0.541568,1.706224,8.073982,3.884743,-2.608041,-2.293626,0.375000,stable,0.416667
4,804730_2025-07-29_14-55-04,804730,DMD2,DMD2_syn0026,7,0.417572,0.417572,-0.027676,0.763546,-0.308532,4.836897,9.153324,4.234429,-5.923051,-7.413954,0.078125,stable,0.111607

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-29_804730\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-30_804730/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-30_804730/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-30_804730/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-30_804730/analysis/derived/glutamate/glutamate_analysis'))

C:\Users\andrew.shelton\Dropbox\allen institute\Python_Code\ams\ophys\vip-slap2-analysis\src\vip_slap2_analysis\glutamate\analysis.py:193: RuntimeWarning: Mean of empty slice
  baseline = float(np.nanmean(pre_seg)) if pre_seg.size else np.nan

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0000,image,2277,0.000000,6.422066,none,1.827399e-02,no_change,5.482198e-02
1,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,image,2277,10.273371,33.730969,up,6.038482e-30,activated,1.811545e-29
2,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0002,image,2277,0.000000,30.721095,none,2.220139e-11,no_change,6.660416e-11
3,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0003,image,2277,0.000000,-2.537169,none,3.998996e-01,no_change,5.998494e-01
4,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0004,image,2277,0.000000,20.373152,none,1.999523e-07,no_change,5.998570e-07

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,2277,7,0.019198,0.000500,7.103690e-11,0.000386,...,100075,68.412930,55.471153,51.794096,19.897820,False,fve,0.000783,2.384810e-10,0.000757
1,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0005,2277,7,0.004513,0.103448,1.166349e-01,0.037652,...,69022,95.841478,53.571439,33.408188,0.162988,False,fve,0.110502,1.274847e-01,0.045376
2,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0006,2277,7,0.005634,0.041479,4.823038e-02,0.002010,...,69022,65.477700,42.537872,42.537872,6.701702,False,fve,0.048738,5.812380e-02,0.003280
3,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0007,2277,7,0.009333,0.001999,6.356761e-06,0.000315,...,216066,197.968681,83.462623,35.721801,13.691606,False,fve,0.002847,1.195071e-05,0.000644
4,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0008,2277,7,0.014280,0.000500,1.039001e-04,0.062784,...,216066,53.111818,20.159162,18.629885,0.586532,False,fve,0.000783,1.627769e-04,0.070258

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,stimuli\images_B\216066.tiff,216066,17,38,1.504359,2.609410,...,0.226135,0.150320,0.062061,0.841348,stable,-9.118003,25.007942,5,response_amplitude,False
1,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,stimuli\images_B\69022.tiff,69022,19,38,2.850061,7.834284,...,0.318194,0.111645,0.259277,0.456593,stable,9.875658,41.288222,3,response_amplitude,False
2,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,stimuli\images_B\268048.tiff,268048,23,38,3.376304,5.505950,...,0.196339,0.058152,0.239731,0.049668,stable,2.745215,35.176415,4,response_amplitude,False
3,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,stimuli\images_B\41006.tiff,41006,16,37,1.612107,5.959499,...,0.289265,0.179433,0.107239,0.835010,stable,-30.236615,6.906274,6,response_amplitude,False
4,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,stimuli\images_B\imk01306.tiff,imk01306,14,37,1.200952,6.777335,...,-0.072680,-0.060519,-0.149721,0.288021,stable,-33.094431,4.456718,7,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,stimuli\images_B\216066.tiff,216066,repeated,0,31.0,38,...,early,2.48913,2.127756,1.414394,184.0,-9.118003,25.007942,5,response_amplitude,False
1,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,stimuli\images_B\216066.tiff,216066,repeated,1,31.0,38,...,early,2.48913,2.127756,1.414394,184.0,-9.118003,25.007942,5,response_amplitude,False
2,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,stimuli\images_B\216066.tiff,216066,repeated,2,31.0,38,...,early,2.48913,2.127756,1.414394,184.0,-9.118003,25.007942,5,response_amplitude,False
3,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,stimuli\images_B\216066.tiff,216066,repeated,3,30.0,38,...,early,2.48913,2.127756,1.414394,184.0,-9.118003,25.007942,5,response_amplitude,False
4,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,stimuli\images_B\216066.tiff,216066,repeated,4,30.0,38,...,early,2.48913,2.127756,1.414394,184.0,-9.118003,25.007942,5,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0001,7,0.196339,0.196339,0.107239,0.456593,-0.529385,2.046188,6.777335,2.277090,-4.108815,-2.217211,0.031250,stable,0.039696
1,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0005,7,0.233765,0.233765,0.235687,0.702149,-0.602619,3.564895,12.125033,3.821183,-6.163105,-4.274830,0.015625,stable,0.029375
2,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0006,7,0.253129,0.253129,0.057510,0.617579,-0.572692,4.364648,15.618965,4.294513,-10.701488,-4.064405,0.015625,stable,0.029375
3,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0007,7,0.373154,0.373154,0.011486,1.386134,-0.034987,6.012059,8.101596,5.376037,-2.979072,-7.131687,0.031250,stable,0.039696
4,804730_2025-07-30_11-11-11,804730,DMD1,DMD1_syn0008,7,0.233155,0.233155,0.155649,0.523097,-0.558838,2.094739,5.265530,1.779864,-2.714368,-3.333077,0.015625,stable,0.029375

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-30_804730\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-31_804730/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-31_804730/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-31_804730/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-07-31_804730/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,image,2277,32.281927,39.019688,up,2.391364e-16,activated,7.174091e-16
1,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0001,image,2277,14.068165,21.601726,up,8.413502e-06,activated,2.524051e-05
2,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0002,image,2277,35.612595,37.934304,up,1.766482e-22,activated,5.299445e-22
3,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0003,image,2277,31.344018,38.842228,up,1.274875e-15,activated,3.824624e-15
4,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0004,image,2277,28.887461,44.298491,up,5.643126e-12,activated,1.692938e-11

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,2277,7,0.023194,0.000500,2.128861e-08,0.029323,...,216066,100.766014,84.637358,60.273653,41.576917,False,fve,0.001235,1.032892e-07,0.039578
1,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0001,2277,7,0.006062,0.035482,1.042674e-01,0.004620,...,McGill_stairs,40.069525,25.330383,12.536893,4.834744,False,fve,0.048418,1.264725e-01,0.008070
2,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0002,2277,7,0.003362,0.266367,1.083408e-01,0.049958,...,100075,55.529261,58.930823,28.017682,9.242150,False,fve,0.298240,1.278617e-01,0.062928
3,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0003,2277,7,0.003875,0.171914,2.287302e-01,0.016142,...,41006,70.564876,52.192133,22.501934,28.360453,False,fve,0.204659,2.517955e-01,0.023759
4,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0004,2277,7,0.011310,0.001499,1.248002e-03,0.008080,...,41006,79.782708,52.452598,28.286582,4.430219,False,fve,0.002931,2.440123e-03,0.012753

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,stimuli\images_B\100075.tiff,100075,17,37,3.870661,1.487918,...,0.028647,0.007401,0.058670,-0.092704,stable,22.204610,59.189096,2,response_amplitude,False
1,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,stimuli\images_B\McGill_stairs.tiff,McGill_stairs,14,37,1.768745,6.227522,...,0.271859,0.153702,0.171971,0.543275,stable,4.946251,44.396218,3,response_amplitude,False
2,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,stimuli\images_B\imk01306.tiff,imk01306,25,37,2.673482,2.882404,...,0.197111,0.073728,0.034437,0.645388,stable,-75.664527,-24.698735,7,response_amplitude,False
3,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,stimuli\images_B\216066.tiff,216066,15,37,2.988727,7.321247,...,0.081418,0.027242,-0.269067,1.102623,stable,70.711013,100.766014,1,response_amplitude,True
4,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,23,36,-0.073419,5.026790,...,0.228214,3.108360,0.220784,0.253852,stable,-18.582133,24.229031,6,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,stimuli\images_B\100075.tiff,100075,repeated,0,37.0,37,...,early,2.5,3.0182,0.779763,222.0,22.20461,59.189096,2,response_amplitude,False
1,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,stimuli\images_B\100075.tiff,100075,repeated,1,37.0,37,...,early,2.5,3.0182,0.779763,222.0,22.20461,59.189096,2,response_amplitude,False
2,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,stimuli\images_B\100075.tiff,100075,repeated,2,37.0,37,...,early,2.5,3.0182,0.779763,222.0,22.20461,59.189096,2,response_amplitude,False
3,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,stimuli\images_B\100075.tiff,100075,repeated,3,37.0,37,...,early,2.5,3.0182,0.779763,222.0,22.20461,59.189096,2,response_amplitude,False
4,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,stimuli\images_B\100075.tiff,100075,repeated,4,37.0,37,...,early,2.5,3.0182,0.779763,222.0,22.20461,59.189096,2,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0000,7,0.197111,0.197111,0.047508,0.543275,-0.557607,1.956322,6.227522,2.309341,-3.918181,-3.572300,0.015625,stable,0.028829
1,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0001,7,0.217033,0.217033,-0.036688,0.691470,-0.525993,1.748390,4.904247,1.606621,-3.648599,-4.392816,0.015625,stable,0.028829
2,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0002,7,0.182901,0.182901,0.139986,0.458994,-0.389094,2.601166,5.837655,1.864261,-4.145186,-2.625926,0.015625,stable,0.028829
3,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0003,7,0.299983,0.299983,0.210950,0.532338,-0.619633,2.980666,10.727920,2.992865,-6.500429,-4.733443,0.031250,stable,0.038988
4,804730_2025-07-31_11-45-27,804730,DMD1,DMD1_syn0004,7,0.337241,0.337241,0.269574,0.209189,-0.540630,3.845674,9.513932,3.075208,-5.990532,-3.896225,0.015625,stable,0.028829

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-31_804730\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-08-01_804730/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-08-01_804730/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-08-01_804730/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804730/2025-08-01_804730/analysis/derived/glutamate/glutamate_analysis'))

C:\Users\andrew.shelton\Dropbox\allen institute\Python_Code\ams\ophys\vip-slap2-analysis\src\vip_slap2_analysis\glutamate\analysis.py:193: RuntimeWarning: Mean of empty slice
  baseline = float(np.nanmean(pre_seg)) if pre_seg.size else np.nan

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,image,2279,127.991999,143.141810,up,7.460263e-221,activated,2.238079e-220
1,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0001,image,2279,107.748085,131.300790,up,2.431556e-54,activated,7.294669e-54
2,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0002,image,2279,11.719513,27.881171,up,2.065679e-06,activated,6.197037e-06
3,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0003,image,2279,54.659018,65.242747,up,6.374178e-121,activated,1.912253e-120
4,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0004,image,2279,45.847445,54.102866,up,3.788065e-36,activated,1.136419e-35

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,2279,7,0.068782,0.000500,5.088048e-28,1.667041e-39,...,268048,205.317241,192.913605,73.759058,11.691388,True,fve,0.000750,3.154590e-27,1.033565e-38
1,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0001,2279,7,0.040872,0.000500,3.024855e-20,7.962782e-06,...,268048,264.283320,252.709013,171.026438,96.234049,False,fve,0.000750,1.339579e-19,1.851347e-05
2,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0002,2279,7,0.004148,0.153923,8.705683e-01,8.045912e-04,...,41006,59.257184,17.779415,6.514440,14.796726,False,fve,0.160841,8.705683e-01,1.356776e-03
3,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0003,2279,7,0.011886,0.000500,6.596432e-04,3.508380e-03,...,69022,85.827669,74.334209,21.003105,7.911990,False,fve,0.000750,9.294972e-04,5.262570e-03
4,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0004,2279,7,0.051636,0.000500,4.566871e-20,1.778707e-12,...,268048,143.455117,139.034569,106.345152,46.087307,True,fve,0.000750,1.930541e-19,5.907850e-12

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,25,40,5.815747,9.468857,...,0.433718,0.074576,0.521034,0.235756,stable,71.738028,71.738028,1,selectivity_score,True
1,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,stimuli\images_B\41006.tiff,41006,23,39,4.305826,4.429204,...,0.336869,0.078236,0.297269,0.453670,stable,-8.350589,-8.350589,4,selectivity_score,False
2,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,stimuli\images_B\216066.tiff,216066,13,40,6.224773,5.600841,...,0.303214,0.048711,0.096607,1.125757,stable,58.098074,58.098074,2,selectivity_score,False
3,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,stimuli\images_B\imk01306.tiff,imk01306,21,40,5.017229,12.756077,...,0.093461,0.018628,0.035338,0.229996,stable,-50.966555,-50.966555,6,selectivity_score,False
4,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,stimuli\images_B\69022.tiff,69022,13,39,6.398448,16.692297,...,0.014196,0.002219,-0.175288,0.824946,stable,44.430758,44.430758,3,selectivity_score,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,repeated,0,39.0,40,...,early,3.350694,5.797955,0.996941,288.0,71.738028,71.738028,1,selectivity_score,True
1,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,repeated,1,39.0,40,...,early,3.350694,5.797955,0.996941,288.0,71.738028,71.738028,1,selectivity_score,True
2,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,repeated,2,38.0,40,...,early,3.350694,5.797955,0.996941,288.0,71.738028,71.738028,1,selectivity_score,True
3,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,repeated,3,38.0,40,...,early,3.350694,5.797955,0.996941,288.0,71.738028,71.738028,1,selectivity_score,True
4,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,repeated,4,38.0,40,...,early,3.350694,5.797955,0.996941,288.0,71.738028,71.738028,1,selectivity_score,True

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0000,7,0.303214,0.303214,0.096607,0.453670,-0.239006,5.660714,9.468857,5.433992,-4.928261,-4.573672,0.015625,stable,0.021369
1,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0001,7,0.473966,0.473966,0.048830,1.565184,-0.561628,5.644785,14.042343,4.952810,-9.383240,-9.956727,0.031250,stable,0.035880
2,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0002,7,0.377686,0.377686,0.219734,0.673990,-0.483841,1.765677,7.950331,2.461512,-5.672851,-6.261158,0.015625,stable,0.021369
3,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0003,7,0.153022,0.153022,0.077415,0.244927,-0.217054,2.883381,6.678269,3.241062,-3.252463,-2.589677,0.015625,stable,0.021369
4,804730_2025-08-01_14-22-38,804730,DMD1,DMD1_syn0004,7,0.202293,0.202293,0.034663,0.485417,-0.569999,2.864211,11.260592,3.289930,-7.237299,-4.654901,0.015625,stable,0.021369

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-08-01_804730\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-25_804733/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-25_804733/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-25_804733/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-25_804733/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0000,image,2277,20.546762,22.869892,none,1.697016e-02,no_change,5.091047e-02
1,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,image,2277,47.429487,43.108061,up,4.431872e-06,activated,1.329562e-05
2,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0002,image,2277,16.822427,14.971332,up,2.404219e-03,activated,7.212656e-03
3,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0003,image,2277,-135.314813,-165.028672,down,1.847468e-57,deactivated,5.542405e-57
4,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0004,image,2277,-33.990210,-42.270624,down,1.525773e-09,deactivated,4.577319e-09

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,2277,7,0.008735,0.001499,1.406698e-03,3.376592e-03,...,imk01220,124.640785,140.110263,99.101810,40.174272,False,fve,0.001749,1.641147e-03,3.990518e-03
1,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0002,2277,7,0.005007,0.088956,2.668325e-02,2.197322e-03,...,imk01220,74.701246,45.406973,31.085389,59.073394,False,fve,0.094127,2.890685e-02,2.666084e-03
2,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0008,2277,7,0.020572,0.000500,2.606174e-07,1.751446e-02,...,imk01220,102.029569,72.623628,49.384459,69.980103,False,fve,0.000591,3.705653e-07,1.943678e-02
3,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0009,2277,7,0.036894,0.000500,1.173693e-10,2.941477e-21,...,imk00459,144.025604,71.738968,41.797240,34.446205,False,fve,0.000591,2.053962e-10,1.029517e-20
4,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0010,2277,7,0.053342,0.000500,2.826609e-25,9.847574e-30,...,imk01057,282.865802,271.063797,98.710972,17.363944,True,fve,0.000591,1.169188e-24,5.974195e-29

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk01643.tiff,imk01643,17,40,-1.286268,9.520626,...,0.617703,0.480229,0.594487,0.680316,stable,-96.371531,-37.074829,7,response_amplitude,False
1,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk00459.tiff,imk00459,16,40,6.758537,1.358356,...,-0.349823,-0.051760,-0.673974,0.696747,stable,-87.700288,-29.642335,6,response_amplitude,False
2,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk01097.tiff,imk01097,18,40,6.815477,-1.912382,...,0.731816,0.107376,0.463315,1.511503,stable,45.426701,84.466513,2,response_amplitude,False
3,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk00942.tiff,imk00942,14,39,4.696399,18.544746,...,0.091937,0.019576,-0.094877,0.785413,stable,42.360919,81.838700,3,response_amplitude,False
4,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk01220.tiff,imk01220,17,38,6.003799,17.631866,...,1.233610,0.205472,0.402942,3.689686,stable,92.296685,124.640785,1,response_amplitude,True

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk01643.tiff,imk01643,repeated,0,40.0,40,...,early,2.483193,3.048804,2.370271,238.0,-96.371531,-37.074829,7,response_amplitude,False
1,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk01643.tiff,imk01643,repeated,1,40.0,40,...,early,2.483193,3.048804,2.370271,238.0,-96.371531,-37.074829,7,response_amplitude,False
2,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk01643.tiff,imk01643,repeated,2,40.0,40,...,early,2.483193,3.048804,2.370271,238.0,-96.371531,-37.074829,7,response_amplitude,False
3,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk01643.tiff,imk01643,repeated,3,40.0,40,...,early,2.483193,3.048804,2.370271,238.0,-96.371531,-37.074829,7,response_amplitude,False
4,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk01643.tiff,imk01643,repeated,4,39.0,40,...,early,2.483193,3.048804,2.370271,238.0,-96.371531,-37.074829,7,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0001,7,0.617703,0.617703,0.402942,1.015287,-0.476445,6.758537,17.631866,6.046582,-6.686100,-6.912467,0.15625,stable,0.184659
1,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0002,7,0.448935,0.448935,0.229614,0.974336,-0.734458,2.079497,14.647673,1.937851,-12.709822,-8.074586,0.03125,stable,0.050781
2,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0008,7,0.125345,0.125345,-0.033488,0.602822,-0.609323,1.818994,9.621203,2.210947,-7.868842,-2.494470,0.03125,stable,0.050781
3,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0009,7,0.238968,0.238968,0.182090,0.469887,-0.445466,2.477304,8.848071,2.889847,-6.273923,-3.473240,0.03125,stable,0.050781
4,804733_2025-07-25_15-17-00,804733,DMD1,DMD1_syn0010,7,-0.025442,-0.025442,-0.048514,0.200071,-0.148306,8.699350,9.058096,9.117314,-0.567080,-1.032426,1.00000,stable,1.000000

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-25_804733\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-28_804733/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-28_804733/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-28_804733/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-28_804733/analysis/derived/glutamate/glutamate_analysis'))

C:\Users\andrew.shelton\Dropbox\allen institute\Python_Code\ams\ophys\vip-slap2-analysis\src\vip_slap2_analysis\glutamate\analysis.py:193: RuntimeWarning: Mean of empty slice
  baseline = float(np.nanmean(pre_seg)) if pre_seg.size else np.nan

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0000,image,2277,0.000000,4.039210,none,8.541730e-01,no_change,8.541730e-01
1,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0001,image,2277,0.000000,6.760873,none,8.805787e-01,no_change,9.948598e-01
2,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0002,image,2277,-58.420841,-75.900247,down,5.840377e-91,deactivated,1.752113e-90
3,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,image,2277,4.476792,20.404038,up,8.404823e-07,activated,2.521447e-06
4,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0004,image,2277,-9.911611,-40.012227,down,3.590991e-08,deactivated,1.077297e-07

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,2277,7,0.007234,0.010495,3.228628e-03,1.245006e-03,...,imk01057,51.787917,44.193077,44.110498,23.776854,False,fve,0.011194,3.443870e-03,1.532315e-03
1,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0007,2277,7,0.039020,0.000500,2.605757e-13,2.258230e-19,...,imk00895,152.898893,96.517796,96.517796,116.910988,False,fve,0.000551,7.580384e-13,9.032918e-19
2,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0008,2277,7,0.107040,0.000500,8.407704e-44,6.537914e-25,...,imk01057,268.440722,238.246199,194.589518,123.844718,True,fve,0.000551,5.380931e-43,3.486887e-24
3,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0009,2277,7,0.071963,0.000500,1.967710e-28,7.289720e-15,...,imk01057,191.469760,174.078936,129.512029,53.452074,True,fve,0.000551,8.995244e-28,2.591901e-14
4,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0010,2277,7,0.112574,0.000500,2.428729e-53,8.375985e-54,...,imk01220,267.308382,242.001813,117.455596,32.470967,True,fve,0.000551,3.885966e-52,8.934384e-53

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,stimuli\images_A\imk00895.tiff,imk00895,27,39,0.346405,4.401203,...,0.385715,1.113479,0.506776,0.221763,stable,8.923345,28.011063,2,response_amplitude,False
1,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,stimuli\images_A\imk01097.tiff,imk01097,18,39,0.751793,3.563332,...,0.224332,0.298396,0.285626,0.074837,stable,-6.236163,15.017199,4,response_amplitude,False
2,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,stimuli\images_A\imk01378.tiff,imk01378,17,40,1.776905,5.984901,...,0.131046,0.073750,0.174669,0.038239,stable,-7.825463,13.654942,5,response_amplitude,False
3,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,stimuli\images_A\imk00459.tiff,imk00459,14,39,2.014183,16.886672,...,-0.025148,-0.012486,-0.196016,0.509473,stable,-12.282413,9.834699,6,response_amplitude,False
4,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,stimuli\images_A\imk01057.tiff,imk01057,21,39,2.120176,1.698430,...,0.223848,0.105580,0.292521,0.070925,stable,36.663008,51.787917,1,response_amplitude,True

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,stimuli\images_A\imk00895.tiff,imk00895,repeated,0,38.0,39,...,early,3.245487,1.90675,5.50439,277.0,8.923345,28.011063,2,response_amplitude,False
1,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,stimuli\images_A\imk00895.tiff,imk00895,repeated,1,38.0,39,...,early,3.245487,1.90675,5.50439,277.0,8.923345,28.011063,2,response_amplitude,False
2,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,stimuli\images_A\imk00895.tiff,imk00895,repeated,2,38.0,39,...,early,3.245487,1.90675,5.50439,277.0,8.923345,28.011063,2,response_amplitude,False
3,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,stimuli\images_A\imk00895.tiff,imk00895,repeated,3,38.0,39,...,early,3.245487,1.90675,5.50439,277.0,8.923345,28.011063,2,response_amplitude,False
4,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,stimuli\images_A\imk00895.tiff,imk00895,repeated,4,38.0,39,...,early,3.245487,1.90675,5.50439,277.0,8.923345,28.011063,2,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0003,7,0.223848,0.223848,0.187968,0.221763,-0.651554,2.014183,5.029789,2.177021,-3.975201,-2.244070,0.031250,stable,0.035714
1,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0007,7,0.193411,0.193411,0.106968,0.417413,-0.474927,3.028556,4.908854,1.319203,-3.908057,-2.554635,0.015625,stable,0.019231
2,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0008,7,0.218157,0.218157,0.171993,0.347565,-0.380466,3.148355,13.787592,4.359839,-8.565547,-2.866887,0.015625,stable,0.019231
3,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0009,7,0.169469,0.169469,0.103699,0.737812,-0.173670,3.794638,5.890301,3.996060,-1.816909,-2.747671,0.031250,stable,0.035714
4,804733_2025-07-28_19-00-06,804733,DMD1,DMD1_syn0010,7,0.124538,0.124538,-0.065524,0.715927,-0.379620,7.844749,14.222985,6.842987,-7.214194,-3.425875,0.046875,stable,0.050000

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-28_804733\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-29_804733/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-29_804733/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-29_804733/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-29_804733/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0000,image,2278,0.000000,2.249527,none,7.604218e-03,no_change,2.281265e-02
1,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,image,2278,13.124292,18.090690,up,9.906999e-08,activated,2.972100e-07
2,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0002,image,2278,36.516792,58.672103,up,2.148264e-30,activated,6.444791e-30
3,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0003,image,2278,0.000000,-0.113329,none,3.543158e-01,no_change,5.314737e-01
4,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0004,image,2278,0.000000,23.472453,none,6.004972e-04,no_change,1.801492e-03

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,2278,7,0.009349,0.001499,5.577653e-07,7.823001e-02,...,imk01057,62.285253,46.429870,38.427462,7.015856,False,fve,0.001838,9.634128e-07,8.373917e-02
1,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0002,2278,7,0.088628,0.000500,6.447721e-37,5.431329e-28,...,imk00459,194.474650,183.895027,166.221539,72.788243,True,fve,0.000655,6.125335e-36,3.997894e-27
2,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0010,2278,7,0.037343,0.000500,2.936210e-17,3.179362e-07,...,imk00459,366.935420,286.261814,251.624426,207.628715,False,fve,0.000655,1.174484e-16,5.491626e-07
3,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0012,2278,7,0.039244,0.000500,2.918693e-15,1.253407e-18,...,imk01097,225.774756,164.492750,124.015017,74.233856,False,fve,0.000655,1.008276e-14,5.603465e-18
4,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0013,2278,7,0.169071,0.000500,1.140380e-59,3.180211e-97,...,imk00895,680.318918,593.988847,593.988847,536.953403,True,fve,0.000655,2.888963e-58,1.208480e-95

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk00459.tiff,imk00459,16,39,0.942617,8.666640,...,0.428931,0.455043,0.490930,0.202621,stable,42.092000,55.269397,2,response_amplitude,False
1,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk00895.tiff,imk00895,18,40,0.367050,6.776434,...,0.219324,0.597531,0.104618,0.463783,stable,-37.662428,-13.091542,7,response_amplitude,False
2,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk01097.tiff,imk01097,18,40,0.777156,1.275603,...,0.650670,0.837246,0.876767,0.033820,stable,-18.825486,3.054409,5,response_amplitude,False
3,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk01378.tiff,imk01378,14,39,2.482607,7.893850,...,0.366552,0.147648,0.116289,1.100131,stable,-25.414612,-2.593414,6,response_amplitude,False
4,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk00942.tiff,imk00942,16,39,1.978748,30.541656,...,0.249124,0.125900,0.150190,0.524463,stable,-7.054259,13.144032,4,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk00459.tiff,imk00459,repeated,0,39.0,39,...,early,2.480519,2.448551,2.59761,231.0,42.092,55.269397,2,response_amplitude,False
1,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk00459.tiff,imk00459,repeated,1,39.0,39,...,early,2.480519,2.448551,2.59761,231.0,42.092,55.269397,2,response_amplitude,False
2,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk00459.tiff,imk00459,repeated,2,39.0,39,...,early,2.480519,2.448551,2.59761,231.0,42.092,55.269397,2,response_amplitude,False
3,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk00459.tiff,imk00459,repeated,3,38.0,39,...,early,2.480519,2.448551,2.59761,231.0,42.092,55.269397,2,response_amplitude,False
4,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,stimuli\images_A\imk00459.tiff,imk00459,repeated,4,38.0,39,...,early,2.480519,2.448551,2.59761,231.0,42.092,55.269397,2,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0001,7,0.366552,0.366552,0.150190,0.524463,-0.785103,1.978748,7.893850,1.496776,-6.157341,-4.643901,0.015625,stable,0.028274
1,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0002,7,0.108690,0.108690,0.067965,0.797203,-0.426142,2.887772,5.842796,3.639013,-2.799182,-5.613115,0.109375,stable,0.122243
2,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0010,7,0.540252,0.540252,0.064131,1.935876,-0.472162,8.324515,26.056680,6.496997,-22.492409,-11.675111,0.015625,stable,0.028274
3,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0012,7,0.173818,0.173818,0.217181,0.173605,-0.047088,11.077926,8.176813,7.956226,-1.339403,-3.460544,0.375000,stable,0.390411
4,804733_2025-07-29_16-02-24,804733,DMD1,DMD1_syn0013,7,0.432194,0.432194,0.025563,1.387605,-0.476308,3.372821,11.398476,8.424328,-1.107062,-6.021288,0.078125,stable,0.092773

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-29_804733\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-30_804733/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-30_804733/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-30_804733/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-30_804733/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0000,image,2278,-12.894695,-19.108900,down,1.286560e-03,deactivated,1.929840e-03
1,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0001,image,2278,8.697711,14.686569,none,5.755059e-02,no_change,1.726518e-01
2,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0002,image,2278,5.281195,-5.088143,none,7.220957e-01,no_change,7.220957e-01
3,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0003,image,2278,-0.491887,-0.919548,none,7.008794e-01,no_change,7.008794e-01
4,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,image,2278,46.782947,53.701373,up,3.747473e-18,activated,1.124242e-17

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,2278,7,0.004703,0.098451,1.770781e-03,1.580036e-01,...,McGill_stairs,97.656534,110.422753,70.919136,36.444193,False,fve,0.119177,3.194350e-03,1.912675e-01
1,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0005,2278,7,0.010699,0.000500,4.596665e-06,7.776187e-04,...,69022,155.106081,149.469038,59.801988,12.492552,False,fve,0.000920,1.174703e-05,1.555237e-03
2,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0006,2278,7,0.034675,0.000500,4.833375e-14,7.156457e-05,...,69022,152.883138,145.620190,76.674044,15.249740,False,fve,0.000920,2.021229e-13,1.779443e-04
3,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0007,2278,7,0.144748,0.000500,5.934659e-68,6.651939e-36,...,216066,313.437696,287.188669,154.005607,56.841481,True,fve,0.000920,1.364972e-66,7.649730e-35
4,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0008,2278,7,0.012178,0.000500,1.544404e-05,2.145965e-02,...,216066,84.478302,71.381797,30.361011,0.173147,False,fve,0.000920,3.552129e-05,3.236537e-02

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,stimuli\images_B\McGill_stairs.tiff,McGill_stairs,17,40,2.354081,6.759959,...,0.058218,0.024730,-0.035269,0.456325,stable,51.609915,97.656534,1,response_amplitude,True
1,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,stimuli\images_B\imk01333.tiff,imk01333,12,40,3.464371,5.219891,...,0.137464,0.039679,-0.031456,0.505076,stable,9.091689,61.212341,2,response_amplitude,False
2,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,stimuli\images_B\268048.tiff,268048,15,39,1.249288,18.565724,...,0.390005,0.312181,-0.207761,1.899443,stable,-9.411911,45.352113,5,response_amplitude,False
3,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,stimuli\images_B\100075.tiff,100075,15,39,3.303047,25.151983,...,0.269213,0.081504,0.144975,0.622182,stable,-2.664972,51.135203,4,response_amplitude,False
4,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,stimuli\images_B\69022.tiff,69022,21,39,3.511710,12.103006,...,0.220483,0.062785,0.141926,0.405849,stable,8.634128,60.820145,3,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,stimuli\images_B\McGill_stairs.tiff,McGill_stairs,repeated,0,40.0,40,...,early,2.5,4.387939,1.863971,240.0,51.609915,97.656534,1,response_amplitude,True
1,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,stimuli\images_B\McGill_stairs.tiff,McGill_stairs,repeated,1,40.0,40,...,early,2.5,4.387939,1.863971,240.0,51.609915,97.656534,1,response_amplitude,True
2,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,stimuli\images_B\McGill_stairs.tiff,McGill_stairs,repeated,2,40.0,40,...,early,2.5,4.387939,1.863971,240.0,51.609915,97.656534,1,response_amplitude,True
3,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,stimuli\images_B\McGill_stairs.tiff,McGill_stairs,repeated,3,40.0,40,...,early,2.5,4.387939,1.863971,240.0,51.609915,97.656534,1,response_amplitude,True
4,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,stimuli\images_B\McGill_stairs.tiff,McGill_stairs,repeated,4,40.0,40,...,early,2.5,4.387939,1.863971,240.0,51.609915,97.656534,1,response_amplitude,True

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0004,7,0.244800,0.244800,0.113490,0.622182,-0.483417,3.303047,6.759959,2.574475,-4.326894,-4.041445,0.015625,stable,0.030585
1,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0005,7,0.041794,0.041794,0.013521,0.678272,-0.453416,4.748468,15.208522,4.369590,-11.168503,-2.658112,0.296875,stable,0.321324
2,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0006,7,0.321416,0.321416,0.155211,0.825030,-0.587229,3.911478,12.109786,3.569737,-7.420511,-5.782973,0.015625,stable,0.030585
3,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0007,7,0.302975,0.302975,0.190346,1.051329,-0.678428,5.484067,28.623819,6.006171,-23.271851,-9.010997,0.031250,stable,0.048729
4,804733_2025-07-30_12-59-44,804733,DMD1,DMD1_syn0008,7,0.344869,0.344869,0.135674,0.838052,-0.787542,2.340606,13.768205,2.611013,-10.278416,-3.629471,0.015625,stable,0.030585

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-30_804733\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-31_804733/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-31_804733/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-31_804733/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-07-31_804733/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,image,2278,23.088219,29.579810,up,2.007564e-07,activated,6.022692e-07
1,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0001,image,2278,512.777884,611.080875,up,2.350093e-238,activated,7.050279e-238
2,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0002,image,2278,6.232298,11.036412,up,1.044723e-03,activated,3.134168e-03
3,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0003,image,2278,18.511344,24.390533,up,1.712411e-06,activated,5.137232e-06
4,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0004,image,2278,-15.537744,-22.219449,down,1.929338e-04,deactivated,5.788015e-04

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,2278,7,0.003697,0.210895,5.444174e-01,3.926379e-01,...,268048,49.343737,24.163983,2.157102,3.466333,False,fve,0.275235,5.988591e-01,4.580776e-01
1,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0001,2278,7,0.141826,0.000500,3.136267e-64,4.636610e-71,...,imk01306,1040.905917,1003.667801,551.244237,191.197918,True,fve,0.001480,2.414925e-62,3.570190e-69
2,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0002,2278,7,0.003748,0.208396,1.794883e-01,2.433005e-01,...,imk01333,24.178418,12.633852,7.077495,1.454741,False,fve,0.275235,2.265672e-01,3.122356e-01
3,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0003,2278,7,0.003382,0.262869,1.688901e-01,1.345677e-01,...,69022,41.776228,25.706400,8.787132,4.006856,False,fve,0.331818,2.167423e-01,2.031709e-01
4,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0008,2278,7,0.001677,0.709145,3.297996e-01,1.221851e-01,...,268048,51.519840,23.006245,18.902272,10.932661,False,fve,0.758392,3.906857e-01,1.885961e-01

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,13,39,3.562138,3.250330,...,0.047809,0.013422,-0.097500,0.446427,stable,23.111831,49.343737,1,response_amplitude,True
1,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,stimuli\images_B\imk01306.tiff,imk01306,20,39,2.769414,14.070595,...,0.246589,0.089040,0.058882,0.952335,stable,18.895232,45.729509,3,response_amplitude,False
2,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,stimuli\images_B\imk01333.tiff,imk01333,12,39,1.426637,4.203057,...,0.268723,0.188361,0.451935,-0.160737,stable,19.067776,45.877404,2,response_amplitude,False
3,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,stimuli\images_B\100075.tiff,100075,24,39,1.711004,-2.065885,...,0.605745,0.354029,0.472156,0.805019,stable,-9.635466,21.274625,5,response_amplitude,False
4,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,stimuli\images_B\McGill_stairs.tiff,McGill_stairs,16,39,3.266244,17.948723,...,0.422441,0.129335,0.427120,0.408136,stable,-9.340375,21.527561,4,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,repeated,0,38.0,39,...,early,1.984043,3.379472,0.94872,188.0,23.111831,49.343737,1,response_amplitude,True
1,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,repeated,1,38.0,39,...,early,1.984043,3.379472,0.94872,188.0,23.111831,49.343737,1,response_amplitude,True
2,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,repeated,2,38.0,39,...,early,1.984043,3.379472,0.94872,188.0,23.111831,49.343737,1,response_amplitude,True
3,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,repeated,3,37.0,39,...,early,1.984043,3.379472,0.94872,188.0,23.111831,49.343737,1,response_amplitude,True
4,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,stimuli\images_B\268048.tiff,268048,repeated,4,37.0,39,...,early,1.984043,3.379472,0.94872,188.0,23.111831,49.343737,1,response_amplitude,True

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0000,7,0.268723,0.268723,0.427120,0.408136,-0.493174,2.165336,4.203057,1.918355,-1.770584,-2.516459,0.015625,stable,0.031661
1,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0001,7,-0.392848,-0.392848,-0.406174,-0.512031,0.183919,27.418622,22.749098,26.724358,7.544256,5.290170,0.296875,stable,0.300781
2,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0002,7,0.178431,0.178431,0.054663,0.510769,-0.740925,1.147106,8.997231,1.694927,-7.095598,-2.625003,0.015625,stable,0.031661
3,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0003,7,0.297165,0.297165,0.131925,0.535066,-0.662576,2.161222,10.171053,2.123446,-8.273584,-6.787550,0.031250,stable,0.047181
4,804733_2025-07-31_13-29-01,804733,DMD1,DMD1_syn0008,7,0.235980,0.235980,0.140802,0.751699,-0.557276,2.644569,8.168495,2.730224,-6.659188,-3.144131,0.015625,stable,0.031661

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-31_804733\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-08-01_804733/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-08-01_804733/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-08-01_804733/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/804733/2025-08-01_804733/analysis/derived/glutamate/glutamate_analysis'))

,session_id,subject_id,dmd,synapse_id,stimulus_family,n_events,median_delta_auc,mean_delta_auc,effect_direction,p_value,response_class,q_value_within_synapse
0,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0000,image,2277,0.000000,34.039712,none,1.971864e-13,no_change,5.915591e-13
1,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,image,2277,54.673802,128.329756,up,3.344848e-53,activated,1.003454e-52
2,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0002,image,2277,0.000000,-11.360168,none,1.242669e-03,no_change,3.728007e-03
3,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0003,image,2277,1.696254,36.680358,up,2.143996e-26,activated,6.431988e-26
4,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0004,image,2277,0.000000,33.547074,none,2.249812e-14,no_change,6.749436e-14

,session_id,subject_id,dmd,synapse_id,n_image_trials,n_images_tested,fve_image,p_shuffle_fve,p_kw,p_manova,...,preferred_image,preferred_mean,preferred_median,preferred_vs_rest_effect,preferred_vs_next_effect,is_tuned,tuning_method,q_shuffle_fve,q_kw,q_manova
0,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,2277,7,0.006854,0.014993,1.152593e-03,6.252234e-01,...,McGill_stairs,198.165901,176.838921,146.797360,55.767047,False,fve,0.023560,1.811218e-03,6.877458e-01
1,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0003,2277,7,0.002699,0.406797,1.789059e-01,2.109810e-01,...,41006,50.981728,16.056483,16.056483,8.767429,False,fve,0.406797,2.459956e-01,2.578656e-01
2,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0008,2277,7,0.054725,0.000500,3.852692e-23,1.296173e-14,...,41006,277.107736,262.287098,129.857425,31.984371,True,fve,0.001099,1.059490e-22,3.564476e-14
3,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0009,2277,7,0.097609,0.000500,1.099475e-39,3.393812e-37,...,imk01306,672.788818,619.246242,313.337124,79.523230,True,fve,0.001099,1.209422e-38,3.733193e-36
4,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0020,2277,7,0.010962,0.001499,2.599321e-04,1.294843e-03,...,imk01306,140.772802,88.692952,42.806793,10.733340,False,fve,0.002749,4.765421e-04,2.848656e-03

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,n_positions,n_sequences,r0,rlast,...,overall_slope,overall_slope_norm,early_slope,late_slope,sequence_label,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,stimuli\images_B\imk01333.tiff,imk01333,24,40,7.422006,19.597103,...,0.656499,0.088453,0.224223,1.500732,stable,2.490926,132.169908,4,response_amplitude,False
1,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,stimuli\images_B\McGill_stairs.tiff,McGill_stairs,11,39,8.457297,9.679434,...,0.145717,0.017230,-0.263019,1.945050,stable,79.486250,198.165901,1,response_amplitude,True
2,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,stimuli\images_B\100075.tiff,100075,19,39,4.984958,16.923005,...,0.090089,0.018072,-0.089064,0.948165,stable,-63.943437,75.226169,7,response_amplitude,False
3,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,stimuli\images_B\imk01306.tiff,imk01306,13,40,7.490820,27.763967,...,0.328098,0.043800,-0.000134,1.950731,stable,-5.017484,125.734128,5,response_amplitude,False
4,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,stimuli\images_B\41006.tiff,41006,15,38,7.901635,15.249778,...,-0.123564,-0.015638,-0.464909,0.496794,stable,14.424696,142.398854,2,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,stimulus_name,stimulus_label,position_category,sequence_position,counts,n_sequences,...,epoch_label,binned_position_center,binned_response_amplitude,binned_response_amplitude_norm,binned_counts,image_selectivity_score,ranking_score,image_rank_within_synapse,rank_basis,is_preferred_ranked_image
0,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,stimuli\images_B\imk01333.tiff,imk01333,repeated,0,35.0,40,...,early,3.152,6.430934,0.866468,250.0,2.490926,132.169908,4,response_amplitude,False
1,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,stimuli\images_B\imk01333.tiff,imk01333,repeated,1,35.0,40,...,early,3.152,6.430934,0.866468,250.0,2.490926,132.169908,4,response_amplitude,False
2,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,stimuli\images_B\imk01333.tiff,imk01333,repeated,2,35.0,40,...,early,3.152,6.430934,0.866468,250.0,2.490926,132.169908,4,response_amplitude,False
3,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,stimuli\images_B\imk01333.tiff,imk01333,repeated,3,35.0,40,...,early,3.152,6.430934,0.866468,250.0,2.490926,132.169908,4,response_amplitude,False
4,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,stimuli\images_B\imk01333.tiff,imk01333,repeated,4,34.0,40,...,early,3.152,6.430934,0.866468,250.0,2.490926,132.169908,4,response_amplitude,False

,session_id,subject_id,dmd,synapse_id,n_images_with_sequences,median_seq_slope,median_overall_slope,median_early_slope,median_late_slope,median_adaptation_index,median_r0,median_rlast,median_rterminal,median_terminal_minus_last,median_early_minus_late,seq_p,sequence_class,seq_q
0,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0001,7,0.328098,0.328098,-0.000134,1.369885,-0.450611,7.490820,16.923005,6.482226,-8.881085,-5.437394,0.046875,stable,0.073661
1,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0003,7,0.215336,0.215336,0.189521,0.447173,-0.478782,2.797525,5.457405,3.172663,-3.269079,-4.458489,0.015625,stable,0.034375
2,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0008,7,-0.113710,-0.113710,-0.212150,0.502780,-0.137923,11.701692,11.378147,13.154311,-0.863480,-0.082497,0.812500,stable,0.812500
3,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0009,7,-0.299845,-0.299845,-1.018255,1.093037,0.065970,27.356773,25.709499,26.872424,4.963932,-3.577756,0.468750,stable,0.515625
4,804733_2025-08-01_15-20-32,804733,DMD1,DMD1_syn0020,7,0.348973,0.348973,0.328334,0.447826,-0.508267,5.451233,11.787546,4.130657,-8.469850,-3.651376,0.109375,stable,0.150391

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-08-01_804733\analysis\derived\glutamate\glutamate_analysis
['activation_event_table.csv', 'activation_event_table.parquet', 'activation_summary_table.csv', 'activation_summary_table.parquet', 'glutamate_analysis_metadata.json', 'sequence_per_image_table.csv', 'sequence_per_image_table.parquet', 'sequence_position_table.csv', 'sequence_position_table.parquet', 'sequence_summary_table.csv', 'sequence_summary_table.parquet', 'tuning_per_image_table.csv', 'tuning_per_image_table.parquet', 'tuning_summary_table.csv', 'tuning_summary_table.parquet']
GlutamateAnalysisPaths(single_trial_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-25_810196/analysis/derived/glutamate/glutamate_single_trial_df.npz'), mean_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-25_810196/analysis/derived/glutamate/glutamate_mean_df.npz'), sequence_npz=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-25_810196/analysis/derived/glutamate/glutamate_sequence_df.npz'), output_dir=WindowsPath('//allen/aind/scratch/ophys/Andrew/VIP_synaptic_dynamics/iGluSnFR4f/810196/2025-07-25_810196/analysis/derived/glutamate/glutamate_analysis'))