In [52]:
import os
import glob
import shutil
import pandas as pd
from pathlib import Path

### Move .yml file to directories

In [2]:
yaml_path = r"\\allen\aind\scratch\ophys\Andrew\metadata\device.yml"
basepath = r'\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031'
data_paths = glob.glob(os.path.join(basepath,'**','VCO1_Behavior.harp'),recursive=True)
data_paths

['\\\\allen\\aind\\scratch\\ophys\\Andrew\\VIP_synaptic_dynamics\\ASAP7\\826031\\826031_2026-01-30_15-04-02\\behavior\\VCO1_Behavior.harp',
 '\\\\allen\\aind\\scratch\\ophys\\Andrew\\VIP_synaptic_dynamics\\ASAP7\\826031\\826031_2026-02-01_11-01-50\\behavior\\VCO1_Behavior.harp',
 '\\\\allen\\aind\\scratch\\ophys\\Andrew\\VIP_synaptic_dynamics\\ASAP7\\826031\\826031_2026-02-02_10-23-53\\behavior\\VCO1_Behavior.harp',
 '\\\\allen\\aind\\scratch\\ophys\\Andrew\\VIP_synaptic_dynamics\\ASAP7\\826031\\826031_2026-02-03_14-21-45\\behavior\\VCO1_Behavior.harp',
 '\\\\allen\\aind\\scratch\\ophys\\Andrew\\VIP_synaptic_dynamics\\ASAP7\\826031\\826031_2026-02-04_12-15-34\\behavior\\VCO1_Behavior.harp',
 '\\\\allen\\aind\\scratch\\ophys\\Andrew\\VIP_synaptic_dynamics\\ASAP7\\826031\\826031_2026-02-05_09-28-56\\behavior\\VCO1_Behavior.harp',
 '\\\\allen\\aind\\scratch\\ophys\\Andrew\\VIP_synaptic_dynamics\\ASAP7\\826031\\826031_2026-02-06_10-21-20\\behavior\\VCO1_Behavior.harp',
 '\\\\allen\\aind\\scratch\\ophys\\Andrew\\VIP_synaptic_dynamics\\ASAP7\\826031\\826031_2026-02-10_10-48-51\\behavior\\VCO1_Behavior.harp',
 '\\\\allen\\aind\\scratch\\ophys\\Andrew\\VIP_synaptic_dynamics\\ASAP7\\826031\\826031_2026-02-11_12-42-21\\behavior\\VCO1_Behavior.harp',
 '\\\\allen\\aind\\scratch\\ophys\\Andrew\\VIP_synaptic_dynamics\\ASAP7\\826031\\826031_2026-02-12_07-43-37\\behavior\\VCO1_Behavior.harp']

In [ ]:
for path in data_paths:
    if 'device.yml' in os.listdir(path):
        print(path)
        print('device metadata in path')
    else:
        shutil.copy(yaml_path,path)
        new_path = glob.glob(os.path.join(path,'**.yml'))[0]
        print(new_path)

### Move bonsai_event_log.csv to processing directories

In [ ]:
for path in data_paths:
    if 'bonsai_event_log.csv' in os.listdir(path):
        print(path)
        print('Behavior data in path')
    else:
        try:
            parent = Path(path).parents[0]
            behavior_path  = glob.glob(os.path.join(parent,'bonsai_event_log.csv'))[0]
            shutil.move(behavior_path,path)
            new_path = glob.glob(os.path.join(path,'**.csv'))[0]
            print(new_path)
        except:
            print(path)

### Move instrument.json to session_directories

In [3]:
basepath = r'\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics'
json_path = r"\\allen\aind\scratch\ophys\Andrew\metadata\instrument.json"

In [4]:
mice = [803496,804730,804733,810196,809043,809044,809047,803121,814591,814593,
        825854,825855,824806,826031,826032,826033,826034,834788,
        838410,836173,836174
]

In [30]:
from __future__ import annotations

import re
import shutil
from pathlib import Path

def find_session_root_subdir(session_dir: Path, mouse: int | str) -> Path:
    """
    Find the subdirectory inside `session_dir` whose name matches:
        nnnnnn_yyyy-mm-dd_hh-mm-ss
    where nnnnnn == mouse id (6 digits).
    Returns the matching Path, or raises ValueError with a helpful message.
    """
    mouse = str(mouse)
    pattern = re.compile(rf"^{re.escape(mouse)}_\d{{4}}-\d{{2}}-\d{{2}}_\d{{2}}-\d{{2}}-\d{{2}}$")

    matches = [p for p in session_dir.iterdir() if p.is_dir() and pattern.match(p.name)]
    if len(matches) == 0:
        raise ValueError(f"No matching destination subdir in {session_dir}")
    if len(matches) > 1:
        raise ValueError(f"Multiple matching destination subdirs in {session_dir}: {[m.name for m in matches]}")
    return matches[0]

def move_instrument_json(session_dir: Path, mouse: int | str, overwrite: bool = False) -> Path:
    """
    Move session_dir/instrument.json into the matched subdirectory.
    Returns destination path.
    """
    src = session_dir / "instrument.json"
    if not src.exists():
        raise FileNotFoundError(f"Missing {src}")

    dest_dir = find_session_root_subdir(session_dir, mouse)
    dest = dest_dir / "instrument.json"

    if dest.exists():
        if overwrite:
            dest.unlink()
        else:
            raise FileExistsError(f"Destination already has instrument.json: {dest}")

    dest_dir.mkdir(parents=True, exist_ok=True)
    shutil.move(str(src), str(dest))
    return dest

In [31]:
for mouse in mice:
    mouse = str(mouse)

    # Find the mouse directory robustly (no glob()[0] crashes)
    candidates = list(Path(basepath).rglob(mouse))
    candidates = [p for p in candidates if p.is_dir()]

    if not candidates:
        print(f"[SKIP] mouse {mouse}: no directory found under {basepath}")
        continue
    if len(candidates) > 1:
        # pick the shortest path as a heuristic; adjust if you have a better rule
        candidates = sorted(candidates, key=lambda p: len(str(p)))
        print(f"[WARN] mouse {mouse}: multiple dirs found, using {candidates[0]}")
    data_dir = candidates[0]

    session_folders = [
        p for p in data_dir.iterdir()
        if p.is_dir()
        and "processed_data" not in p.name
        and "predictive_processing_data" not in p.name
    ]

    for session_dir in session_folders:
        src = session_dir / "instrument.json"

        # your original conditional, but safer
        if not src.exists():
            continue
        if (session_dir / "behavior").exists():
            continue

        try:
            dest = move_instrument_json(session_dir, mouse, overwrite=False)
            print(f"[OK] moved {src.name} -> {dest}")
        except Exception as e:
            print(f"[ERROR] {session_dir}: {e}")

[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-01_803496\803496_2025-07-01_14-56-10\instrument.json
[ERROR] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-25_803496: No matching destination subdir in \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-25_803496
[ERROR] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-28_803496: No matching destination subdir in \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-28_803496
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-29_803496\803496_2025-07-29_13-34-35\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-30_803496\803496_2025-07-30_10-05-23\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-31_803496\803496_2025-07-31_09-43-28\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-08-01_803496\803496_2025-08-01_13-22-49\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-07_804730\804730_2025-07-07_08-47-41\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-25_804730\804730_2025-07-25_14-08-35\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-28_804730\804730_2025-07-28_13-57-34\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-29_804730\804730_2025-07-29_14-55-04\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-30_804730\804730_2025-07-30_11-11-11\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-31_804730\804730_2025-07-31_11-45-27\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-08-01_804730\804730_2025-08-01_14-22-38\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-14_804733\804733_2025-07-14_15-14-24\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-25_804733\804733_2025-07-25_15-17-00\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-28_804733\804733_2025-07-28_19-00-06\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-29_804733\804733_2025-07-29_16-02-24\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-30_804733\804733_2025-07-30_12-59-44\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-31_804733\804733_2025-07-31_13-29-01\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-08-01_804733\804733_2025-08-01_15-20-32\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-14_810196\810196_2025-07-14_18-16-47\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-25_810196\810196_2025-07-25_16-24-20\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-28_810196\810196_2025-07-28_19-59-05\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-29_810196\810196_2025-07-29_17-02-41\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-30_810196\810196_2025-07-31_08-28-08\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-31_810196\810196_2025-07-31_14-19-46\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-08-01_810196\810196_2025-08-01_16-37-27\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809043\2025-08-27_809043\809043_2025-08-27_12-26-49\instrument.json
[ERROR] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809043\2025-12-04_809043_BigVolume: No matching destination subdir in \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809043\2025-12-04_809043_BigVolume
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809044\2025-08-27_809044\809044_2025-08-27_13-10-38\instrument.json
[ERROR] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809044\2025-12-04_809044_BigVolume: No matching destination subdir in \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809044\2025-12-04_809044_BigVolume
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-03_809047\809047_2025-10-03_16-13-46\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-29_809047\809047_2025-10-29_10-16-32\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-30_809047\809047_2025-10-30_10-06-43\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-31_809047\809047_2025-10-31_12-00-50\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-01_809047\809047_2025-11-01_17-51-59\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-05_809047\809047_2025-11-05_10-13-00\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-06_809047\809047_2025-11-06_11-05-31\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-31_803121\803121_2025-10-31_13-05-26\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-01_803121\803121_2025-11-01_19-00-21\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-05_803121\803121_2025-11-05_11-16-57\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-06_803121\803121_2025-11-06_12-12-23\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814591\2025-11-07_814591\814591_2025-11-07_10-21-49\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814591\2026-01-13_814591_BigStacks\814591_2026-01-13_10-37-24\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814593\2025-11-07_814593\814593_2025-11-07_13-36-49\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814593\2026-01-13_814593_BigStacks\814593_2026-01-13_13-41-32\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\825854\2026-01-12_825854\825854_2026-01-12_11-09-10\instrument.json

[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\825855\2026-01-12_825855\825855_2026-01-12_11-56-04\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\824806\2026-01-08_824806\824806_2026-01-08_11-12-01\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\2025-12-01_826033\826033_2025-12-01_10-44-52\instrument.json
[OK] moved instrument.json -> \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826034\2025-12-01_826034\826034_2025-12-01_11-32-40\instrument.json
[ERROR] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-02-13_15-22-44: No matching destination subdir in \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-02-13_15-22-44
[ERROR] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-02-13_15-49-00: No matching destination subdir in \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-02-13_15-49-00
[ERROR] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836173\836173_2026-02-13_16-42-29: No matching destination subdir in \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836173\836173_2026-02-13_16-42-29
[ERROR] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836174\836174_2026-02-13_16-17-06: No matching destination subdir in \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836174\836174_2026-02-13_16-17-06

In [38]:
session_folders = []

for mouse in mice:
    data_dir = glob.glob(os.path.join(basepath,'**',str(mouse)))[0]
    for path in os.listdir(data_dir):
        session_folder = os.path.join(data_dir,path)
        if os.path.isdir(session_folder) and 'processed_data' not in session_folder and 'predictive_processing_data' not in session_folder:
            print(session_folder)
            session_folders.append(session_folder)

\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-01_803496
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-25_803496
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-28_803496
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-29_803496
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-30_803496
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-31_803496
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-08-01_803496
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-07_804730
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-25_804730
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-28_804730
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-29_804730
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-30_804730
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-31_804730
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-08-01_804730
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-14_804733
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-25_804733
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-28_804733
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-29_804733
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-30_804733
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-31_804733
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-08-01_804733
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-14_810196
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-25_810196
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-28_810196
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-29_810196
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-30_810196
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-31_810196
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-08-01_810196
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809043\2025-08-27_809043
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809043\2025-12-04_809043_BigVolume
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809044\2025-08-27_809044
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809044\2025-12-04_809044_BigVolume
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-03_809047
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-29_809047
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-30_809047
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-31_809047
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-01_809047
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-05_809047
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-06_809047
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-06_803121
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-29_803121
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-30_803121
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-31_803121
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-01_803121
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-05_803121
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-06_803121
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814591\2025-11-07_814591
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814591\2026-01-13_814591_BigStacks
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814593\2025-11-07_814593
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814593\2026-01-13_814593_BigStacks
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\825854\2026-01-12_825854
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\825855\2026-01-12_825855
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\824806\2026-01-08_824806
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\2026-01-08_826031
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-01-30_15-04-02
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-01_11-01-50
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-02_10-23-53
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-03_14-21-45
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-04_12-15-34
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-05_09-28-56
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-06_10-21-20
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-10_10-48-51
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-11_12-42-21
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-12_07-43-37
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\2026-01-08_826032
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-01-29_12-59-37
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-01-30_16-31-08
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-02_08-24-52
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-03_16-02-38
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-04_13-49-07
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-05_13-18-03
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-06_11-45-33
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-10_13-02-11
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-11_14-46-30
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\2025-12-01_826033
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-17_13-13-55
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-18_11-57-04
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-19_13-47-57
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-21_09-23-34
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-23_10-45-21
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-24_14-14-45
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-25_08-49-29
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-26_12-40-54
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-27_13-53-35
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826034\2025-12-01_826034
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-02-13_15-22-44
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-02_10-18-42
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-03_09-22-19
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-04_08-43-07
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-05_08-11-16
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-02-13_15-49-00
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-02_12-40-55
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-03_13-49-07
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-04_12-54-47
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-05_10-16-37
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836173\836173_2026-02-13_16-42-29
\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836174\836174_2026-02-13_16-17-06

In [ ]:
for folder in session_folders:
    static_data = glob.glob(os.path.join(Path(folder).parent,'**','**VasMap**'),recursive=True)
    print(static_data)

In [ ]:
for mouse in mice:
    data_dir = glob.glob(os.path.join(basepath,'**',str(mouse)))[0]
    vas_file = glob.glob(os.path.join(data_dir,'**','**local_vasculature**'),recursive=True)
    print(vas_file)

In [ ]:
df = pd.DataFrame(columns = ['session_id',
                             'subject_id',
                             'session_#',
                             'session_date',
                             'indicator1',
                             'indicator2',
                             'dmd1_depth',
                             'dmd2_depth',
                             'paradigm',
                             'session_type',
                             'stimulus',
                             'experimentor',
                             'imaging_rig',
                             'behavior_rig',
                             'session_dir',
                             'purpose',
                             'notes'
])

In [ ]:
df['session_dir'] = session_folders

In [ ]:
df['session_id'] = [Path(path).stem for path in session_folders]

In [ ]:
import re
from datetime import datetime
from typing import Optional, Dict, Any

# Matches:
#   yyyy-mm-dd_nnnnnn
#   nnnnnn_yyyy-mm-dd
#   nnnnnn_yyyy-mm-dd_hh-mm-ss
_PAT = re.compile(
    r"""
    ^(?:
        (?P<date1>\d{4}-\d{2}-\d{2})_(?P<sid1>\d{6})               # yyyy-mm-dd_nnnnnn
        (?:_(?P<big1>Big[A-Za-z]+))?                               # optional _Big...
      |
        (?P<sid2>\d{6})_(?P<date2>\d{4}-\d{2}-\d{2})               # nnnnnn_yyyy-mm-dd ...
        (?:_(?P<time2>\d{2}-\d{2}-\d{2}))?                         # optional _hh-mm-ss
        (?:_(?P<big2>Big[A-Za-z]+))?                               # optional _Big...
    )$
    """,
    re.VERBOSE,
)

def parse_subject_and_date(s: str) -> Dict[str, Any]:
    """
    Parses:
      - yyyy-mm-dd_nnnnnn
      - yyyy-mm-dd_nnnnnn_BigVolume / _BigStacks (or any _Big<letters>)
      - nnnnnn_yyyy-mm-dd
      - nnnnnn_yyyy-mm-dd_hh-mm-ss
      - (optionally) ..._BigSomething at the end

    Returns:
      {
        'subject_id': str (6 digits),
        'date': datetime.date,
        'datetime': datetime | None,   # present if time included
      }
    """
    m = _PAT.match(s.strip())
    if not m:
        raise ValueError(f"Unrecognized format: {s!r}")

    subject_id = m.group("sid1") or m.group("sid2")
    date_str   = m.group("date1") or m.group("date2")
    time_str   = m.group("time2")  # only possible in sid2/date2 branch

    d = datetime.strptime(date_str, "%Y-%m-%d").date()

    dt: Optional[datetime] = None
    if time_str is not None:
        dt = datetime.strptime(f"{date_str}_{time_str}", "%Y-%m-%d_%H-%M-%S")

    return {"subject_id": subject_id, "date": d, "datetime": dt}

In [ ]:
for session in df['session_id'].values:
    parse = parse_subject_and_date(session)
    print(parse['date'])

In [ ]:


df['session_date'] = 
df['subject_id'] =

In [ ]:
filen = '2026-02-16_session_df.csv'
savepath = os.path.join(basepath,filen) 
df.to_csv(savepath)

In [ ]:
Path(path).stem

### Delete old metadata files

In [54]:
from pathlib import Path

root = Path(r"\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics")  # change as needed
dry_run = False  # set to False to actually delete

for path in root.rglob("instrument.json"):
    if dry_run:
        print(f"[DRY RUN] Would delete: {path}")
    else:
        try:
            path.unlink()
            print(f"Deleted: {path}")
        except Exception as e:
            print(f"Failed to delete {path}: {e}")

Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\2026-01-08_826031\826031_2026-01-08_12-11-08\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\2026-01-08_826032\826032_2026-01-08_15-19-44\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-06_803121\803121_2025-10-06_17-44-40\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-29_803121\803121_2025-10-29_11-19-29\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-30_803121\803121_2025-10-30_11-13-32\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-31_803121\803121_2025-10-31_13-05-26\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-01_803121\803121_2025-11-01_19-00-21\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-05_803121\803121_2025-11-05_11-16-57\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-06_803121\803121_2025-11-06_12-12-23\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-01_803496\803496_2025-07-01_14-56-10\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-25_803496\803496_2025-07-25_13-02-10\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-28_803496\803496_2025-07-28_08-04-39\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-29_803496\803496_2025-07-29_13-34-35\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-30_803496\803496_2025-07-30_10-05-23\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-31_803496\803496_2025-07-31_09-43-28\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-08-01_803496\803496_2025-08-01_13-22-49\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-07_804730\804730_2025-07-07_08-47-41\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-25_804730\804730_2025-07-25_14-08-35\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-28_804730\804730_2025-07-28_13-57-34\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-29_804730\804730_2025-07-29_14-55-04\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-30_804730\804730_2025-07-30_11-11-11\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-31_804730\804730_2025-07-31_11-45-27\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-08-01_804730\804730_2025-08-01_14-22-38\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-14_804733\804733_2025-07-14_15-14-24\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-25_804733\804733_2025-07-25_15-17-00\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-28_804733\804733_2025-07-28_19-00-06\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-29_804733\804733_2025-07-29_16-02-24\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-30_804733\804733_2025-07-30_12-59-44\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-31_804733\804733_2025-07-31_13-29-01\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-08-01_804733\804733_2025-08-01_15-20-32\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-03_809047\809047_2025-10-03_16-13-46\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-29_809047\809047_2025-10-29_10-16-32\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-30_809047\809047_2025-10-30_10-06-43\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-31_809047\809047_2025-10-31_12-00-50\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-01_809047\809047_2025-11-01_17-51-59\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-05_809047\809047_2025-11-05_10-13-00\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-06_809047\809047_2025-11-06_11-05-31\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-14_810196\810196_2025-07-14_18-16-47\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-25_810196\810196_2025-07-25_16-24-20\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-28_810196\810196_2025-07-28_19-59-05\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-29_810196\810196_2025-07-29_17-02-41\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-30_810196\810196_2025-07-31_08-28-08\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-31_810196\810196_2025-07-31_14-19-46\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-08-01_810196\810196_2025-08-01_16-37-27\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\2025-12-01_826033\826033_2025-12-01_10-44-52\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826034\2025-12-01_826034\826034_2025-12-01_11-32-40\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\824806\2026-01-08_824806\824806_2026-01-08_11-12-01\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\825854\2026-01-12_825854\825854_2026-01-12_11-09-10\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\825855\2026-01-12_825855\825855_2026-01-12_11-56-04\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809043\2025-08-27_809043\809043_2025-08-27_12-26-49\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809044\2025-08-27_809044\809044_2025-08-27_13-10-38\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814591\2025-11-07_814591\814591_2025-11-07_10-21-49\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814591\2026-01-13_814591_BigStacks\814591_2026-01-13_10-37-24\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814593\2025-11-07_814593\814593_2025-11-07_13-36-49\instrument.json
Deleted: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814593\2026-01-13_814593_BigStacks\814593_2026-01-13_13-41-32\instrument.json

### Find/delete unneeded data

In [49]:
summary_path = glob.glob(os.path.join(basepath,'**summary.xlsx'))[0]
summary_df = pd.read_excel(summary_path,sheet_name='subjects')
session_df = pd.read_excel(summary_path,sheet_name='sessions')

In [15]:
key_match = '**_REGISTERED_DOWNSAMPLED**'

session_sizes = []

for idx, row in delete_df.iterrows():
    try:
        sess_path = row['session_dir']   # change if your column name is different

        alignment_paths = glob.glob(
            os.path.join(sess_path, '**', key_match),
            recursive=True
        )

        total_bytes = 0
        for path in alignment_paths:
            if os.path.isfile(path):
                total_bytes += os.path.getsize(path)

        total_tb = total_bytes / (1024**4)   # tebibytes-style TB
        total_gb = total_bytes / (1024**3)

        session_sizes.append({
            'session_path': sess_path,
            'n_files_found': len(alignment_paths),
            'total_bytes': total_bytes,
            'total_gb': total_gb,
            'total_tb': total_tb,
        })
    except:
        pass
size_df = pd.DataFrame(session_sizes)
size_df

,session_path,n_files_found,total_bytes,total_gb,total_tb
0,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,46,277971958820,258.881560,0.252814
1,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,834423617336,777.117552,0.758904
2,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,790499664432,736.210183,0.718955
3,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,754186435256,702.390853,0.685929
4,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,748050659728,696.676466,0.680348
5,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,682741974832,635.853014,0.620950
6,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,673392595552,627.145726,0.612447
7,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,120,148006535520,137.841828,0.134611
8,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,719110841920,669.724161,0.654028
9,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,762592970688,710.220049,0.693574
10,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,751868746152,700.232336,0.683821
11,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,662330973680,616.843788,0.602387
12,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,703888064832,655.546845,0.640182
13,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,747670169360,696.322107,0.680002
14,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,44,201446098480,187.611299,0.183214
15,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,1123404928832,1046.252371,1.021731
16,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,627198808096,584.124409,0.570434
17,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,734860099376,684.391800,0.668351
18,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,672779886752,626.575096,0.611890
19,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,673990265136,627.702349,0.612991
20,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,728584290240,678.546997,0.662644
21,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,44,219077190888,204.031533,0.199250
22,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,1350648596608,1257.889528,1.228408
23,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,723347858032,673.670189,0.657881
24,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,810885007280,755.195513,0.737496
25,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,749349269976,697.885891,0.681529
26,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,742607523648,691.607151,0.675398
27,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,652378354736,607.574689,0.593335
28,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,44,448369649728,417.576777,0.407790
29,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,1177819040352,1096.929461,1.071220
30,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,900947073792,839.072348,0.819407
31,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,1344634850752,1252.288791,1.222938
32,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,1308759366976,1218.877143,1.190310
33,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,1163644300768,1083.728206,1.058328
34,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,1396187707488,1300.301130,1.269825
35,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,1493022752224,1390.485794,1.357896
36,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,1332466130560,1240.955787,1.211871
37,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,1494722057856,1392.068395,1.359442
38,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,1378357653208,1283.695598,1.253609
39,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,1486649897920,1384.550610,1.352100
40,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,124,1623154734464,1511.680646,1.476251
41,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,44,263222446080,245.145006,0.239399
42,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,44,180810138960,168.392564,0.164446
43,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,130,1267759419680,1180.692967,1.153020
44,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,0,0,0.000000,0.000000
45,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,130,1421430215376,1323.810048,1.292783
46,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,122,1080410779808,1006.210949,0.982628
47,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,130,1358464288480,1265.168459,1.235516
48,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,130,1433952346208,1335.472191,1.304172
49,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,130,1398715978400,1302.655766,1.272125
50,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,130,1532636304160,1427.378789,1.393925
51,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,130,1610341851040,1499.747719,1.464597
52,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,130,1068283609120,994.916641,0.971598
53,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,130,1384252057760,1289.185190,1.258970
54,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,130,1328611134240,1237.365542,1.208365
55,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,130,1325452625120,1234.423951,1.205492
56,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,130,1531352619680,1426.183264,1.392757

In [16]:
sum(size_df['total_tb'])

49.11428224330666

In [43]:
assets_processing = pd.read_excel(summary_path,sheet_name='assets_processing')

In [44]:
delete_df = assets_processing[assets_processing['preprocessed']=='yes']

In [45]:
delete_df

,session_id,subject_id,session_dir,session_type,behavior,behavior_processed,alignment_method,behavior_videos,dynamic_data,preprocessed,preprocess_method,postprocessed,ref_stack,ref_volume,local_vasculature,vasculature_map,launcher_data,metadata,uploaded
0,803496_2025-07-01_14-56-10,803496,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,expression_check,no,no,NaN,no,yes,yes,summarize_NoLoCo,no,yes,no,no,yes,no,no,no
1,809436_2025-07-25_13-02-10,803496,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
2,809436_2025-07-28_08-04-39,803496,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
3,803496_2025-07-29_13-34-35,803496,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
4,803496_2025-07-30_10-05-23,803496,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
5,803496_2025-07-31_09-43-28,803496,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel+,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
6,803496_2025-08-01_13-22-49,803496,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel+,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
7,804730_2025-07-07_08-47-41,804730,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,expression_check,no,no,NaN,no,yes,yes,summarize_NoLoCo,no,yes,no,no,yes,no,no,no
8,804730_2025-07-25_14-08-35,804730,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
9,804730_2025-07-28_13-57-34,804730,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
10,804730_2025-07-29_14-55-04,804730,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
11,804730_2025-07-30_11-11-11,804730,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
12,804730_2025-07-31_11-45-27,804730,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel+,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
13,804730_2025-08-01_14-22-38,804730,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel+,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
14,804733_2025-07-14_15-14-24,804733,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,expression_check,no,no,NaN,no,yes,yes,summarize_NoLoCo,no,yes,no,no,yes,no,no,no
15,804733_2025-07-25_15-17-00,804733,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
16,804733_2025-07-28_19-00-06,804733,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
17,804733_2025-07-29_16-02-24,804733,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
18,804733_2025-07-30_12-59-44,804733,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
19,804733_2025-07-31_13-29-01,804733,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel+,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
20,804733_2025-08-01_15-20-32,804733,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel+,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
21,810196_2025-07-14_18-16-47,810196,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,expression_check,no,no,NaN,no,yes,yes,summarize_NoLoCo,no,yes,no,no,yes,no,no,no
22,810196_2025-07-25_16-24-20,810196,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
23,810196_2025-07-28_19-59-05,810196,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
24,810196_2025-07-29_17-02-41,810196,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
25,810196_2025-07-31_08-28-08,810196,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
26,810196_2025-07-31_14-19-46,810196,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel+,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
27,810196_2025-08-01_16-37-27,810196,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel+,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
33,809047_2025-10-03_16-13-46,809047,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,expression_check,no,no,NaN,no,yes,yes,summarize_NoLoCo,no,yes,no,no,yes,no,no,no
34,809047_2025-10-29_10-16-32,809047,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
35,809047_2025-10-30_10-06-43,809047,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
36,809047_2025-10-31_12-00-50,809047,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
37,809047_2025-11-01_17-51-59,809047,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
38,809047_2025-11-05_10-13-00,809047,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel+,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
39,809047_2025-11-06_11-05-31,809047,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel+,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
41,803121_2025-10-29_11-19-29,803121,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
42,803121_2025-10-30_11-13-32,803121,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
43,803121_2025-10-31_13-05-26,803121,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
44,803121_2025-11-01_19-00-21,803121,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
45,803121_2025-11-05_11-16-57,803121,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel+,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
46,803121_2025-11-06_12-12-23,803121,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel+,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,no,no,yes,no,no,no
55,2026-01-08_826031,826031,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,expression_check,no,no,NaN,no,yes,yes,extractDendrites,no,yes,no,no,yes,yes,no,no
66,2026-01-08_826032,826032,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,expression_check,no,no,NaN,no,yes,yes,extractDendrites,no,yes,no,no,yes,yes,no,no
77,826033_2026-02-17_13-13-55,826033,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,yes,no,yes,yes,no,no
78,826033_2026-02-18_11-57-04,826033,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,yes,no,yes,yes,no,no
79,826033_2026-02-19_13-47-57,826033,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,frame_modclass_affine_anchored_edges,yes,yes,yes,summarize_LoCo,no,yes,yes,no,yes,yes,no,no
80,826033_2026-02-21_09-23-34,826033,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,bv_photodiode_piecewise,yes,yes,yes,summarize_LoCo,no,yes,yes,no,yes,yes,no,no
81,826033_2026-02-23_10-45-21,826033,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,bv_photodiode_piecewise,yes,yes,yes,summarize_LoCo,no,yes,yes,yes,yes,yes,no,no
82,826033_2026-02-24_14-14-45,826033,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,bv_photodiode_piecewise,yes,yes,yes,summarize_LoCo,no,yes,yes,yes,yes,yes,no,no
83,826033_2026-02-25_08-49-29,826033,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel,yes,yes,bv_photodiode_piecewise,yes,yes,yes,summarize_LoCo,no,yes,yes,yes,yes,yes,no,no
84,826033_2026-02-26_12-40-54,826033,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel+,yes,yes,bv_photodiode_piecewise,yes,yes,yes,summarize_LoCo,no,yes,yes,yes,yes,yes,no,no
85,826033_2026-02-27_13-53-35,826033,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,novel+,yes,yes,bv_photodiode_piecewise,yes,yes,yes,summarize_LoCo,no,yes,yes,yes,yes,yes,no,no
88,834788_2026-03-02_10-18-42,834788,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,bv_photodiode_piecewise,yes,yes,yes,summarize_LoCo,no,yes,yes,yes,yes,yes,no,no
89,834788_2026-03-03_09-22-19,834788,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,bv_photodiode_piecewise,yes,yes,yes,summarize_LoCo,no,yes,yes,yes,yes,yes,no,no
90,834788_2026-03-04_08-43-07,834788,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,bv_photodiode_piecewise,yes,yes,yes,summarize_LoCo,no,yes,yes,yes,yes,yes,no,no
91,834788_2026-03-05_08-11-16,834788,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,bv_photodiode_piecewise,yes,yes,yes,NaN,no,yes,yes,yes,yes,yes,no,no
96,838410_2026-03-02_12-40-55,838410,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,familiar,yes,yes,bv_photodiode_piecewise,yes,yes,yes,summarize_LoCo,no,yes,yes,yes,yes,yes,no,no

In [51]:
import os
import glob
from pathlib import Path
import pandas as pd
from datetime import datetime

key_match = 'instrument.json'
dry_run = False  # set to False to actually delete files

# choose where to save the log
log_dir = Path.cwd() / 'deletion_logs'
log_dir.mkdir(parents=True, exist_ok=True)

timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
log_csv = log_dir / f'instrument_delete_log_{timestamp}.csv'
summary_csv = log_dir / f'instrument_delete_summary_{timestamp}.csv'

file_log = []
session_summary = []

for idx, row in session_df.iterrows():
    sess_path = row['session_dir']   # change if needed
    try:
        alignment_paths = glob.glob(
            os.path.join(sess_path, '**', key_match),
            recursive=True
        )
    except:
        alignment_paths = glob.glob(
            os.path.join(sess_path, key_match),
            recursive=True
        )  
    
    matched_files = [p for p in alignment_paths if os.path.isfile(p)]

    print(f'\nSession: {sess_path}')
    print(f'Found {len(matched_files)} matching files')

    deleted_count = 0
    deleted_bytes = 0
    error_count = 0

    for path in matched_files:
        size_bytes = os.path.getsize(path)
        status = None
        error_msg = ''

        if dry_run:
            status = 'would_delete'
            print(f'[DRY RUN] Would delete: {path}')
            deleted_count += 1
            deleted_bytes += size_bytes
        else:
            try:
                os.remove(path)
                status = 'deleted'
                print(f'[DELETED] {path}')
                deleted_count += 1
                deleted_bytes += size_bytes
            except Exception as e:
                status = 'error'
                error_msg = str(e)
                error_count += 1
                print(f'[ERROR] {path}: {e}')

        file_log.append({
            'session_path': sess_path,
            'file_path': path,
            'file_name': Path(path).name,
            'size_bytes': size_bytes,
            'size_gb': size_bytes / (1024**3),
            'size_tb': size_bytes / (1024**4),
            'status': status,
            'error': error_msg,
            'dry_run': dry_run,
        })

    session_summary.append({
        'session_path': sess_path,
        'n_files_matched': len(matched_files),
        'n_files_deleted_or_would_delete': deleted_count,
        'n_errors': error_count,
        'total_size_gb': deleted_bytes / (1024**3),
        'total_size_tb': deleted_bytes / (1024**4),
        'dry_run': dry_run,
    })

# save detailed per-file log
file_log_df = pd.DataFrame(file_log)
file_log_df.to_csv(log_csv, index=False)

# save per-session summary
summary_df = pd.DataFrame(session_summary)
summary_df.to_csv(summary_csv, index=False)

print(f'\nDetailed log saved to:\n{log_csv}')
print(f'Summary log saved to:\n{summary_csv}')

summary_df

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-01_803496
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-25_803496
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-25_803496\809436_2025-07-25_13-02-10\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-28_803496
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-28_803496\809436_2025-07-28_08-04-39\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-29_803496
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-29_803496\803496_2025-07-29_13-34-35\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-30_803496
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-30_803496\803496_2025-07-30_10-05-23\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-31_803496
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-31_803496\803496_2025-07-31_09-43-28\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-08-01_803496
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-08-01_803496\803496_2025-08-01_13-22-49\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-07_804730
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-25_804730
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-25_804730\804730_2025-07-25_14-08-35\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-28_804730
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-28_804730\804730_2025-07-28_13-57-34\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-29_804730
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-29_804730\804730_2025-07-29_14-55-04\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-30_804730
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-30_804730\804730_2025-07-30_11-11-11\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-31_804730
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-31_804730\804730_2025-07-31_11-45-27\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-08-01_804730
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-08-01_804730\804730_2025-08-01_14-22-38\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-14_804733
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-25_804733
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-25_804733\804733_2025-07-25_15-17-00\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-28_804733
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-28_804733\804733_2025-07-28_19-00-06\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-29_804733
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-29_804733\804733_2025-07-29_16-02-24\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-30_804733
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-30_804733\804733_2025-07-30_12-59-44\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-31_804733
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-31_804733\804733_2025-07-31_13-29-01\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-08-01_804733
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-08-01_804733\804733_2025-08-01_15-20-32\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-14_810196
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-25_810196
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-25_810196\810196_2025-07-25_16-24-20\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-28_810196
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-28_810196\810196_2025-07-28_19-59-05\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-29_810196
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-29_810196\810196_2025-07-29_17-02-41\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-30_810196
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-30_810196\810196_2025-07-31_08-28-08\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-31_810196
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-31_810196\810196_2025-07-31_14-19-46\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-08-01_810196
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-08-01_810196\810196_2025-08-01_16-37-27\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\810196\810196_2026-02-19_09-25-03
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809043\2025-08-27_809043
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809043\2025-12-04_809043_BigVolume
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809044\2025-08-27_809044
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809044\2025-12-04_809044_BigVolume
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-03_809047
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-29_809047
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-29_809047\809047_2025-10-29_10-16-32\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-30_809047
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-30_809047\809047_2025-10-30_10-06-43\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-31_809047
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-31_809047\809047_2025-10-31_12-00-50\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-01_809047
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-01_809047\809047_2025-11-01_17-51-59\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-05_809047
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-05_809047\809047_2025-11-05_10-13-00\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-06_809047
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-06_809047\809047_2025-11-06_11-05-31\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-06_803121
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-29_803121
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-29_803121\803121_2025-10-29_11-19-29\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-30_803121
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-30_803121\803121_2025-10-30_11-13-32\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-31_803121
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-31_803121\803121_2025-10-31_13-05-26\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-01_803121
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-01_803121\803121_2025-11-01_19-00-21\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-05_803121
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-05_803121\803121_2025-11-05_11-16-57\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-06_803121
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-06_803121\803121_2025-11-06_12-12-23\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\803121\803121_2026-02-19_11-06-55
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814591\2025-11-07_814591
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814591\2026-01-13_814591_BigStacks
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814593\2025-11-07_814593
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814593\2026-01-13_814593_BigStacks
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\825854\2026-01-12_825854
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\825855\2026-01-12_825855
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\824806\2026-01-08_824806
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\2026-01-08_826031
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-01-30_15-04-02
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-01-30_15-04-02\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-01_11-01-50
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-01_11-01-50\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-02_10-23-53
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-02_10-23-53\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-03_14-21-45
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-03_14-21-45\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-04_12-15-34
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-04_12-15-34\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-05_09-28-56
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-05_09-28-56\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-06_10-21-20
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-06_10-21-20\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-10_10-48-51
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-10_10-48-51\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-11_12-42-21
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-11_12-42-21\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-12_07-43-37
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-12_07-43-37\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\2026-01-08_826032
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-01-29_12-59-37
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-01-29_12-59-37\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-01-30_16-31-08
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-01-30_16-31-08\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-02_08-24-52
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-02_08-24-52\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-03_16-02-38
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-03_16-02-38\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-04_13-49-07
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-04_13-49-07\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-05_13-18-03
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-05_13-18-03\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-06_11-45-33
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-06_11-45-33\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-10_13-02-11
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-10_13-02-11\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-11_14-46-30
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-11_14-46-30\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\2025-12-01_826033
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-17_13-13-55
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-17_13-13-55\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-18_11-57-04
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-18_11-57-04\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-19_13-47-57
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-19_13-47-57\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-21_09-23-34
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-21_09-23-34\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-23_10-45-21
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-23_10-45-21\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-24_14-14-45
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-24_14-14-45\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-25_08-49-29
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-25_08-49-29\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-26_12-40-54
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-26_12-40-54\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-27_13-53-35
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-27_13-53-35\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826034\2025-12-01_826034
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-02-13_15-22-44
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-02-13_15-22-44\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-02_10-18-42
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-02_10-18-42\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-03_09-22-19
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-03_09-22-19\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-04_08-43-07
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-05_08-11-16
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-07_11-28-35
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-07_11-28-35\slap2\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-08_12-21-24
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-08_12-21-24\slap2\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-09_09-07-35
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-09_09-07-35\slap2\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-02-13_15-49-00
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-02-13_15-49-00\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-02_12-40-55
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-02_12-40-55\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-03_13-49-07
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-03_13-49-07\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-04_12-54-47
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-05_10-16-37
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-07_13-21-42
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-07_13-21-42\slap2\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-08_14-02-23
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-08_14-02-23\slap2\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-09_11-04-01
Found 1 matching files
[DELETED] \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-09_11-04-01\slap2\instrument.json

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836173\836173_2026-02-13_16-42-29
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836174\836174_2026-02-13_16-17-06
Found 0 matching files

Session: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\836172\836172_2026-02-23_13-56-01
Found 0 matching files

Detailed log saved to:
C:\Users\andrew.shelton\Dropbox\allen institute\Python_Code\ams\ophys\vip-slap2-analysis\notebooks\metadata\deletion_logs\instrument_delete_log_2026-03-09_13-31-35.csv
Summary log saved to:
C:\Users\andrew.shelton\Dropbox\allen institute\Python_Code\ams\ophys\vip-slap2-analysis\notebooks\metadata\deletion_logs\instrument_delete_summary_2026-03-09_13-31-35.csv

,session_path,n_files_matched,n_files_deleted_or_would_delete,n_errors,total_size_gb,total_size_tb,dry_run
0,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,0,0,0,0.000000,0.000000e+00,False
1,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,1,1,0,0.000028,2.736488e-08,False
2,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,1,1,0,0.000025,2.449360e-08,False
3,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,1,1,0,0.000025,2.449360e-08,False
4,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,1,1,0,0.000025,2.449360e-08,False
...,...,...,...,...,...,...,...
101,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,1,1,0,0.000030,2.976867e-08,False
102,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,1,1,0,0.000030,2.976867e-08,False
103,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,0,0,0,0.000000,0.000000e+00,False
104,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,0,0,0,0.000000,0.000000e+00,False
105,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,0,0,0,0.000000,0.000000e+00,False