In [15]:
import os
import re
import glob
import pandas as pd
from pathlib import Path
from slap2_processing.src import generate_instrument_json as gij
from slap2_processing.src.generate_acquisition_json import Slap2VCOAcquisitionEtl

In [16]:
basepath = r'\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics'
summary_path = glob.glob(os.path.join(basepath,'**summary.xlsx'))[0]
summary_df = pd.read_excel(summary_path,sheet_name='subjects')
session_df = pd.read_excel(summary_path,sheet_name='sessions')

In [17]:
session_df

,session_id,subject_id,session_#,session_date,indicator1,indicator2,dmd1_depth,dmd2_depth,paradigm,session_type,...,instrument_id,camera_type,has raster ROI?,has integration roi?,behavior_rig,quality,flags,session_dir,purpose,notes
0,803496_2025-07-01_14-56-10,803496,1,2025-07-01,iGluSnFR4,NaN,25,100,change_detection_passive,expression_check,...,SLAP2_1,NaN,yes,no,VCO.1,good,NaN,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,NaN,NaN
1,809436_2025-07-25_13-02-10,803496,2,2025-07-25,iGluSnFR4,NaN,25,100,change_detection_passive,familiar,...,SLAP2_1,vimba,yes,no,VCO.1,good,NaN,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,NaN,NaN
2,809436_2025-07-28_08-04-39,803496,3,2025-07-28,iGluSnFR4,NaN,25,100,change_detection_passive,familiar,...,SLAP2_1,vimba,yes,no,VCO.1,good,NaN,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,NaN,NaN
3,803496_2025-07-29_13-34-35,803496,4,2025-07-29,iGluSnFR4,NaN,25,100,change_detection_passive,familiar,...,SLAP2_1,vimba,yes,no,VCO.1,good,NaN,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,NaN,NaN
4,803496_2025-07-30_10-05-23,803496,5,2025-07-30,iGluSnFR4,NaN,25,100,change_detection_passive,novel,...,SLAP2_1,vimba,yes,no,VCO.1,good,NaN,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,838410_2026-03-08_14-02-23,838410,7,2026-03-08,iGluSnFR4,RCaMP3,50,200,change_detection_passive,novel+,...,SLAP2_1,spinnaker,yes,no,VCO.1,good,Acquisition saved to a single file,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,NaN,NaN
102,838410_2026-03-09_11-04-01,838410,8,2026-03-09,iGluSnFR4,RCaMP3,50,200,change_detection_passive,novel+,...,SLAP2_1,spinnaker,yes,no,VCO.1,poor,Too much motion on DMD2,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,NaN,NaN
103,836173_2026-02-13_16-42-29,836173,1,2026-02-13,iGluSnFR4,RCaMP3,50,200,change_detection_passive,expression_check,...,SLAP2_1,NaN,yes,no,VCO.1,good,NaN,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,NaN,NaN
104,836174_2026-02-13_16-17-06,836174,1,2026-02-13,iGluSnFR4,RCaMP3,50,200,change_detection_passive,expression_check,...,SLAP2_1,NaN,yes,no,VCO.1,good,NaN,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,NaN,NaN
105,836172_2026-02-23_13-56-01,836172,1,2026-02-23,ASAP7y,NaN,50,200,change_detection_passive,expression_check,...,SLAP2_1,NaN,yes,no,VCO.1,good,NaN,\\allen\aind\scratch\ophys\Andrew\VIP_synaptic...,NaN,Expression looked dense overall across a wide ...

In [18]:
def find_session_root_subdir(session_dir: Path, mouse: int | str) -> Path:
    """
    Find the subdirectory inside `session_dir` whose name matches:
        nnnnnn_yyyy-mm-dd_hh-mm-ss
    where nnnnnn == mouse id (6 digits).
    Returns the matching Path, or raises ValueError with a helpful message.
    """
    mouse = str(mouse)
    pattern = re.compile(rf"^{re.escape(mouse)}_\d{{4}}-\d{{2}}-\d{{2}}_\d{{2}}-\d{{2}}-\d{{2}}$")

    matches = [p for p in session_dir.iterdir() if p.is_dir() and pattern.match(p.name)]
    if len(matches) == 0:
        raise ValueError(f"No matching destination subdir in {session_dir}")
    if len(matches) > 1:
        raise ValueError(f"Multiple matching destination subdirs in {session_dir}: {[m.name for m in matches]}")
    return matches[0]

### Generate instrument.json

In [38]:
for idx, row in session_df.iterrows():
    try:
        sess = find_session_root_subdir(Path(row['session_dir']), mouse=row['subject_id'])
    except Exception:
        sess = Path(row['session_dir'])

    out_path = Path(sess) / "instrument.json"
    print(f"Attempting to generate instrument.json for {Path(sess).stem}")

    try:
        gij.generate_instrument_json(
            Path(sess),
            use_vimba=(row['camera_type'] == 'vimba')
        )

        if out_path.exists():
            print(f"SUCCESS: wrote {out_path}")
        else:
            print(f"NO FILE FOUND AFTER RUN: expected {out_path}")

    except BaseException as e:
        print(f"FAILED: {type(e).__name__}: {e}")

    print()

Attempting to generate instrument.json for 803496_2025-07-01_14-56-10
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-01_803496\803496_2025-07-01_14-56-10
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-01_803496\803496_2025-07-01_14-56-10\instrument.json

Attempting to generate instrument.json for 803496_2025-07-25_13-02-10
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-25_803496\803496_2025-07-25_13-02-10
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-25_803496\803496_2025-07-25_13-02-10\instrument.json

Attempting to generate instrument.json for 803496_2025-07-28_08-04-39
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-28_803496\803496_2025-07-28_08-04-39
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-28_803496\803496_2025-07-28_08-04-39\instrument.json

Attempting to generate instrument.json for 803496_2025-07-29_13-34-35
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-29_803496\803496_2025-07-29_13-34-35
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-29_803496\803496_2025-07-29_13-34-35\instrument.json

Attempting to generate instrument.json for 803496_2025-07-30_10-05-23
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-30_803496\803496_2025-07-30_10-05-23
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-30_803496\803496_2025-07-30_10-05-23\instrument.json

Attempting to generate instrument.json for 803496_2025-07-31_09-43-28
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-31_803496\803496_2025-07-31_09-43-28
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-07-31_803496\803496_2025-07-31_09-43-28\instrument.json

Attempting to generate instrument.json for 803496_2025-08-01_13-22-49
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-08-01_803496\803496_2025-08-01_13-22-49
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803496\2025-08-01_803496\803496_2025-08-01_13-22-49\instrument.json

Attempting to generate instrument.json for 804730_2025-07-07_08-47-41
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-07_804730\804730_2025-07-07_08-47-41
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-07_804730\804730_2025-07-07_08-47-41\instrument.json

Attempting to generate instrument.json for 804730_2025-07-25_14-08-35
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-25_804730\804730_2025-07-25_14-08-35
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-25_804730\804730_2025-07-25_14-08-35\instrument.json

Attempting to generate instrument.json for 804730_2025-07-28_13-57-34
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-28_804730\804730_2025-07-28_13-57-34
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-28_804730\804730_2025-07-28_13-57-34\instrument.json

Attempting to generate instrument.json for 804730_2025-07-29_14-55-04
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-29_804730\804730_2025-07-29_14-55-04
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-29_804730\804730_2025-07-29_14-55-04\instrument.json

Attempting to generate instrument.json for 804730_2025-07-30_11-11-11
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-30_804730\804730_2025-07-30_11-11-11
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-30_804730\804730_2025-07-30_11-11-11\instrument.json

Attempting to generate instrument.json for 804730_2025-07-31_11-45-27
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-31_804730\804730_2025-07-31_11-45-27
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-07-31_804730\804730_2025-07-31_11-45-27\instrument.json

Attempting to generate instrument.json for 804730_2025-08-01_14-22-38
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-08-01_804730\804730_2025-08-01_14-22-38
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804730\2025-08-01_804730\804730_2025-08-01_14-22-38\instrument.json

Attempting to generate instrument.json for 804733_2025-07-14_15-14-24
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-14_804733\804733_2025-07-14_15-14-24
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-14_804733\804733_2025-07-14_15-14-24\instrument.json

Attempting to generate instrument.json for 804733_2025-07-25_15-17-00
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-25_804733\804733_2025-07-25_15-17-00
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-25_804733\804733_2025-07-25_15-17-00\instrument.json

Attempting to generate instrument.json for 804733_2025-07-28_19-00-06
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-28_804733\804733_2025-07-28_19-00-06
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-28_804733\804733_2025-07-28_19-00-06\instrument.json

Attempting to generate instrument.json for 804733_2025-07-29_16-02-24
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-29_804733\804733_2025-07-29_16-02-24
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-29_804733\804733_2025-07-29_16-02-24\instrument.json

Attempting to generate instrument.json for 804733_2025-07-30_12-59-44
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-30_804733\804733_2025-07-30_12-59-44
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-30_804733\804733_2025-07-30_12-59-44\instrument.json

Attempting to generate instrument.json for 804733_2025-07-31_13-29-01
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-31_804733\804733_2025-07-31_13-29-01
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-07-31_804733\804733_2025-07-31_13-29-01\instrument.json

Attempting to generate instrument.json for 804733_2025-08-01_15-20-32
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-08-01_804733\804733_2025-08-01_15-20-32
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\804733\2025-08-01_804733\804733_2025-08-01_15-20-32\instrument.json

Attempting to generate instrument.json for 810196_2025-07-14_18-16-47
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-14_810196\810196_2025-07-14_18-16-47
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-14_810196\810196_2025-07-14_18-16-47\instrument.json

Attempting to generate instrument.json for 810196_2025-07-25_16-24-20
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-25_810196\810196_2025-07-25_16-24-20
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-25_810196\810196_2025-07-25_16-24-20\instrument.json

Attempting to generate instrument.json for 810196_2025-07-28_19-59-05

Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-28_810196\810196_2025-07-28_19-59-05
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-28_810196\810196_2025-07-28_19-59-05\instrument.json

Attempting to generate instrument.json for 810196_2025-07-29_17-02-41
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-29_810196\810196_2025-07-29_17-02-41
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-29_810196\810196_2025-07-29_17-02-41\instrument.json

Attempting to generate instrument.json for 810196_2025-07-31_08-28-08
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-30_810196\810196_2025-07-31_08-28-08
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-30_810196\810196_2025-07-31_08-28-08\instrument.json

Attempting to generate instrument.json for 810196_2025-07-31_14-19-46
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-31_810196\810196_2025-07-31_14-19-46
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-07-31_810196\810196_2025-07-31_14-19-46\instrument.json

Attempting to generate instrument.json for 810196_2025-08-01_16-37-27
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-08-01_810196\810196_2025-08-01_16-37-27
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\810196\2025-08-01_810196\810196_2025-08-01_16-37-27\instrument.json

Attempting to generate instrument.json for 810196_2026-02-19_09-25-03
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\810196\810196_2026-02-19_09-25-03
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\810196\810196_2026-02-19_09-25-03\instrument.json

Attempting to generate instrument.json for 809043_2025-08-27_12-26-49
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809043\2025-08-27_809043\809043_2025-08-27_12-26-49
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809043\2025-08-27_809043\809043_2025-08-27_12-26-49\instrument.json

Attempting to generate instrument.json for 2025-12-04_809043_BigVolume
FAILED: SystemExit: Not a valid data asset directory: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809043\2025-12-04_809043_BigVolume
Must have at least one immediate subfolder among: behavior, behavior-videos, slap2.
Found subfolders: slap2_809043_2025-12-04_14-24-16.

Attempting to generate instrument.json for 809044_2025-08-27_13-10-38
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809044\2025-08-27_809044\809044_2025-08-27_13-10-38
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809044\2025-08-27_809044\809044_2025-08-27_13-10-38\instrument.json

Attempting to generate instrument.json for 2025-12-04_809044_BigVolume
FAILED: SystemExit: Not a valid data asset directory: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\809044\2025-12-04_809044_BigVolume
Must have at least one immediate subfolder among: behavior, behavior-videos, slap2.
Found subfolders: slap2_809044_2025-12-04_16-26-24.

Attempting to generate instrument.json for 809047_2025-10-03_16-13-46
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-03_809047\809047_2025-10-03_16-13-46
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-03_809047\809047_2025-10-03_16-13-46\instrument.json

Attempting to generate instrument.json for 809047_2025-10-29_10-16-32
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-29_809047\809047_2025-10-29_10-16-32
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-29_809047\809047_2025-10-29_10-16-32\instrument.json

Attempting to generate instrument.json for 809047_2025-10-30_10-06-43
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-30_809047\809047_2025-10-30_10-06-43
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-30_809047\809047_2025-10-30_10-06-43\instrument.json

Attempting to generate instrument.json for 809047_2025-10-31_12-00-50
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-31_809047\809047_2025-10-31_12-00-50
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-10-31_809047\809047_2025-10-31_12-00-50\instrument.json

Attempting to generate instrument.json for 809047_2025-11-01_17-51-59
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-01_809047\809047_2025-11-01_17-51-59
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-01_809047\809047_2025-11-01_17-51-59\instrument.json

Attempting to generate instrument.json for 809047_2025-11-05_10-13-00
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-05_809047\809047_2025-11-05_10-13-00
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-05_809047\809047_2025-11-05_10-13-00\instrument.json

Attempting to generate instrument.json for 809047_2025-11-06_11-05-31
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-06_809047\809047_2025-11-06_11-05-31
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\809047\2025-11-06_809047\809047_2025-11-06_11-05-31\instrument.json

Attempting to generate instrument.json for 803121_2025-10-06_17-44-40
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-06_803121\803121_2025-10-06_17-44-40
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-06_803121\803121_2025-10-06_17-44-40\instrument.json

Attempting to generate instrument.json for 803121_2025-10-29_11-19-29
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-29_803121\803121_2025-10-29_11-19-29
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-29_803121\803121_2025-10-29_11-19-29\instrument.json

Attempting to generate instrument.json for 803121_2025-10-30_11-13-32
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-30_803121\803121_2025-10-30_11-13-32
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-30_803121\803121_2025-10-30_11-13-32\instrument.json

Attempting to generate instrument.json for 803121_2025-10-31_13-05-26
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-31_803121\803121_2025-10-31_13-05-26
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-31_803121\803121_2025-10-31_13-05-26\instrument.json

Attempting to generate instrument.json for 803121_2025-11-01_19-00-21
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-01_803121\803121_2025-11-01_19-00-21
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-01_803121\803121_2025-11-01_19-00-21\instrument.json

Attempting to generate instrument.json for 803121_2025-11-05_11-16-57
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-05_803121\803121_2025-11-05_11-16-57
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-05_803121\803121_2025-11-05_11-16-57\instrument.json

Attempting to generate instrument.json for 803121_2025-11-06_12-12-23
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-06_803121\803121_2025-11-06_12-12-23
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-06_803121\803121_2025-11-06_12-12-23\instrument.json

Attempting to generate instrument.json for 803121_2026-02-19_11-06-55

Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\803121\803121_2026-02-19_11-06-55
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\803121\803121_2026-02-19_11-06-55\instrument.json

Attempting to generate instrument.json for 814591_2025-11-07_10-21-49
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814591\2025-11-07_814591\814591_2025-11-07_10-21-49
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814591\2025-11-07_814591\814591_2025-11-07_10-21-49\instrument.json

Attempting to generate instrument.json for 814591_2026-01-13_10-37-24
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814591\2026-01-13_814591_BigStacks\814591_2026-01-13_10-37-24
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814591\2026-01-13_814591_BigStacks\814591_2026-01-13_10-37-24\instrument.json

Attempting to generate instrument.json for 814593_2025-11-07_13-36-49
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814593\2025-11-07_814593\814593_2025-11-07_13-36-49
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814593\2025-11-07_814593\814593_2025-11-07_13-36-49\instrument.json

Attempting to generate instrument.json for 814593_2026-01-13_13-41-32
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814593\2026-01-13_814593_BigStacks\814593_2026-01-13_13-41-32
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\structure_volume\814593\2026-01-13_814593_BigStacks\814593_2026-01-13_13-41-32\instrument.json

Attempting to generate instrument.json for 825854_2026-01-12_11-09-10
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\825854\2026-01-12_825854\825854_2026-01-12_11-09-10
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\825854\2026-01-12_825854\825854_2026-01-12_11-09-10\instrument.json

Attempting to generate instrument.json for 825855_2026-01-12_11-56-04
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\825855\2026-01-12_825855\825855_2026-01-12_11-56-04
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\825855\2026-01-12_825855\825855_2026-01-12_11-56-04\instrument.json

Attempting to generate instrument.json for 824806_2026-01-08_11-12-01
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\824806\2026-01-08_824806\824806_2026-01-08_11-12-01
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\NM\824806\2026-01-08_824806\824806_2026-01-08_11-12-01\instrument.json

Attempting to generate instrument.json for 826031_2026-01-08_12-11-08
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\2026-01-08_826031\826031_2026-01-08_12-11-08
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\2026-01-08_826031\826031_2026-01-08_12-11-08\instrument.json

Attempting to generate instrument.json for 826031_2026-01-30_15-04-02
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-01-30_15-04-02
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-01-30_15-04-02\instrument.json

Attempting to generate instrument.json for 826031_2026-02-01_11-01-50
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-01_11-01-50
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-01_11-01-50\instrument.json

Attempting to generate instrument.json for 826031_2026-02-02_10-23-53
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-02_10-23-53
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-02_10-23-53\instrument.json

Attempting to generate instrument.json for 826031_2026-02-03_14-21-45
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-03_14-21-45
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-03_14-21-45\instrument.json

Attempting to generate instrument.json for 826031_2026-02-04_12-15-34
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-04_12-15-34
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-04_12-15-34\instrument.json

Attempting to generate instrument.json for 826031_2026-02-05_09-28-56
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-05_09-28-56
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-05_09-28-56\instrument.json

Attempting to generate instrument.json for 826031_2026-02-06_10-21-20
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-06_10-21-20
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-06_10-21-20\instrument.json

Attempting to generate instrument.json for 826031_2026-02-10_10-48-51
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-10_10-48-51
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-10_10-48-51\instrument.json

Attempting to generate instrument.json for 826031_2026-02-11_12-42-21
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-11_12-42-21
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-11_12-42-21\instrument.json

Attempting to generate instrument.json for 826031_2026-02-12_07-43-37
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-12_07-43-37
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826031\826031_2026-02-12_07-43-37\instrument.json

Attempting to generate instrument.json for 826032_2026-01-08_15-19-44
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\2026-01-08_826032\826032_2026-01-08_15-19-44
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\2026-01-08_826032\826032_2026-01-08_15-19-44\instrument.json

Attempting to generate instrument.json for 826032_2026-01-29_12-59-37
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-01-29_12-59-37
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-01-29_12-59-37\instrument.json

Attempting to generate instrument.json for 826032_2026-01-30_16-31-08
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-01-30_16-31-08
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-01-30_16-31-08\instrument.json

Attempting to generate instrument.json for 826032_2026-02-02_08-24-52
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-02_08-24-52
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-02_08-24-52\instrument.json

Attempting to generate instrument.json for 826032_2026-02-03_16-02-38

Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-03_16-02-38
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-03_16-02-38\instrument.json

Attempting to generate instrument.json for 826032_2026-02-04_13-49-07
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-04_13-49-07
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-04_13-49-07\instrument.json

Attempting to generate instrument.json for 826032_2026-02-05_13-18-03
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-05_13-18-03
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-05_13-18-03\instrument.json

Attempting to generate instrument.json for 826032_2026-02-06_11-45-33
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-06_11-45-33
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-06_11-45-33\instrument.json

Attempting to generate instrument.json for 826032_2026-02-10_13-02-11
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-10_13-02-11
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-10_13-02-11\instrument.json

Attempting to generate instrument.json for 826032_2026-02-11_14-46-30
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-11_14-46-30
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\826032\826032_2026-02-11_14-46-30\instrument.json

Attempting to generate instrument.json for 826033_2025-12-01_10-44-52
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\2025-12-01_826033\826033_2025-12-01_10-44-52
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\2025-12-01_826033\826033_2025-12-01_10-44-52\instrument.json

Attempting to generate instrument.json for 826033_2026-02-17_13-13-55
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-17_13-13-55
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-17_13-13-55\instrument.json

Attempting to generate instrument.json for 826033_2026-02-18_11-57-04
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-18_11-57-04
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-18_11-57-04\instrument.json

Attempting to generate instrument.json for 826033_2026-02-19_13-47-57
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-19_13-47-57
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-19_13-47-57\instrument.json

Attempting to generate instrument.json for 826033_2026-02-21_09-23-34
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-21_09-23-34
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-21_09-23-34\instrument.json

Attempting to generate instrument.json for 826033_2026-02-23_10-45-21
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-23_10-45-21
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-23_10-45-21\instrument.json

Attempting to generate instrument.json for 826033_2026-02-24_14-14-45
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-24_14-14-45
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-24_14-14-45\instrument.json

Attempting to generate instrument.json for 826033_2026-02-25_08-49-29
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-25_08-49-29
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-25_08-49-29\instrument.json

Attempting to generate instrument.json for 826033_2026-02-26_12-40-54
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-26_12-40-54
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-26_12-40-54\instrument.json

Attempting to generate instrument.json for 826033_2026-02-27_13-53-35
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-27_13-53-35
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826033\826033_2026-02-27_13-53-35\instrument.json

Attempting to generate instrument.json for 826034_2025-12-01_11-32-40
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826034\2025-12-01_826034\826034_2025-12-01_11-32-40
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\826034\2025-12-01_826034\826034_2025-12-01_11-32-40\instrument.json

Attempting to generate instrument.json for 834788_2026-02-13_15-22-44
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-02-13_15-22-44
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-02-13_15-22-44\instrument.json

Attempting to generate instrument.json for 834788_2026-03-02_10-18-42
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-02_10-18-42
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-02_10-18-42\instrument.json

Attempting to generate instrument.json for 834788_2026-03-03_09-22-19
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-03_09-22-19
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-03_09-22-19\instrument.json

Attempting to generate instrument.json for 834788_2026-03-04_08-43-07
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-04_08-43-07
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-04_08-43-07\instrument.json

Attempting to generate instrument.json for 834788_2026-03-05_08-11-16
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-05_08-11-16
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-05_08-11-16\instrument.json

Attempting to generate instrument.json for 834788_2026-03-07_11-28-35
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-07_11-28-35
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-07_11-28-35\instrument.json

Attempting to generate instrument.json for 834788_2026-03-08_12-21-24
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-08_12-21-24
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-08_12-21-24\instrument.json

Attempting to generate instrument.json for 834788_2026-03-09_09-07-35

Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-09_09-07-35
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\834788\834788_2026-03-09_09-07-35\instrument.json

Attempting to generate instrument.json for 838410_2026-02-13_15-49-00
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-02-13_15-49-00
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-02-13_15-49-00\instrument.json

Attempting to generate instrument.json for 838410_2026-03-02_12-40-55
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-02_12-40-55
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-02_12-40-55\instrument.json

Attempting to generate instrument.json for 838410_2026-03-03_13-49-07
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-03_13-49-07
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-03_13-49-07\instrument.json

Attempting to generate instrument.json for 838410_2026-03-04_12-54-47
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-04_12-54-47
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-04_12-54-47\instrument.json

Attempting to generate instrument.json for 838410_2026-03-05_10-16-37
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-05_10-16-37
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-05_10-16-37\instrument.json

Attempting to generate instrument.json for 838410_2026-03-07_13-21-42
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-07_13-21-42
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-07_13-21-42\instrument.json

Attempting to generate instrument.json for 838410_2026-03-08_14-02-23
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-08_14-02-23
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-08_14-02-23\instrument.json

Attempting to generate instrument.json for 838410_2026-03-09_11-04-01
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-09_11-04-01
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\838410\838410_2026-03-09_11-04-01\instrument.json

Attempting to generate instrument.json for 836173_2026-02-13_16-42-29
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836173\836173_2026-02-13_16-42-29
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836173\836173_2026-02-13_16-42-29\instrument.json

Attempting to generate instrument.json for 836174_2026-02-13_16-17-06
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836174\836174_2026-02-13_16-17-06
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836174\836174_2026-02-13_16-17-06\instrument.json

Attempting to generate instrument.json for 836172_2026-02-23_13-56-01
Successfully wrote instrument JSON file to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\836172\836172_2026-02-23_13-56-01
SUCCESS: wrote \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\ASAP7\836172\836172_2026-02-23_13-56-01\instrument.json

### Get stimulus parameters

In [20]:
stim_path = r"C:\Users\andrew.shelton\Dropbox\allen institute\Python_Code\ams\Aind.Behavior.ChangeDetection\src\stimuli\images_B"

In [21]:
image_names = os.listdir(stim_path)
image_names

['100075.tiff',
 '216066.tiff',
 '268048.tiff',
 '41006.tiff',
 '69022.tiff',
 'imk01306.tiff',
 'imk01333.tiff',
 'McGill_stairs.tiff']

### Generate acquisition.json

In [37]:
mouse = 803121
process_dirs = session_df[(session_df['subject_id']==mouse)
                          &(session_df['session_type']!='expression_check')
                          &(session_df['session_type']!='volume_imaging')]['session_dir'].values
session_dirs = [find_session_root_subdir(Path(sess),mouse) for sess in process_dirs]
results = []

for sess_dir in session_dirs:
    try:
        etl = Slap2VCOAcquisitionEtl(
            asset_dir=sess_dir,
            output_dir=sess_dir,      
            timing_source="harp",     
            timing_source_column=None,
            save_images=False,
        )
        etl.run_job()

        results.append({
            "session_dir": str(sess_dir),
            "status": "success",
            "error": ""
        })

    except Exception as e:
        results.append({
            "session_dir": str(sess_dir),
            "status": "failed",
            "error": str(e)
        })

results_df = pd.DataFrame(results)
results_df

Asset directory: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-29_803121\803121_2025-10-29_11-19-29
Extracted mouse_id: 803121
Extracted session_datetime: 2025-10-29 11:19:29

Less than 5 trial start or end times found in HARP data. Using SLAP2 frame clock input instead.

Succesfully wrote acquisition JSON to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-29_803121\803121_2025-10-29_11-19-29
Asset directory: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-30_803121\803121_2025-10-30_11-13-32
Extracted mouse_id: 803121
Extracted session_datetime: 2025-10-30 11:13:32

Less than 5 trial start or end times found in HARP data. Using SLAP2 frame clock input instead.

Succesfully wrote acquisition JSON to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-30_803121\803121_2025-10-30_11-13-32
Asset directory: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-31_803121\803121_2025-10-31_13-05-26
Extracted mouse_id: 803121
Extracted session_datetime: 2025-10-31 13:05:26

Less than 5 trial start or end times found in HARP data. Using SLAP2 frame clock input instead.

Succesfully wrote acquisition JSON to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-10-31_803121\803121_2025-10-31_13-05-26
Asset directory: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-01_803121\803121_2025-11-01_19-00-21
Extracted mouse_id: 803121
Extracted session_datetime: 2025-11-01 19:00:21

Less than 5 trial start or end times found in HARP data. Using SLAP2 frame clock input instead.

Succesfully wrote acquisition JSON to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-01_803121\803121_2025-11-01_19-00-21
Asset directory: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-05_803121\803121_2025-11-05_11-16-57
Extracted mouse_id: 803121
Extracted session_datetime: 2025-11-05 11:16:57

Less than 5 trial start or end times found in HARP data. Using SLAP2 frame clock input instead.

Succesfully wrote acquisition JSON to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-05_803121\803121_2025-11-05_11-16-57
Asset directory: \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-06_803121\803121_2025-11-06_12-12-23
Extracted mouse_id: 803121
Extracted session_datetime: 2025-11-06 12:12:23

Less than 5 trial start or end times found in HARP data. Using SLAP2 frame clock input instead.

Succesfully wrote acquisition JSON to \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f\803121\2025-11-06_803121\803121_2025-11-06_12-12-23

                                         session_dir   status error
0  \\allen\aind\scratch\ophys\Andrew\VIP_synaptic...  success
1  \\allen\aind\scratch\ophys\Andrew\VIP_synaptic...  success
2  \\allen\aind\scratch\ophys\Andrew\VIP_synaptic...  success
3  \\allen\aind\scratch\ophys\Andrew\VIP_synaptic...  success
4  \\allen\aind\scratch\ophys\Andrew\VIP_synaptic...  success
5  \\allen\aind\scratch\ophys\Andrew\VIP_synaptic...  success